frontend:
  - changed-files:
      - any-glob-to-any-file: "frontend/**"

backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**"

marketing:
  - changed-files:
      - any-glob-to-any-file: "marketing-site/**"

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
      - any-glob-to-any-file: "docs/**"

ci/cd:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
