services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-super_impress}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - app

  backend:
    build:
      context: ./backend
    image: super-impress-backend
    env_file:
      - backend/.env
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - app

  frontend:
    build:
      context: ./frontend
    image: super-impress-frontend
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env
    depends_on:
      - backend
    networks:
      - app

volumes:
  postgres-data:

networks:
  app:
    driver: bridge
