/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
export type BodyLoginUserGrantType = string | null;

export type BodyLoginUserClientId = string | null;

export type BodyLoginUserClientSecret = string | null;

export interface BodyLoginUser {
	grant_type?: BodyLoginUserGrantType;
	username: string;
	password: string;
	scope?: string;
	client_id?: BodyLoginUserClientId;
	client_secret?: BodyLoginUserClientSecret;
}

/**
 * Schema for confirming email verification.
 */
export interface EmailVerificationConfirm {
	token: string;
}

/**
 * Schema for requesting email verification resend.
 */
export interface EmailVerificationRequest {
	email: string;
}

export type EmailVerificationResponseEmail = string | null;

/**
 * Schema for verification responses.
 */
export interface EmailVerificationResponse {
	message: string;
	email?: EmailVerificationResponseEmail;
}

export interface HTTPValidationError {
	detail?: ValidationError[];
}

/**
 * Schema for changing a user's password.
 */
export interface PasswordChange {
	old_password: string;
	/**
	 * Must contain uppercase, lowercase, digit, and special character
	 * @minLength 8
	 * @maxLength 15
	 */
	new_password: string;
}

/**
 * JWT token response schema.
 */
export interface Token {
	access_token: string;
	token_type: string;
}

/**
 * Schema for creating a new user.
 */
export interface UserCreate {
	email: string;
	/**
	 * Must contain uppercase, lowercase, digit, and special character
	 * @minLength 8
	 * @maxLength 15
	 */
	password: string;
}

/**
 * Schema for user public data (excludes password).
 */
export interface UserPublic {
	email: string;
	id: number;
	email_verified: boolean;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
	loc: ValidationErrorLocItem[];
	msg: string;
	type: string;
}
