/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
export type BodyLoginUserGrantType = string | null;

export type BodyLoginUserClientId = string | null;

export type BodyLoginUserClientSecret = string | null;

export interface BodyLoginUser {
	grant_type?: BodyLoginUserGrantType;
	username: string;
	password: string;
	scope?: string;
	client_id?: BodyLoginUserClientId;
	client_secret?: BodyLoginUserClientSecret;
}

/**
 * Schema for confirming email verification.
 */
export interface EmailVerificationConfirm {
	token: string;
}

/**
 * Schema for requesting email verification resend.
 */
export interface EmailVerificationRequest {
	email: string;
}

export type EmailVerificationResponseEmail = string | null;

/**
 * Schema for verification responses.
 */
export interface EmailVerificationResponse {
	message: string;
	email?: EmailVerificationResponseEmail;
}

export interface HTTPValidationError {
	detail?: ValidationError[];
}

/**
 * Schema for changing a user's password.
 */
export interface PasswordChange {
	old_password: string;
	/**
	 * Must contain uppercase, lowercase, digit, and special character
	 * @minLength 8
	 * @maxLength 15
	 */
	new_password: string;
}

/**
 * Post title
 */
export type PostCreateTitle = string | null;

/**
 * Schema for creating a new post.
 */
export interface PostCreate {
	/** Post title */
	title?: PostCreateTitle;
	/**
	 * Post content
	 * @minLength 1
	 */
	content: string;
	/** Post tags */
	tags?: string[];
	status?: PostStatus;
}

/**
 * Response schema for listing posts.
 */
export interface PostListResponse {
	posts: PostPublic[];
	total: number;
}

/**
 * Post title
 */
export type PostPublicTitle = string | null;

/**
 * Schema for post public data.
 */
export interface PostPublic {
	/** Post title */
	title?: PostPublicTitle;
	/**
	 * Post content
	 * @minLength 1
	 */
	content: string;
	/** Post tags */
	tags?: string[];
	id: number;
	user_id: number;
	status: PostStatus;
	created_at: string;
	updated_at: string;
}

/**
 * Post status enumeration.
 */
export type PostStatus = (typeof PostStatus)[keyof typeof PostStatus];

export const PostStatus = {
	draft: 'draft',
	published: 'published',
	archived: 'archived'
} as const;

export type PostUpdateTitle = string | null;

export type PostUpdateContent = string | null;

export type PostUpdateTags = string[] | null;

export type PostUpdateStatus = PostStatus | null;

/**
 * Schema for updating a post (all fields optional).
 */
export interface PostUpdate {
	title?: PostUpdateTitle;
	content?: PostUpdateContent;
	tags?: PostUpdateTags;
	status?: PostUpdateStatus;
}

/**
 * JWT token response schema.
 */
export interface Token {
	access_token: string;
	token_type: string;
}

/**
 * Schema for creating a new user.
 */
export interface UserCreate {
	email: string;
	/**
	 * Must contain uppercase, lowercase, digit, and special character
	 * @minLength 8
	 * @maxLength 15
	 */
	password: string;
}

/**
 * Schema for user public data (excludes password).
 */
export interface UserPublic {
	email: string;
	id: number;
	email_verified: boolean;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
	loc: ValidationErrorLocItem[];
	msg: string;
	type: string;
}

export type ListPostsParams = {
	/**
	 * Filter by post status
	 */
	status?: PostStatus | null;
	/**
	 * Filter by tag
	 */
	tag?: string | null;
	/**
	 * Number of posts to return
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
	/**
	 * Number of posts to skip
	 * @minimum 0
	 */
	offset?: number;
};
