/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Super Impress API
 * LinkedIn post management tool API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult
} from '@tanstack/react-query';

import type {
	ApiAuthGetAccessTokenPostRequest,
	ApiAuthRefreshTokenPostRequest,
	ApiAuthRevokeOtherSessionsPostRequest,
	ApiAuthRevokeSessionPostRequest,
	ApiAuthRevokeSessionsPostRequest,
	ApiAuthUnlinkAccountPostRequest,
	ChangeEmail200,
	ChangeEmail400,
	ChangeEmail401,
	ChangeEmail403,
	ChangeEmail404,
	ChangeEmail422,
	ChangeEmail429,
	ChangeEmail500,
	ChangeEmailRequest,
	ChangePassword200,
	ChangePassword400,
	ChangePassword401,
	ChangePassword403,
	ChangePassword404,
	ChangePassword429,
	ChangePassword500,
	ChangePasswordRequest,
	DeleteUser200,
	DeleteUser400,
	DeleteUser401,
	DeleteUser403,
	DeleteUser404,
	DeleteUser429,
	DeleteUser500,
	DeleteUserRequest,
	GetApiAuthAccountInfo200,
	GetApiAuthAccountInfo400,
	GetApiAuthAccountInfo401,
	GetApiAuthAccountInfo403,
	GetApiAuthAccountInfo404,
	GetApiAuthAccountInfo429,
	GetApiAuthAccountInfo500,
	GetApiAuthDeleteUserCallback200,
	GetApiAuthDeleteUserCallback400,
	GetApiAuthDeleteUserCallback401,
	GetApiAuthDeleteUserCallback403,
	GetApiAuthDeleteUserCallback404,
	GetApiAuthDeleteUserCallback429,
	GetApiAuthDeleteUserCallback500,
	GetApiAuthDeleteUserCallbackParams,
	GetApiAuthError400,
	GetApiAuthError401,
	GetApiAuthError403,
	GetApiAuthError404,
	GetApiAuthError429,
	GetApiAuthError500,
	GetApiAuthOk200,
	GetApiAuthOk400,
	GetApiAuthOk401,
	GetApiAuthOk403,
	GetApiAuthOk404,
	GetApiAuthOk429,
	GetApiAuthOk500,
	GetApiAuthVerifyEmail200,
	GetApiAuthVerifyEmail400,
	GetApiAuthVerifyEmail401,
	GetApiAuthVerifyEmail403,
	GetApiAuthVerifyEmail404,
	GetApiAuthVerifyEmail429,
	GetApiAuthVerifyEmail500,
	GetApiAuthVerifyEmailParams,
	GetSession200,
	GetSession400,
	GetSession401,
	GetSession403,
	GetSession404,
	GetSession429,
	GetSession500,
	LinkSocialAccount200,
	LinkSocialAccount400,
	LinkSocialAccount401,
	LinkSocialAccount403,
	LinkSocialAccount404,
	LinkSocialAccount429,
	LinkSocialAccount500,
	LinkSocialAccountRequest,
	ListUserAccounts200Item,
	ListUserAccounts400,
	ListUserAccounts401,
	ListUserAccounts403,
	ListUserAccounts404,
	ListUserAccounts429,
	ListUserAccounts500,
	ListUserSessions400,
	ListUserSessions401,
	ListUserSessions403,
	ListUserSessions404,
	ListUserSessions429,
	ListUserSessions500,
	PostApiAuthGetAccessToken200,
	PostApiAuthGetAccessToken401,
	PostApiAuthGetAccessToken403,
	PostApiAuthGetAccessToken404,
	PostApiAuthGetAccessToken429,
	PostApiAuthGetAccessToken500,
	PostApiAuthRefreshToken200,
	PostApiAuthRefreshToken401,
	PostApiAuthRefreshToken403,
	PostApiAuthRefreshToken404,
	PostApiAuthRefreshToken429,
	PostApiAuthRefreshToken500,
	PostApiAuthRevokeOtherSessions200,
	PostApiAuthRevokeOtherSessions400,
	PostApiAuthRevokeOtherSessions401,
	PostApiAuthRevokeOtherSessions403,
	PostApiAuthRevokeOtherSessions404,
	PostApiAuthRevokeOtherSessions429,
	PostApiAuthRevokeOtherSessions500,
	PostApiAuthRevokeSession200,
	PostApiAuthRevokeSession400,
	PostApiAuthRevokeSession401,
	PostApiAuthRevokeSession403,
	PostApiAuthRevokeSession404,
	PostApiAuthRevokeSession429,
	PostApiAuthRevokeSession500,
	PostApiAuthRevokeSessions200,
	PostApiAuthRevokeSessions400,
	PostApiAuthRevokeSessions401,
	PostApiAuthRevokeSessions403,
	PostApiAuthRevokeSessions404,
	PostApiAuthRevokeSessions429,
	PostApiAuthRevokeSessions500,
	PostApiAuthUnlinkAccount200,
	PostApiAuthUnlinkAccount400,
	PostApiAuthUnlinkAccount401,
	PostApiAuthUnlinkAccount403,
	PostApiAuthUnlinkAccount404,
	PostApiAuthUnlinkAccount429,
	PostApiAuthUnlinkAccount500,
	RequestPasswordReset200,
	RequestPasswordReset400,
	RequestPasswordReset401,
	RequestPasswordReset403,
	RequestPasswordReset404,
	RequestPasswordReset429,
	RequestPasswordReset500,
	RequestPasswordResetRequest,
	ResetPassword200,
	ResetPassword400,
	ResetPassword401,
	ResetPassword403,
	ResetPassword404,
	ResetPassword429,
	ResetPassword500,
	ResetPasswordCallback200,
	ResetPasswordCallback400,
	ResetPasswordCallback401,
	ResetPasswordCallback403,
	ResetPasswordCallback404,
	ResetPasswordCallback429,
	ResetPasswordCallback500,
	ResetPasswordCallbackParams,
	ResetPasswordRequest,
	SendVerificationEmail200,
	SendVerificationEmail400,
	SendVerificationEmail401,
	SendVerificationEmail403,
	SendVerificationEmail404,
	SendVerificationEmail429,
	SendVerificationEmail500,
	SendVerificationEmailRequest,
	Session,
	SignInEmail200,
	SignInEmail400,
	SignInEmail401,
	SignInEmail403,
	SignInEmail404,
	SignInEmail429,
	SignInEmail500,
	SignInEmailRequest,
	SignOut200,
	SignOut400,
	SignOut401,
	SignOut403,
	SignOut404,
	SignOut429,
	SignOut500,
	SignOutRequest,
	SignUpWithEmailAndPassword200,
	SignUpWithEmailAndPassword400,
	SignUpWithEmailAndPassword401,
	SignUpWithEmailAndPassword403,
	SignUpWithEmailAndPassword404,
	SignUpWithEmailAndPassword422,
	SignUpWithEmailAndPassword429,
	SignUpWithEmailAndPassword500,
	SignUpWithEmailAndPasswordRequest,
	SocialSignIn200,
	SocialSignIn400,
	SocialSignIn401,
	SocialSignIn403,
	SocialSignIn404,
	SocialSignIn429,
	SocialSignIn500,
	SocialSignInRequest,
	UpdateUser200,
	UpdateUser400,
	UpdateUser401,
	UpdateUser403,
	UpdateUser404,
	UpdateUser429,
	UpdateUser500,
	UpdateUserRequest,
	VerifyPassword200,
	VerifyPassword400,
	VerifyPassword401,
	VerifyPassword403,
	VerifyPassword404,
	VerifyPassword429,
	VerifyPassword500,
	VerifyPasswordRequest
} from '../superimpress.schemas';

import { customInstance } from '.././axios';
import type { ErrorType } from '.././axios';

/**
 * Sign in with a social provider
 */
export const socialSignIn = (socialSignInRequest: SocialSignInRequest, signal?: AbortSignal) => {
	return customInstance<SocialSignIn200>({
		url: `/api/auth/sign-in/social`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: socialSignInRequest,
		signal
	});
};

export const getSocialSignInMutationOptions = <
	TError = ErrorType<
		| SocialSignIn400
		| SocialSignIn401
		| SocialSignIn403
		| SocialSignIn404
		| SocialSignIn429
		| SocialSignIn500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof socialSignIn>>,
		TError,
		{ data: SocialSignInRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof socialSignIn>>,
	TError,
	{ data: SocialSignInRequest },
	TContext
> => {
	const mutationKey = ['socialSignIn'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof socialSignIn>>,
		{ data: SocialSignInRequest }
	> = (props) => {
		const { data } = props ?? {};

		return socialSignIn(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SocialSignInMutationResult = NonNullable<Awaited<ReturnType<typeof socialSignIn>>>;
export type SocialSignInMutationBody = SocialSignInRequest;
export type SocialSignInMutationError = ErrorType<
	| SocialSignIn400
	| SocialSignIn401
	| SocialSignIn403
	| SocialSignIn404
	| SocialSignIn429
	| SocialSignIn500
>;

export const useSocialSignIn = <
	TError = ErrorType<
		| SocialSignIn400
		| SocialSignIn401
		| SocialSignIn403
		| SocialSignIn404
		| SocialSignIn429
		| SocialSignIn500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof socialSignIn>>,
			TError,
			{ data: SocialSignInRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof socialSignIn>>,
	TError,
	{ data: SocialSignInRequest },
	TContext
> => {
	return useMutation(getSocialSignInMutationOptions(options), queryClient);
};
/**
 * Get the current session
 */
export const getSession = (signal?: AbortSignal) => {
	return customInstance<GetSession200>({ url: `/api/auth/get-session`, method: 'GET', signal });
};

export const getGetSessionQueryKey = () => {
	return [`/api/auth/get-session`] as const;
};

export const getGetSessionQueryOptions = <
	TData = Awaited<ReturnType<typeof getSession>>,
	TError = ErrorType<
		GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500
	>
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetSessionQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({ signal }) =>
		getSession(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getSession>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getSession>>>;
export type GetSessionQueryError = ErrorType<
	GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500
>;

export function useGetSession<
	TData = Awaited<ReturnType<typeof getSession>>,
	TError = ErrorType<
		GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500
	>
>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSession>>,
					TError,
					Awaited<ReturnType<typeof getSession>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSession<
	TData = Awaited<ReturnType<typeof getSession>>,
	TError = ErrorType<
		GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSession>>,
					TError,
					Awaited<ReturnType<typeof getSession>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSession<
	TData = Awaited<ReturnType<typeof getSession>>,
	TError = ErrorType<
		GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSession<
	TData = Awaited<ReturnType<typeof getSession>>,
	TError = ErrorType<
		GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetSessionQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Sign out the current user
 */
export const signOut = (signOutRequest: SignOutRequest, signal?: AbortSignal) => {
	return customInstance<SignOut200>({
		url: `/api/auth/sign-out`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: signOutRequest,
		signal
	});
};

export const getSignOutMutationOptions = <
	TError = ErrorType<SignOut400 | SignOut401 | SignOut403 | SignOut404 | SignOut429 | SignOut500>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof signOut>>,
		TError,
		{ data: SignOutRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof signOut>>,
	TError,
	{ data: SignOutRequest },
	TContext
> => {
	const mutationKey = ['signOut'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof signOut>>,
		{ data: SignOutRequest }
	> = (props) => {
		const { data } = props ?? {};

		return signOut(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SignOutMutationResult = NonNullable<Awaited<ReturnType<typeof signOut>>>;
export type SignOutMutationBody = SignOutRequest;
export type SignOutMutationError = ErrorType<
	SignOut400 | SignOut401 | SignOut403 | SignOut404 | SignOut429 | SignOut500
>;

export const useSignOut = <
	TError = ErrorType<SignOut400 | SignOut401 | SignOut403 | SignOut404 | SignOut429 | SignOut500>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof signOut>>,
			TError,
			{ data: SignOutRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof signOut>>,
	TError,
	{ data: SignOutRequest },
	TContext
> => {
	return useMutation(getSignOutMutationOptions(options), queryClient);
};
/**
 * Sign up a user using email and password
 */
export const signUpWithEmailAndPassword = (
	signUpWithEmailAndPasswordRequest: SignUpWithEmailAndPasswordRequest,
	signal?: AbortSignal
) => {
	return customInstance<SignUpWithEmailAndPassword200>({
		url: `/api/auth/sign-up/email`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: signUpWithEmailAndPasswordRequest,
		signal
	});
};

export const getSignUpWithEmailAndPasswordMutationOptions = <
	TError = ErrorType<
		| SignUpWithEmailAndPassword400
		| SignUpWithEmailAndPassword401
		| SignUpWithEmailAndPassword403
		| SignUpWithEmailAndPassword404
		| SignUpWithEmailAndPassword422
		| SignUpWithEmailAndPassword429
		| SignUpWithEmailAndPassword500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof signUpWithEmailAndPassword>>,
		TError,
		{ data: SignUpWithEmailAndPasswordRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof signUpWithEmailAndPassword>>,
	TError,
	{ data: SignUpWithEmailAndPasswordRequest },
	TContext
> => {
	const mutationKey = ['signUpWithEmailAndPassword'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof signUpWithEmailAndPassword>>,
		{ data: SignUpWithEmailAndPasswordRequest }
	> = (props) => {
		const { data } = props ?? {};

		return signUpWithEmailAndPassword(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SignUpWithEmailAndPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof signUpWithEmailAndPassword>>
>;
export type SignUpWithEmailAndPasswordMutationBody = SignUpWithEmailAndPasswordRequest;
export type SignUpWithEmailAndPasswordMutationError = ErrorType<
	| SignUpWithEmailAndPassword400
	| SignUpWithEmailAndPassword401
	| SignUpWithEmailAndPassword403
	| SignUpWithEmailAndPassword404
	| SignUpWithEmailAndPassword422
	| SignUpWithEmailAndPassword429
	| SignUpWithEmailAndPassword500
>;

export const useSignUpWithEmailAndPassword = <
	TError = ErrorType<
		| SignUpWithEmailAndPassword400
		| SignUpWithEmailAndPassword401
		| SignUpWithEmailAndPassword403
		| SignUpWithEmailAndPassword404
		| SignUpWithEmailAndPassword422
		| SignUpWithEmailAndPassword429
		| SignUpWithEmailAndPassword500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof signUpWithEmailAndPassword>>,
			TError,
			{ data: SignUpWithEmailAndPasswordRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof signUpWithEmailAndPassword>>,
	TError,
	{ data: SignUpWithEmailAndPasswordRequest },
	TContext
> => {
	return useMutation(getSignUpWithEmailAndPasswordMutationOptions(options), queryClient);
};
/**
 * Sign in with email and password
 */
export const signInEmail = (signInEmailRequest: SignInEmailRequest, signal?: AbortSignal) => {
	return customInstance<SignInEmail200>({
		url: `/api/auth/sign-in/email`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: signInEmailRequest,
		signal
	});
};

export const getSignInEmailMutationOptions = <
	TError = ErrorType<
		| SignInEmail400
		| SignInEmail401
		| SignInEmail403
		| SignInEmail404
		| SignInEmail429
		| SignInEmail500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof signInEmail>>,
		TError,
		{ data: SignInEmailRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof signInEmail>>,
	TError,
	{ data: SignInEmailRequest },
	TContext
> => {
	const mutationKey = ['signInEmail'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof signInEmail>>,
		{ data: SignInEmailRequest }
	> = (props) => {
		const { data } = props ?? {};

		return signInEmail(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SignInEmailMutationResult = NonNullable<Awaited<ReturnType<typeof signInEmail>>>;
export type SignInEmailMutationBody = SignInEmailRequest;
export type SignInEmailMutationError = ErrorType<
	| SignInEmail400
	| SignInEmail401
	| SignInEmail403
	| SignInEmail404
	| SignInEmail429
	| SignInEmail500
>;

export const useSignInEmail = <
	TError = ErrorType<
		| SignInEmail400
		| SignInEmail401
		| SignInEmail403
		| SignInEmail404
		| SignInEmail429
		| SignInEmail500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof signInEmail>>,
			TError,
			{ data: SignInEmailRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof signInEmail>>,
	TError,
	{ data: SignInEmailRequest },
	TContext
> => {
	return useMutation(getSignInEmailMutationOptions(options), queryClient);
};
/**
 * Reset the password for a user
 */
export const resetPassword = (resetPasswordRequest: ResetPasswordRequest, signal?: AbortSignal) => {
	return customInstance<ResetPassword200>({
		url: `/api/auth/reset-password`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: resetPasswordRequest,
		signal
	});
};

export const getResetPasswordMutationOptions = <
	TError = ErrorType<
		| ResetPassword400
		| ResetPassword401
		| ResetPassword403
		| ResetPassword404
		| ResetPassword429
		| ResetPassword500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof resetPassword>>,
		TError,
		{ data: ResetPasswordRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof resetPassword>>,
	TError,
	{ data: ResetPasswordRequest },
	TContext
> => {
	const mutationKey = ['resetPassword'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof resetPassword>>,
		{ data: ResetPasswordRequest }
	> = (props) => {
		const { data } = props ?? {};

		return resetPassword(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type ResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>;
export type ResetPasswordMutationBody = ResetPasswordRequest;
export type ResetPasswordMutationError = ErrorType<
	| ResetPassword400
	| ResetPassword401
	| ResetPassword403
	| ResetPassword404
	| ResetPassword429
	| ResetPassword500
>;

export const useResetPassword = <
	TError = ErrorType<
		| ResetPassword400
		| ResetPassword401
		| ResetPassword403
		| ResetPassword404
		| ResetPassword429
		| ResetPassword500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof resetPassword>>,
			TError,
			{ data: ResetPasswordRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof resetPassword>>,
	TError,
	{ data: ResetPasswordRequest },
	TContext
> => {
	return useMutation(getResetPasswordMutationOptions(options), queryClient);
};
/**
 * Verify the current user's password
 */
export const verifyPassword = (
	verifyPasswordRequest: VerifyPasswordRequest,
	signal?: AbortSignal
) => {
	return customInstance<VerifyPassword200>({
		url: `/api/auth/verify-password`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: verifyPasswordRequest,
		signal
	});
};

export const getVerifyPasswordMutationOptions = <
	TError = ErrorType<
		| VerifyPassword400
		| VerifyPassword401
		| VerifyPassword403
		| VerifyPassword404
		| VerifyPassword429
		| VerifyPassword500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof verifyPassword>>,
		TError,
		{ data: VerifyPasswordRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof verifyPassword>>,
	TError,
	{ data: VerifyPasswordRequest },
	TContext
> => {
	const mutationKey = ['verifyPassword'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof verifyPassword>>,
		{ data: VerifyPasswordRequest }
	> = (props) => {
		const { data } = props ?? {};

		return verifyPassword(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type VerifyPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof verifyPassword>>>;
export type VerifyPasswordMutationBody = VerifyPasswordRequest;
export type VerifyPasswordMutationError = ErrorType<
	| VerifyPassword400
	| VerifyPassword401
	| VerifyPassword403
	| VerifyPassword404
	| VerifyPassword429
	| VerifyPassword500
>;

export const useVerifyPassword = <
	TError = ErrorType<
		| VerifyPassword400
		| VerifyPassword401
		| VerifyPassword403
		| VerifyPassword404
		| VerifyPassword429
		| VerifyPassword500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof verifyPassword>>,
			TError,
			{ data: VerifyPasswordRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof verifyPassword>>,
	TError,
	{ data: VerifyPasswordRequest },
	TContext
> => {
	return useMutation(getVerifyPasswordMutationOptions(options), queryClient);
};
/**
 * Verify the email of the user
 */
export const getApiAuthVerifyEmail = (
	params: GetApiAuthVerifyEmailParams,
	signal?: AbortSignal
) => {
	return customInstance<GetApiAuthVerifyEmail200>({
		url: `/api/auth/verify-email`,
		method: 'GET',
		params,
		signal
	});
};

export const getGetApiAuthVerifyEmailQueryKey = (params?: GetApiAuthVerifyEmailParams) => {
	return [`/api/auth/verify-email`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuthVerifyEmailQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiAuthVerifyEmail>>,
	TError = ErrorType<
		| GetApiAuthVerifyEmail400
		| GetApiAuthVerifyEmail401
		| GetApiAuthVerifyEmail403
		| GetApiAuthVerifyEmail404
		| GetApiAuthVerifyEmail429
		| GetApiAuthVerifyEmail500
	>
>(
	params: GetApiAuthVerifyEmailParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError, TData>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiAuthVerifyEmailQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>> = ({ signal }) =>
		getApiAuthVerifyEmail(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiAuthVerifyEmail>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthVerifyEmailQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiAuthVerifyEmail>>
>;
export type GetApiAuthVerifyEmailQueryError = ErrorType<
	| GetApiAuthVerifyEmail400
	| GetApiAuthVerifyEmail401
	| GetApiAuthVerifyEmail403
	| GetApiAuthVerifyEmail404
	| GetApiAuthVerifyEmail429
	| GetApiAuthVerifyEmail500
>;

export function useGetApiAuthVerifyEmail<
	TData = Awaited<ReturnType<typeof getApiAuthVerifyEmail>>,
	TError = ErrorType<
		| GetApiAuthVerifyEmail400
		| GetApiAuthVerifyEmail401
		| GetApiAuthVerifyEmail403
		| GetApiAuthVerifyEmail404
		| GetApiAuthVerifyEmail429
		| GetApiAuthVerifyEmail500
	>
>(
	params: GetApiAuthVerifyEmailParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthVerifyEmail>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthVerifyEmail>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthVerifyEmail<
	TData = Awaited<ReturnType<typeof getApiAuthVerifyEmail>>,
	TError = ErrorType<
		| GetApiAuthVerifyEmail400
		| GetApiAuthVerifyEmail401
		| GetApiAuthVerifyEmail403
		| GetApiAuthVerifyEmail404
		| GetApiAuthVerifyEmail429
		| GetApiAuthVerifyEmail500
	>
>(
	params: GetApiAuthVerifyEmailParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthVerifyEmail>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthVerifyEmail>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthVerifyEmail<
	TData = Awaited<ReturnType<typeof getApiAuthVerifyEmail>>,
	TError = ErrorType<
		| GetApiAuthVerifyEmail400
		| GetApiAuthVerifyEmail401
		| GetApiAuthVerifyEmail403
		| GetApiAuthVerifyEmail404
		| GetApiAuthVerifyEmail429
		| GetApiAuthVerifyEmail500
	>
>(
	params: GetApiAuthVerifyEmailParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiAuthVerifyEmail<
	TData = Awaited<ReturnType<typeof getApiAuthVerifyEmail>>,
	TError = ErrorType<
		| GetApiAuthVerifyEmail400
		| GetApiAuthVerifyEmail401
		| GetApiAuthVerifyEmail403
		| GetApiAuthVerifyEmail404
		| GetApiAuthVerifyEmail429
		| GetApiAuthVerifyEmail500
	>
>(
	params: GetApiAuthVerifyEmailParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetApiAuthVerifyEmailQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Send a verification email to the user
 */
export const sendVerificationEmail = (
	sendVerificationEmailRequest: SendVerificationEmailRequest,
	signal?: AbortSignal
) => {
	return customInstance<SendVerificationEmail200>({
		url: `/api/auth/send-verification-email`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: sendVerificationEmailRequest,
		signal
	});
};

export const getSendVerificationEmailMutationOptions = <
	TError = ErrorType<
		| SendVerificationEmail400
		| SendVerificationEmail401
		| SendVerificationEmail403
		| SendVerificationEmail404
		| SendVerificationEmail429
		| SendVerificationEmail500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof sendVerificationEmail>>,
		TError,
		{ data: SendVerificationEmailRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof sendVerificationEmail>>,
	TError,
	{ data: SendVerificationEmailRequest },
	TContext
> => {
	const mutationKey = ['sendVerificationEmail'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof sendVerificationEmail>>,
		{ data: SendVerificationEmailRequest }
	> = (props) => {
		const { data } = props ?? {};

		return sendVerificationEmail(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SendVerificationEmailMutationResult = NonNullable<
	Awaited<ReturnType<typeof sendVerificationEmail>>
>;
export type SendVerificationEmailMutationBody = SendVerificationEmailRequest;
export type SendVerificationEmailMutationError = ErrorType<
	| SendVerificationEmail400
	| SendVerificationEmail401
	| SendVerificationEmail403
	| SendVerificationEmail404
	| SendVerificationEmail429
	| SendVerificationEmail500
>;

export const useSendVerificationEmail = <
	TError = ErrorType<
		| SendVerificationEmail400
		| SendVerificationEmail401
		| SendVerificationEmail403
		| SendVerificationEmail404
		| SendVerificationEmail429
		| SendVerificationEmail500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof sendVerificationEmail>>,
			TError,
			{ data: SendVerificationEmailRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof sendVerificationEmail>>,
	TError,
	{ data: SendVerificationEmailRequest },
	TContext
> => {
	return useMutation(getSendVerificationEmailMutationOptions(options), queryClient);
};
export const changeEmail = (changeEmailRequest: ChangeEmailRequest, signal?: AbortSignal) => {
	return customInstance<ChangeEmail200>({
		url: `/api/auth/change-email`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: changeEmailRequest,
		signal
	});
};

export const getChangeEmailMutationOptions = <
	TError = ErrorType<
		| ChangeEmail400
		| ChangeEmail401
		| ChangeEmail403
		| ChangeEmail404
		| ChangeEmail422
		| ChangeEmail429
		| ChangeEmail500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof changeEmail>>,
		TError,
		{ data: ChangeEmailRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof changeEmail>>,
	TError,
	{ data: ChangeEmailRequest },
	TContext
> => {
	const mutationKey = ['changeEmail'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof changeEmail>>,
		{ data: ChangeEmailRequest }
	> = (props) => {
		const { data } = props ?? {};

		return changeEmail(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type ChangeEmailMutationResult = NonNullable<Awaited<ReturnType<typeof changeEmail>>>;
export type ChangeEmailMutationBody = ChangeEmailRequest;
export type ChangeEmailMutationError = ErrorType<
	| ChangeEmail400
	| ChangeEmail401
	| ChangeEmail403
	| ChangeEmail404
	| ChangeEmail422
	| ChangeEmail429
	| ChangeEmail500
>;

export const useChangeEmail = <
	TError = ErrorType<
		| ChangeEmail400
		| ChangeEmail401
		| ChangeEmail403
		| ChangeEmail404
		| ChangeEmail422
		| ChangeEmail429
		| ChangeEmail500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof changeEmail>>,
			TError,
			{ data: ChangeEmailRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof changeEmail>>,
	TError,
	{ data: ChangeEmailRequest },
	TContext
> => {
	return useMutation(getChangeEmailMutationOptions(options), queryClient);
};
/**
 * Change the password of the user
 */
export const changePassword = (
	changePasswordRequest: ChangePasswordRequest,
	signal?: AbortSignal
) => {
	return customInstance<ChangePassword200>({
		url: `/api/auth/change-password`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: changePasswordRequest,
		signal
	});
};

export const getChangePasswordMutationOptions = <
	TError = ErrorType<
		| ChangePassword400
		| ChangePassword401
		| ChangePassword403
		| ChangePassword404
		| ChangePassword429
		| ChangePassword500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof changePassword>>,
		TError,
		{ data: ChangePasswordRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof changePassword>>,
	TError,
	{ data: ChangePasswordRequest },
	TContext
> => {
	const mutationKey = ['changePassword'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof changePassword>>,
		{ data: ChangePasswordRequest }
	> = (props) => {
		const { data } = props ?? {};

		return changePassword(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>;
export type ChangePasswordMutationBody = ChangePasswordRequest;
export type ChangePasswordMutationError = ErrorType<
	| ChangePassword400
	| ChangePassword401
	| ChangePassword403
	| ChangePassword404
	| ChangePassword429
	| ChangePassword500
>;

export const useChangePassword = <
	TError = ErrorType<
		| ChangePassword400
		| ChangePassword401
		| ChangePassword403
		| ChangePassword404
		| ChangePassword429
		| ChangePassword500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof changePassword>>,
			TError,
			{ data: ChangePasswordRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof changePassword>>,
	TError,
	{ data: ChangePasswordRequest },
	TContext
> => {
	return useMutation(getChangePasswordMutationOptions(options), queryClient);
};
/**
 * Update the current user
 */
export const updateUser = (updateUserRequest: UpdateUserRequest, signal?: AbortSignal) => {
	return customInstance<UpdateUser200>({
		url: `/api/auth/update-user`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: updateUserRequest,
		signal
	});
};

export const getUpdateUserMutationOptions = <
	TError = ErrorType<
		UpdateUser400 | UpdateUser401 | UpdateUser403 | UpdateUser404 | UpdateUser429 | UpdateUser500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateUser>>,
		TError,
		{ data: UpdateUserRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateUser>>,
	TError,
	{ data: UpdateUserRequest },
	TContext
> => {
	const mutationKey = ['updateUser'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateUser>>,
		{ data: UpdateUserRequest }
	> = (props) => {
		const { data } = props ?? {};

		return updateUser(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>;
export type UpdateUserMutationBody = UpdateUserRequest;
export type UpdateUserMutationError = ErrorType<
	UpdateUser400 | UpdateUser401 | UpdateUser403 | UpdateUser404 | UpdateUser429 | UpdateUser500
>;

export const useUpdateUser = <
	TError = ErrorType<
		UpdateUser400 | UpdateUser401 | UpdateUser403 | UpdateUser404 | UpdateUser429 | UpdateUser500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateUser>>,
			TError,
			{ data: UpdateUserRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof updateUser>>,
	TError,
	{ data: UpdateUserRequest },
	TContext
> => {
	return useMutation(getUpdateUserMutationOptions(options), queryClient);
};
/**
 * Delete the user
 */
export const deleteUser = (deleteUserRequest: DeleteUserRequest, signal?: AbortSignal) => {
	return customInstance<DeleteUser200>({
		url: `/api/auth/delete-user`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: deleteUserRequest,
		signal
	});
};

export const getDeleteUserMutationOptions = <
	TError = ErrorType<
		DeleteUser400 | DeleteUser401 | DeleteUser403 | DeleteUser404 | DeleteUser429 | DeleteUser500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteUser>>,
		TError,
		{ data: DeleteUserRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteUser>>,
	TError,
	{ data: DeleteUserRequest },
	TContext
> => {
	const mutationKey = ['deleteUser'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteUser>>,
		{ data: DeleteUserRequest }
	> = (props) => {
		const { data } = props ?? {};

		return deleteUser(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>;
export type DeleteUserMutationBody = DeleteUserRequest;
export type DeleteUserMutationError = ErrorType<
	DeleteUser400 | DeleteUser401 | DeleteUser403 | DeleteUser404 | DeleteUser429 | DeleteUser500
>;

export const useDeleteUser = <
	TError = ErrorType<
		DeleteUser400 | DeleteUser401 | DeleteUser403 | DeleteUser404 | DeleteUser429 | DeleteUser500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteUser>>,
			TError,
			{ data: DeleteUserRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof deleteUser>>,
	TError,
	{ data: DeleteUserRequest },
	TContext
> => {
	return useMutation(getDeleteUserMutationOptions(options), queryClient);
};
/**
 * Send a password reset email to the user
 */
export const requestPasswordReset = (
	requestPasswordResetRequest: RequestPasswordResetRequest,
	signal?: AbortSignal
) => {
	return customInstance<RequestPasswordReset200>({
		url: `/api/auth/request-password-reset`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: requestPasswordResetRequest,
		signal
	});
};

export const getRequestPasswordResetMutationOptions = <
	TError = ErrorType<
		| RequestPasswordReset400
		| RequestPasswordReset401
		| RequestPasswordReset403
		| RequestPasswordReset404
		| RequestPasswordReset429
		| RequestPasswordReset500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof requestPasswordReset>>,
		TError,
		{ data: RequestPasswordResetRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof requestPasswordReset>>,
	TError,
	{ data: RequestPasswordResetRequest },
	TContext
> => {
	const mutationKey = ['requestPasswordReset'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof requestPasswordReset>>,
		{ data: RequestPasswordResetRequest }
	> = (props) => {
		const { data } = props ?? {};

		return requestPasswordReset(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type RequestPasswordResetMutationResult = NonNullable<
	Awaited<ReturnType<typeof requestPasswordReset>>
>;
export type RequestPasswordResetMutationBody = RequestPasswordResetRequest;
export type RequestPasswordResetMutationError = ErrorType<
	| RequestPasswordReset400
	| RequestPasswordReset401
	| RequestPasswordReset403
	| RequestPasswordReset404
	| RequestPasswordReset429
	| RequestPasswordReset500
>;

export const useRequestPasswordReset = <
	TError = ErrorType<
		| RequestPasswordReset400
		| RequestPasswordReset401
		| RequestPasswordReset403
		| RequestPasswordReset404
		| RequestPasswordReset429
		| RequestPasswordReset500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof requestPasswordReset>>,
			TError,
			{ data: RequestPasswordResetRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof requestPasswordReset>>,
	TError,
	{ data: RequestPasswordResetRequest },
	TContext
> => {
	return useMutation(getRequestPasswordResetMutationOptions(options), queryClient);
};
/**
 * Redirects the user to the callback URL with the token
 */
export const resetPasswordCallback = (
	token: string,
	params: ResetPasswordCallbackParams,
	signal?: AbortSignal
) => {
	return customInstance<ResetPasswordCallback200>({
		url: `/api/auth/reset-password/${token}`,
		method: 'GET',
		params,
		signal
	});
};

export const getResetPasswordCallbackQueryKey = (
	token?: string,
	params?: ResetPasswordCallbackParams
) => {
	return [`/api/auth/reset-password/${token}`, ...(params ? [params] : [])] as const;
};

export const getResetPasswordCallbackQueryOptions = <
	TData = Awaited<ReturnType<typeof resetPasswordCallback>>,
	TError = ErrorType<
		| ResetPasswordCallback400
		| ResetPasswordCallback401
		| ResetPasswordCallback403
		| ResetPasswordCallback404
		| ResetPasswordCallback429
		| ResetPasswordCallback500
	>
>(
	token: string,
	params: ResetPasswordCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getResetPasswordCallbackQueryKey(token, params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof resetPasswordCallback>>> = ({ signal }) =>
		resetPasswordCallback(token, params, signal);

	return { queryKey, queryFn, enabled: !!token, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof resetPasswordCallback>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ResetPasswordCallbackQueryResult = NonNullable<
	Awaited<ReturnType<typeof resetPasswordCallback>>
>;
export type ResetPasswordCallbackQueryError = ErrorType<
	| ResetPasswordCallback400
	| ResetPasswordCallback401
	| ResetPasswordCallback403
	| ResetPasswordCallback404
	| ResetPasswordCallback429
	| ResetPasswordCallback500
>;

export function useResetPasswordCallback<
	TData = Awaited<ReturnType<typeof resetPasswordCallback>>,
	TError = ErrorType<
		| ResetPasswordCallback400
		| ResetPasswordCallback401
		| ResetPasswordCallback403
		| ResetPasswordCallback404
		| ResetPasswordCallback429
		| ResetPasswordCallback500
	>
>(
	token: string,
	params: ResetPasswordCallbackParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof resetPasswordCallback>>,
					TError,
					Awaited<ReturnType<typeof resetPasswordCallback>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useResetPasswordCallback<
	TData = Awaited<ReturnType<typeof resetPasswordCallback>>,
	TError = ErrorType<
		| ResetPasswordCallback400
		| ResetPasswordCallback401
		| ResetPasswordCallback403
		| ResetPasswordCallback404
		| ResetPasswordCallback429
		| ResetPasswordCallback500
	>
>(
	token: string,
	params: ResetPasswordCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof resetPasswordCallback>>,
					TError,
					Awaited<ReturnType<typeof resetPasswordCallback>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useResetPasswordCallback<
	TData = Awaited<ReturnType<typeof resetPasswordCallback>>,
	TError = ErrorType<
		| ResetPasswordCallback400
		| ResetPasswordCallback401
		| ResetPasswordCallback403
		| ResetPasswordCallback404
		| ResetPasswordCallback429
		| ResetPasswordCallback500
	>
>(
	token: string,
	params: ResetPasswordCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useResetPasswordCallback<
	TData = Awaited<ReturnType<typeof resetPasswordCallback>>,
	TError = ErrorType<
		| ResetPasswordCallback400
		| ResetPasswordCallback401
		| ResetPasswordCallback403
		| ResetPasswordCallback404
		| ResetPasswordCallback429
		| ResetPasswordCallback500
	>
>(
	token: string,
	params: ResetPasswordCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getResetPasswordCallbackQueryOptions(token, params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * List all active sessions for the user
 */
export const listUserSessions = (signal?: AbortSignal) => {
	return customInstance<Session[]>({ url: `/api/auth/list-sessions`, method: 'GET', signal });
};

export const getListUserSessionsQueryKey = () => {
	return [`/api/auth/list-sessions`] as const;
};

export const getListUserSessionsQueryOptions = <
	TData = Awaited<ReturnType<typeof listUserSessions>>,
	TError = ErrorType<
		| ListUserSessions400
		| ListUserSessions401
		| ListUserSessions403
		| ListUserSessions404
		| ListUserSessions429
		| ListUserSessions500
	>
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserSessions>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListUserSessionsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listUserSessions>>> = ({ signal }) =>
		listUserSessions(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listUserSessions>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListUserSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listUserSessions>>>;
export type ListUserSessionsQueryError = ErrorType<
	| ListUserSessions400
	| ListUserSessions401
	| ListUserSessions403
	| ListUserSessions404
	| ListUserSessions429
	| ListUserSessions500
>;

export function useListUserSessions<
	TData = Awaited<ReturnType<typeof listUserSessions>>,
	TError = ErrorType<
		| ListUserSessions400
		| ListUserSessions401
		| ListUserSessions403
		| ListUserSessions404
		| ListUserSessions429
		| ListUserSessions500
	>
>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserSessions>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listUserSessions>>,
					TError,
					Awaited<ReturnType<typeof listUserSessions>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListUserSessions<
	TData = Awaited<ReturnType<typeof listUserSessions>>,
	TError = ErrorType<
		| ListUserSessions400
		| ListUserSessions401
		| ListUserSessions403
		| ListUserSessions404
		| ListUserSessions429
		| ListUserSessions500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserSessions>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listUserSessions>>,
					TError,
					Awaited<ReturnType<typeof listUserSessions>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListUserSessions<
	TData = Awaited<ReturnType<typeof listUserSessions>>,
	TError = ErrorType<
		| ListUserSessions400
		| ListUserSessions401
		| ListUserSessions403
		| ListUserSessions404
		| ListUserSessions429
		| ListUserSessions500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserSessions>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListUserSessions<
	TData = Awaited<ReturnType<typeof listUserSessions>>,
	TError = ErrorType<
		| ListUserSessions400
		| ListUserSessions401
		| ListUserSessions403
		| ListUserSessions404
		| ListUserSessions429
		| ListUserSessions500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserSessions>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getListUserSessionsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Revoke a single session
 */
export const postApiAuthRevokeSession = (
	apiAuthRevokeSessionPostRequest: ApiAuthRevokeSessionPostRequest,
	signal?: AbortSignal
) => {
	return customInstance<PostApiAuthRevokeSession200>({
		url: `/api/auth/revoke-session`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: apiAuthRevokeSessionPostRequest,
		signal
	});
};

export const getPostApiAuthRevokeSessionMutationOptions = <
	TError = ErrorType<
		| PostApiAuthRevokeSession400
		| PostApiAuthRevokeSession401
		| PostApiAuthRevokeSession403
		| PostApiAuthRevokeSession404
		| PostApiAuthRevokeSession429
		| PostApiAuthRevokeSession500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiAuthRevokeSession>>,
		TError,
		{ data: ApiAuthRevokeSessionPostRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiAuthRevokeSession>>,
	TError,
	{ data: ApiAuthRevokeSessionPostRequest },
	TContext
> => {
	const mutationKey = ['postApiAuthRevokeSession'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiAuthRevokeSession>>,
		{ data: ApiAuthRevokeSessionPostRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postApiAuthRevokeSession(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiAuthRevokeSessionMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiAuthRevokeSession>>
>;
export type PostApiAuthRevokeSessionMutationBody = ApiAuthRevokeSessionPostRequest;
export type PostApiAuthRevokeSessionMutationError = ErrorType<
	| PostApiAuthRevokeSession400
	| PostApiAuthRevokeSession401
	| PostApiAuthRevokeSession403
	| PostApiAuthRevokeSession404
	| PostApiAuthRevokeSession429
	| PostApiAuthRevokeSession500
>;

export const usePostApiAuthRevokeSession = <
	TError = ErrorType<
		| PostApiAuthRevokeSession400
		| PostApiAuthRevokeSession401
		| PostApiAuthRevokeSession403
		| PostApiAuthRevokeSession404
		| PostApiAuthRevokeSession429
		| PostApiAuthRevokeSession500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiAuthRevokeSession>>,
			TError,
			{ data: ApiAuthRevokeSessionPostRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof postApiAuthRevokeSession>>,
	TError,
	{ data: ApiAuthRevokeSessionPostRequest },
	TContext
> => {
	return useMutation(getPostApiAuthRevokeSessionMutationOptions(options), queryClient);
};
/**
 * Revoke all sessions for the user
 */
export const postApiAuthRevokeSessions = (
	apiAuthRevokeSessionsPostRequest: ApiAuthRevokeSessionsPostRequest,
	signal?: AbortSignal
) => {
	return customInstance<PostApiAuthRevokeSessions200>({
		url: `/api/auth/revoke-sessions`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: apiAuthRevokeSessionsPostRequest,
		signal
	});
};

export const getPostApiAuthRevokeSessionsMutationOptions = <
	TError = ErrorType<
		| PostApiAuthRevokeSessions400
		| PostApiAuthRevokeSessions401
		| PostApiAuthRevokeSessions403
		| PostApiAuthRevokeSessions404
		| PostApiAuthRevokeSessions429
		| PostApiAuthRevokeSessions500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiAuthRevokeSessions>>,
		TError,
		{ data: ApiAuthRevokeSessionsPostRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiAuthRevokeSessions>>,
	TError,
	{ data: ApiAuthRevokeSessionsPostRequest },
	TContext
> => {
	const mutationKey = ['postApiAuthRevokeSessions'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiAuthRevokeSessions>>,
		{ data: ApiAuthRevokeSessionsPostRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postApiAuthRevokeSessions(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiAuthRevokeSessionsMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiAuthRevokeSessions>>
>;
export type PostApiAuthRevokeSessionsMutationBody = ApiAuthRevokeSessionsPostRequest;
export type PostApiAuthRevokeSessionsMutationError = ErrorType<
	| PostApiAuthRevokeSessions400
	| PostApiAuthRevokeSessions401
	| PostApiAuthRevokeSessions403
	| PostApiAuthRevokeSessions404
	| PostApiAuthRevokeSessions429
	| PostApiAuthRevokeSessions500
>;

export const usePostApiAuthRevokeSessions = <
	TError = ErrorType<
		| PostApiAuthRevokeSessions400
		| PostApiAuthRevokeSessions401
		| PostApiAuthRevokeSessions403
		| PostApiAuthRevokeSessions404
		| PostApiAuthRevokeSessions429
		| PostApiAuthRevokeSessions500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiAuthRevokeSessions>>,
			TError,
			{ data: ApiAuthRevokeSessionsPostRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof postApiAuthRevokeSessions>>,
	TError,
	{ data: ApiAuthRevokeSessionsPostRequest },
	TContext
> => {
	return useMutation(getPostApiAuthRevokeSessionsMutationOptions(options), queryClient);
};
/**
 * Revoke all other sessions for the user except the current one
 */
export const postApiAuthRevokeOtherSessions = (
	apiAuthRevokeOtherSessionsPostRequest: ApiAuthRevokeOtherSessionsPostRequest,
	signal?: AbortSignal
) => {
	return customInstance<PostApiAuthRevokeOtherSessions200>({
		url: `/api/auth/revoke-other-sessions`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: apiAuthRevokeOtherSessionsPostRequest,
		signal
	});
};

export const getPostApiAuthRevokeOtherSessionsMutationOptions = <
	TError = ErrorType<
		| PostApiAuthRevokeOtherSessions400
		| PostApiAuthRevokeOtherSessions401
		| PostApiAuthRevokeOtherSessions403
		| PostApiAuthRevokeOtherSessions404
		| PostApiAuthRevokeOtherSessions429
		| PostApiAuthRevokeOtherSessions500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>,
		TError,
		{ data: ApiAuthRevokeOtherSessionsPostRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>,
	TError,
	{ data: ApiAuthRevokeOtherSessionsPostRequest },
	TContext
> => {
	const mutationKey = ['postApiAuthRevokeOtherSessions'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>,
		{ data: ApiAuthRevokeOtherSessionsPostRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postApiAuthRevokeOtherSessions(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiAuthRevokeOtherSessionsMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>
>;
export type PostApiAuthRevokeOtherSessionsMutationBody = ApiAuthRevokeOtherSessionsPostRequest;
export type PostApiAuthRevokeOtherSessionsMutationError = ErrorType<
	| PostApiAuthRevokeOtherSessions400
	| PostApiAuthRevokeOtherSessions401
	| PostApiAuthRevokeOtherSessions403
	| PostApiAuthRevokeOtherSessions404
	| PostApiAuthRevokeOtherSessions429
	| PostApiAuthRevokeOtherSessions500
>;

export const usePostApiAuthRevokeOtherSessions = <
	TError = ErrorType<
		| PostApiAuthRevokeOtherSessions400
		| PostApiAuthRevokeOtherSessions401
		| PostApiAuthRevokeOtherSessions403
		| PostApiAuthRevokeOtherSessions404
		| PostApiAuthRevokeOtherSessions429
		| PostApiAuthRevokeOtherSessions500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>,
			TError,
			{ data: ApiAuthRevokeOtherSessionsPostRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>,
	TError,
	{ data: ApiAuthRevokeOtherSessionsPostRequest },
	TContext
> => {
	return useMutation(getPostApiAuthRevokeOtherSessionsMutationOptions(options), queryClient);
};
/**
 * Link a social account to the user
 */
export const linkSocialAccount = (
	linkSocialAccountRequest: LinkSocialAccountRequest,
	signal?: AbortSignal
) => {
	return customInstance<LinkSocialAccount200>({
		url: `/api/auth/link-social`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: linkSocialAccountRequest,
		signal
	});
};

export const getLinkSocialAccountMutationOptions = <
	TError = ErrorType<
		| LinkSocialAccount400
		| LinkSocialAccount401
		| LinkSocialAccount403
		| LinkSocialAccount404
		| LinkSocialAccount429
		| LinkSocialAccount500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof linkSocialAccount>>,
		TError,
		{ data: LinkSocialAccountRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof linkSocialAccount>>,
	TError,
	{ data: LinkSocialAccountRequest },
	TContext
> => {
	const mutationKey = ['linkSocialAccount'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof linkSocialAccount>>,
		{ data: LinkSocialAccountRequest }
	> = (props) => {
		const { data } = props ?? {};

		return linkSocialAccount(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type LinkSocialAccountMutationResult = NonNullable<
	Awaited<ReturnType<typeof linkSocialAccount>>
>;
export type LinkSocialAccountMutationBody = LinkSocialAccountRequest;
export type LinkSocialAccountMutationError = ErrorType<
	| LinkSocialAccount400
	| LinkSocialAccount401
	| LinkSocialAccount403
	| LinkSocialAccount404
	| LinkSocialAccount429
	| LinkSocialAccount500
>;

export const useLinkSocialAccount = <
	TError = ErrorType<
		| LinkSocialAccount400
		| LinkSocialAccount401
		| LinkSocialAccount403
		| LinkSocialAccount404
		| LinkSocialAccount429
		| LinkSocialAccount500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof linkSocialAccount>>,
			TError,
			{ data: LinkSocialAccountRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof linkSocialAccount>>,
	TError,
	{ data: LinkSocialAccountRequest },
	TContext
> => {
	return useMutation(getLinkSocialAccountMutationOptions(options), queryClient);
};
/**
 * List all accounts linked to the user
 */
export const listUserAccounts = (signal?: AbortSignal) => {
	return customInstance<ListUserAccounts200Item[]>({
		url: `/api/auth/list-accounts`,
		method: 'GET',
		signal
	});
};

export const getListUserAccountsQueryKey = () => {
	return [`/api/auth/list-accounts`] as const;
};

export const getListUserAccountsQueryOptions = <
	TData = Awaited<ReturnType<typeof listUserAccounts>>,
	TError = ErrorType<
		| ListUserAccounts400
		| ListUserAccounts401
		| ListUserAccounts403
		| ListUserAccounts404
		| ListUserAccounts429
		| ListUserAccounts500
	>
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListUserAccountsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listUserAccounts>>> = ({ signal }) =>
		listUserAccounts(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listUserAccounts>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListUserAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof listUserAccounts>>>;
export type ListUserAccountsQueryError = ErrorType<
	| ListUserAccounts400
	| ListUserAccounts401
	| ListUserAccounts403
	| ListUserAccounts404
	| ListUserAccounts429
	| ListUserAccounts500
>;

export function useListUserAccounts<
	TData = Awaited<ReturnType<typeof listUserAccounts>>,
	TError = ErrorType<
		| ListUserAccounts400
		| ListUserAccounts401
		| ListUserAccounts403
		| ListUserAccounts404
		| ListUserAccounts429
		| ListUserAccounts500
	>
>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listUserAccounts>>,
					TError,
					Awaited<ReturnType<typeof listUserAccounts>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListUserAccounts<
	TData = Awaited<ReturnType<typeof listUserAccounts>>,
	TError = ErrorType<
		| ListUserAccounts400
		| ListUserAccounts401
		| ListUserAccounts403
		| ListUserAccounts404
		| ListUserAccounts429
		| ListUserAccounts500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listUserAccounts>>,
					TError,
					Awaited<ReturnType<typeof listUserAccounts>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListUserAccounts<
	TData = Awaited<ReturnType<typeof listUserAccounts>>,
	TError = ErrorType<
		| ListUserAccounts400
		| ListUserAccounts401
		| ListUserAccounts403
		| ListUserAccounts404
		| ListUserAccounts429
		| ListUserAccounts500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListUserAccounts<
	TData = Awaited<ReturnType<typeof listUserAccounts>>,
	TError = ErrorType<
		| ListUserAccounts400
		| ListUserAccounts401
		| ListUserAccounts403
		| ListUserAccounts404
		| ListUserAccounts429
		| ListUserAccounts500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getListUserAccountsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Callback to complete user deletion with verification token
 */
export const getApiAuthDeleteUserCallback = (
	params?: GetApiAuthDeleteUserCallbackParams,
	signal?: AbortSignal
) => {
	return customInstance<GetApiAuthDeleteUserCallback200>({
		url: `/api/auth/delete-user/callback`,
		method: 'GET',
		params,
		signal
	});
};

export const getGetApiAuthDeleteUserCallbackQueryKey = (
	params?: GetApiAuthDeleteUserCallbackParams
) => {
	return [`/api/auth/delete-user/callback`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuthDeleteUserCallbackQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>,
	TError = ErrorType<
		| GetApiAuthDeleteUserCallback400
		| GetApiAuthDeleteUserCallback401
		| GetApiAuthDeleteUserCallback403
		| GetApiAuthDeleteUserCallback404
		| GetApiAuthDeleteUserCallback429
		| GetApiAuthDeleteUserCallback500
	>
>(
	params?: GetApiAuthDeleteUserCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError, TData>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiAuthDeleteUserCallbackQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>> = ({
		signal
	}) => getApiAuthDeleteUserCallback(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthDeleteUserCallbackQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>
>;
export type GetApiAuthDeleteUserCallbackQueryError = ErrorType<
	| GetApiAuthDeleteUserCallback400
	| GetApiAuthDeleteUserCallback401
	| GetApiAuthDeleteUserCallback403
	| GetApiAuthDeleteUserCallback404
	| GetApiAuthDeleteUserCallback429
	| GetApiAuthDeleteUserCallback500
>;

export function useGetApiAuthDeleteUserCallback<
	TData = Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>,
	TError = ErrorType<
		| GetApiAuthDeleteUserCallback400
		| GetApiAuthDeleteUserCallback401
		| GetApiAuthDeleteUserCallback403
		| GetApiAuthDeleteUserCallback404
		| GetApiAuthDeleteUserCallback429
		| GetApiAuthDeleteUserCallback500
	>
>(
	params: undefined | GetApiAuthDeleteUserCallbackParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthDeleteUserCallback<
	TData = Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>,
	TError = ErrorType<
		| GetApiAuthDeleteUserCallback400
		| GetApiAuthDeleteUserCallback401
		| GetApiAuthDeleteUserCallback403
		| GetApiAuthDeleteUserCallback404
		| GetApiAuthDeleteUserCallback429
		| GetApiAuthDeleteUserCallback500
	>
>(
	params?: GetApiAuthDeleteUserCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthDeleteUserCallback<
	TData = Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>,
	TError = ErrorType<
		| GetApiAuthDeleteUserCallback400
		| GetApiAuthDeleteUserCallback401
		| GetApiAuthDeleteUserCallback403
		| GetApiAuthDeleteUserCallback404
		| GetApiAuthDeleteUserCallback429
		| GetApiAuthDeleteUserCallback500
	>
>(
	params?: GetApiAuthDeleteUserCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiAuthDeleteUserCallback<
	TData = Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>,
	TError = ErrorType<
		| GetApiAuthDeleteUserCallback400
		| GetApiAuthDeleteUserCallback401
		| GetApiAuthDeleteUserCallback403
		| GetApiAuthDeleteUserCallback404
		| GetApiAuthDeleteUserCallback429
		| GetApiAuthDeleteUserCallback500
	>
>(
	params?: GetApiAuthDeleteUserCallbackParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetApiAuthDeleteUserCallbackQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Unlink an account
 */
export const postApiAuthUnlinkAccount = (
	apiAuthUnlinkAccountPostRequest: ApiAuthUnlinkAccountPostRequest,
	signal?: AbortSignal
) => {
	return customInstance<PostApiAuthUnlinkAccount200>({
		url: `/api/auth/unlink-account`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: apiAuthUnlinkAccountPostRequest,
		signal
	});
};

export const getPostApiAuthUnlinkAccountMutationOptions = <
	TError = ErrorType<
		| PostApiAuthUnlinkAccount400
		| PostApiAuthUnlinkAccount401
		| PostApiAuthUnlinkAccount403
		| PostApiAuthUnlinkAccount404
		| PostApiAuthUnlinkAccount429
		| PostApiAuthUnlinkAccount500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>,
		TError,
		{ data: ApiAuthUnlinkAccountPostRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>,
	TError,
	{ data: ApiAuthUnlinkAccountPostRequest },
	TContext
> => {
	const mutationKey = ['postApiAuthUnlinkAccount'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>,
		{ data: ApiAuthUnlinkAccountPostRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postApiAuthUnlinkAccount(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiAuthUnlinkAccountMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>
>;
export type PostApiAuthUnlinkAccountMutationBody = ApiAuthUnlinkAccountPostRequest;
export type PostApiAuthUnlinkAccountMutationError = ErrorType<
	| PostApiAuthUnlinkAccount400
	| PostApiAuthUnlinkAccount401
	| PostApiAuthUnlinkAccount403
	| PostApiAuthUnlinkAccount404
	| PostApiAuthUnlinkAccount429
	| PostApiAuthUnlinkAccount500
>;

export const usePostApiAuthUnlinkAccount = <
	TError = ErrorType<
		| PostApiAuthUnlinkAccount400
		| PostApiAuthUnlinkAccount401
		| PostApiAuthUnlinkAccount403
		| PostApiAuthUnlinkAccount404
		| PostApiAuthUnlinkAccount429
		| PostApiAuthUnlinkAccount500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>,
			TError,
			{ data: ApiAuthUnlinkAccountPostRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>,
	TError,
	{ data: ApiAuthUnlinkAccountPostRequest },
	TContext
> => {
	return useMutation(getPostApiAuthUnlinkAccountMutationOptions(options), queryClient);
};
/**
 * Refresh the access token using a refresh token
 */
export const postApiAuthRefreshToken = (
	apiAuthRefreshTokenPostRequest: ApiAuthRefreshTokenPostRequest,
	signal?: AbortSignal
) => {
	return customInstance<PostApiAuthRefreshToken200>({
		url: `/api/auth/refresh-token`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: apiAuthRefreshTokenPostRequest,
		signal
	});
};

export const getPostApiAuthRefreshTokenMutationOptions = <
	TError = ErrorType<
		| void
		| PostApiAuthRefreshToken401
		| PostApiAuthRefreshToken403
		| PostApiAuthRefreshToken404
		| PostApiAuthRefreshToken429
		| PostApiAuthRefreshToken500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiAuthRefreshToken>>,
		TError,
		{ data: ApiAuthRefreshTokenPostRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiAuthRefreshToken>>,
	TError,
	{ data: ApiAuthRefreshTokenPostRequest },
	TContext
> => {
	const mutationKey = ['postApiAuthRefreshToken'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiAuthRefreshToken>>,
		{ data: ApiAuthRefreshTokenPostRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postApiAuthRefreshToken(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiAuthRefreshTokenMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiAuthRefreshToken>>
>;
export type PostApiAuthRefreshTokenMutationBody = ApiAuthRefreshTokenPostRequest;
export type PostApiAuthRefreshTokenMutationError = ErrorType<
	| void
	| PostApiAuthRefreshToken401
	| PostApiAuthRefreshToken403
	| PostApiAuthRefreshToken404
	| PostApiAuthRefreshToken429
	| PostApiAuthRefreshToken500
>;

export const usePostApiAuthRefreshToken = <
	TError = ErrorType<
		| void
		| PostApiAuthRefreshToken401
		| PostApiAuthRefreshToken403
		| PostApiAuthRefreshToken404
		| PostApiAuthRefreshToken429
		| PostApiAuthRefreshToken500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiAuthRefreshToken>>,
			TError,
			{ data: ApiAuthRefreshTokenPostRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof postApiAuthRefreshToken>>,
	TError,
	{ data: ApiAuthRefreshTokenPostRequest },
	TContext
> => {
	return useMutation(getPostApiAuthRefreshTokenMutationOptions(options), queryClient);
};
/**
 * Get a valid access token, doing a refresh if needed
 */
export const postApiAuthGetAccessToken = (
	apiAuthGetAccessTokenPostRequest: ApiAuthGetAccessTokenPostRequest,
	signal?: AbortSignal
) => {
	return customInstance<PostApiAuthGetAccessToken200>({
		url: `/api/auth/get-access-token`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: apiAuthGetAccessTokenPostRequest,
		signal
	});
};

export const getPostApiAuthGetAccessTokenMutationOptions = <
	TError = ErrorType<
		| void
		| PostApiAuthGetAccessToken401
		| PostApiAuthGetAccessToken403
		| PostApiAuthGetAccessToken404
		| PostApiAuthGetAccessToken429
		| PostApiAuthGetAccessToken500
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiAuthGetAccessToken>>,
		TError,
		{ data: ApiAuthGetAccessTokenPostRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiAuthGetAccessToken>>,
	TError,
	{ data: ApiAuthGetAccessTokenPostRequest },
	TContext
> => {
	const mutationKey = ['postApiAuthGetAccessToken'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiAuthGetAccessToken>>,
		{ data: ApiAuthGetAccessTokenPostRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postApiAuthGetAccessToken(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiAuthGetAccessTokenMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiAuthGetAccessToken>>
>;
export type PostApiAuthGetAccessTokenMutationBody = ApiAuthGetAccessTokenPostRequest;
export type PostApiAuthGetAccessTokenMutationError = ErrorType<
	| void
	| PostApiAuthGetAccessToken401
	| PostApiAuthGetAccessToken403
	| PostApiAuthGetAccessToken404
	| PostApiAuthGetAccessToken429
	| PostApiAuthGetAccessToken500
>;

export const usePostApiAuthGetAccessToken = <
	TError = ErrorType<
		| void
		| PostApiAuthGetAccessToken401
		| PostApiAuthGetAccessToken403
		| PostApiAuthGetAccessToken404
		| PostApiAuthGetAccessToken429
		| PostApiAuthGetAccessToken500
	>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiAuthGetAccessToken>>,
			TError,
			{ data: ApiAuthGetAccessTokenPostRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof postApiAuthGetAccessToken>>,
	TError,
	{ data: ApiAuthGetAccessTokenPostRequest },
	TContext
> => {
	return useMutation(getPostApiAuthGetAccessTokenMutationOptions(options), queryClient);
};
/**
 * Get the account info provided by the provider
 */
export const getApiAuthAccountInfo = (signal?: AbortSignal) => {
	return customInstance<GetApiAuthAccountInfo200>({
		url: `/api/auth/account-info`,
		method: 'GET',
		signal
	});
};

export const getGetApiAuthAccountInfoQueryKey = () => {
	return [`/api/auth/account-info`] as const;
};

export const getGetApiAuthAccountInfoQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiAuthAccountInfo>>,
	TError = ErrorType<
		| GetApiAuthAccountInfo400
		| GetApiAuthAccountInfo401
		| GetApiAuthAccountInfo403
		| GetApiAuthAccountInfo404
		| GetApiAuthAccountInfo429
		| GetApiAuthAccountInfo500
	>
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiAuthAccountInfoQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthAccountInfo>>> = ({ signal }) =>
		getApiAuthAccountInfo(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiAuthAccountInfo>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthAccountInfoQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiAuthAccountInfo>>
>;
export type GetApiAuthAccountInfoQueryError = ErrorType<
	| GetApiAuthAccountInfo400
	| GetApiAuthAccountInfo401
	| GetApiAuthAccountInfo403
	| GetApiAuthAccountInfo404
	| GetApiAuthAccountInfo429
	| GetApiAuthAccountInfo500
>;

export function useGetApiAuthAccountInfo<
	TData = Awaited<ReturnType<typeof getApiAuthAccountInfo>>,
	TError = ErrorType<
		| GetApiAuthAccountInfo400
		| GetApiAuthAccountInfo401
		| GetApiAuthAccountInfo403
		| GetApiAuthAccountInfo404
		| GetApiAuthAccountInfo429
		| GetApiAuthAccountInfo500
	>
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthAccountInfo>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthAccountInfo>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthAccountInfo<
	TData = Awaited<ReturnType<typeof getApiAuthAccountInfo>>,
	TError = ErrorType<
		| GetApiAuthAccountInfo400
		| GetApiAuthAccountInfo401
		| GetApiAuthAccountInfo403
		| GetApiAuthAccountInfo404
		| GetApiAuthAccountInfo429
		| GetApiAuthAccountInfo500
	>
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthAccountInfo>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthAccountInfo>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthAccountInfo<
	TData = Awaited<ReturnType<typeof getApiAuthAccountInfo>>,
	TError = ErrorType<
		| GetApiAuthAccountInfo400
		| GetApiAuthAccountInfo401
		| GetApiAuthAccountInfo403
		| GetApiAuthAccountInfo404
		| GetApiAuthAccountInfo429
		| GetApiAuthAccountInfo500
	>
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiAuthAccountInfo<
	TData = Awaited<ReturnType<typeof getApiAuthAccountInfo>>,
	TError = ErrorType<
		| GetApiAuthAccountInfo400
		| GetApiAuthAccountInfo401
		| GetApiAuthAccountInfo403
		| GetApiAuthAccountInfo404
		| GetApiAuthAccountInfo429
		| GetApiAuthAccountInfo500
	>
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetApiAuthAccountInfoQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Check if the API is working
 */
export const getApiAuthOk = (signal?: AbortSignal) => {
	return customInstance<GetApiAuthOk200>({ url: `/api/auth/ok`, method: 'GET', signal });
};

export const getGetApiAuthOkQueryKey = () => {
	return [`/api/auth/ok`] as const;
};

export const getGetApiAuthOkQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiAuthOk>>,
	TError = ErrorType<
		| GetApiAuthOk400
		| GetApiAuthOk401
		| GetApiAuthOk403
		| GetApiAuthOk404
		| GetApiAuthOk429
		| GetApiAuthOk500
	>
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiAuthOkQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthOk>>> = ({ signal }) =>
		getApiAuthOk(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiAuthOk>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthOkQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthOk>>>;
export type GetApiAuthOkQueryError = ErrorType<
	| GetApiAuthOk400
	| GetApiAuthOk401
	| GetApiAuthOk403
	| GetApiAuthOk404
	| GetApiAuthOk429
	| GetApiAuthOk500
>;

export function useGetApiAuthOk<
	TData = Awaited<ReturnType<typeof getApiAuthOk>>,
	TError = ErrorType<
		| GetApiAuthOk400
		| GetApiAuthOk401
		| GetApiAuthOk403
		| GetApiAuthOk404
		| GetApiAuthOk429
		| GetApiAuthOk500
	>
>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthOk>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthOk>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthOk<
	TData = Awaited<ReturnType<typeof getApiAuthOk>>,
	TError = ErrorType<
		| GetApiAuthOk400
		| GetApiAuthOk401
		| GetApiAuthOk403
		| GetApiAuthOk404
		| GetApiAuthOk429
		| GetApiAuthOk500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthOk>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthOk>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthOk<
	TData = Awaited<ReturnType<typeof getApiAuthOk>>,
	TError = ErrorType<
		| GetApiAuthOk400
		| GetApiAuthOk401
		| GetApiAuthOk403
		| GetApiAuthOk404
		| GetApiAuthOk429
		| GetApiAuthOk500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiAuthOk<
	TData = Awaited<ReturnType<typeof getApiAuthOk>>,
	TError = ErrorType<
		| GetApiAuthOk400
		| GetApiAuthOk401
		| GetApiAuthOk403
		| GetApiAuthOk404
		| GetApiAuthOk429
		| GetApiAuthOk500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetApiAuthOkQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Displays an error page
 */
export const getApiAuthError = (signal?: AbortSignal) => {
	return customInstance<string>({ url: `/api/auth/error`, method: 'GET', signal });
};

export const getGetApiAuthErrorQueryKey = () => {
	return [`/api/auth/error`] as const;
};

export const getGetApiAuthErrorQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiAuthError>>,
	TError = ErrorType<
		| GetApiAuthError400
		| GetApiAuthError401
		| GetApiAuthError403
		| GetApiAuthError404
		| GetApiAuthError429
		| GetApiAuthError500
	>
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthError>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiAuthErrorQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthError>>> = ({ signal }) =>
		getApiAuthError(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiAuthError>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthErrorQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthError>>>;
export type GetApiAuthErrorQueryError = ErrorType<
	| GetApiAuthError400
	| GetApiAuthError401
	| GetApiAuthError403
	| GetApiAuthError404
	| GetApiAuthError429
	| GetApiAuthError500
>;

export function useGetApiAuthError<
	TData = Awaited<ReturnType<typeof getApiAuthError>>,
	TError = ErrorType<
		| GetApiAuthError400
		| GetApiAuthError401
		| GetApiAuthError403
		| GetApiAuthError404
		| GetApiAuthError429
		| GetApiAuthError500
	>
>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthError>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthError>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthError>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthError<
	TData = Awaited<ReturnType<typeof getApiAuthError>>,
	TError = ErrorType<
		| GetApiAuthError400
		| GetApiAuthError401
		| GetApiAuthError403
		| GetApiAuthError404
		| GetApiAuthError429
		| GetApiAuthError500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthError>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiAuthError>>,
					TError,
					Awaited<ReturnType<typeof getApiAuthError>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthError<
	TData = Awaited<ReturnType<typeof getApiAuthError>>,
	TError = ErrorType<
		| GetApiAuthError400
		| GetApiAuthError401
		| GetApiAuthError403
		| GetApiAuthError404
		| GetApiAuthError429
		| GetApiAuthError500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthError>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiAuthError<
	TData = Awaited<ReturnType<typeof getApiAuthError>>,
	TError = ErrorType<
		| GetApiAuthError400
		| GetApiAuthError401
		| GetApiAuthError403
		| GetApiAuthError404
		| GetApiAuthError429
		| GetApiAuthError500
	>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthError>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetApiAuthErrorQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}
