/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * SuperImpress API
 * LinkedIn post management tool API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * Sign in with a social provider
 */
export const SocialSignInBody = zod.object({
  callbackURL: zod
    .string()
    .nullish()
    .describe("Callback URL to redirect to after the user has signed in"),
  newUserCallbackURL: zod.string().nullish(),
  errorCallbackURL: zod
    .string()
    .nullish()
    .describe("Callback URL to redirect to if an error happens"),
  provider: zod.string(),
  disableRedirect: zod
    .boolean()
    .nullish()
    .describe(
      "Disable automatic redirection to the provider. Useful for handling the redirection yourself"
    ),
  idToken: zod
    .object({
      token: zod.string().describe("ID token from the provider"),
      nonce: zod
        .string()
        .nullish()
        .describe("Nonce used to generate the token"),
      accessToken: zod
        .string()
        .nullish()
        .describe("Access token from the provider"),
      refreshToken: zod
        .string()
        .nullish()
        .describe("Refresh token from the provider"),
      expiresAt: zod.number().nullish().describe("Expiry date of the token"),
    })
    .nullish(),
  scopes: zod
    .array(zod.unknown())
    .nullish()
    .describe(
      "Array of scopes to request from the provider. This will override the default scopes passed."
    ),
  requestSignUp: zod
    .boolean()
    .nullish()
    .describe(
      "Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider"
    ),
  loginHint: zod
    .string()
    .nullish()
    .describe("The login hint to use for the authorization code request"),
  additionalData: zod.string().nullish(),
});

export const socialSignInResponseUserEmailVerifiedDefault = false;
export const socialSignInResponseUserCreatedAtDefault = `Generated at runtime`;
export const socialSignInResponseUserUpdatedAtDefault = `Generated at runtime`;

export const SocialSignInResponse = zod
  .object({
    token: zod.string(),
    user: zod.object({
      id: zod.string().optional(),
      name: zod.string(),
      email: zod.string(),
      emailVerified: zod
        .boolean()
        .default(socialSignInResponseUserEmailVerifiedDefault),
      image: zod.string().optional(),
      createdAt: zod.iso.datetime({}),
      updatedAt: zod.iso.datetime({}),
    }),
    url: zod.string().optional(),
    redirect: zod.literal(false),
  })
  .describe("Session response when idToken is provided");

/**
 * Get the current session
 */
export const getSessionResponseSessionCreatedAtDefault = `Generated at runtime`;
export const getSessionResponseUserEmailVerifiedDefault = false;
export const getSessionResponseUserCreatedAtDefault = `Generated at runtime`;
export const getSessionResponseUserUpdatedAtDefault = `Generated at runtime`;

export const GetSessionResponse = zod
  .object({
    session: zod.object({
      id: zod.string().optional(),
      expiresAt: zod.iso.datetime({}),
      token: zod.string(),
      createdAt: zod.iso.datetime({}),
      updatedAt: zod.iso.datetime({}),
      ipAddress: zod.string().optional(),
      userAgent: zod.string().optional(),
      userId: zod.string(),
    }),
    user: zod.object({
      id: zod.string().optional(),
      name: zod.string(),
      email: zod.string(),
      emailVerified: zod
        .boolean()
        .default(getSessionResponseUserEmailVerifiedDefault),
      image: zod.string().optional(),
      createdAt: zod.iso.datetime({}),
      updatedAt: zod.iso.datetime({}),
    }),
  })
  .nullable();

/**
 * Sign out the current user
 */
export const SignOutBody = zod.object({});

export const SignOutResponse = zod.object({
  success: zod.boolean().optional(),
});

/**
 * Sign up a user using email and password
 */
export const SignUpWithEmailAndPasswordBody = zod.object({
  name: zod.string().describe("The name of the user"),
  email: zod.string().describe("The email of the user"),
  password: zod.string().describe("The password of the user"),
  image: zod.string().optional().describe("The profile image URL of the user"),
  callbackURL: zod
    .string()
    .optional()
    .describe("The URL to use for email verification callback"),
  rememberMe: zod
    .boolean()
    .optional()
    .describe(
      "If this is false, the session will not be remembered. Default is `true`."
    ),
});

export const SignUpWithEmailAndPasswordResponse = zod.object({
  token: zod
    .string()
    .nullish()
    .describe("Authentication token for the session"),
  user: zod.object({
    id: zod.string().describe("The unique identifier of the user"),
    email: zod.email().describe("The email address of the user"),
    name: zod.string().describe("The name of the user"),
    image: zod.url().nullish().describe("The profile image URL of the user"),
    emailVerified: zod
      .boolean()
      .describe("Whether the email has been verified"),
    createdAt: zod.iso.datetime({}).describe("When the user was created"),
    updatedAt: zod.iso.datetime({}).describe("When the user was last updated"),
  }),
});

/**
 * Sign in with email and password
 */
export const signInEmailBodyRememberMeDefault = true;

export const SignInEmailBody = zod.object({
  email: zod.string().describe("Email of the user"),
  password: zod.string().describe("Password of the user"),
  callbackURL: zod
    .string()
    .nullish()
    .describe("Callback URL to use as a redirect for email verification"),
  rememberMe: zod
    .boolean()
    .default(signInEmailBodyRememberMeDefault)
    .describe(
      "If this is false, the session will not be remembered. Default is `true`."
    ),
});

export const signInEmailResponseUserEmailVerifiedDefault = false;
export const signInEmailResponseUserCreatedAtDefault = `Generated at runtime`;
export const signInEmailResponseUserUpdatedAtDefault = `Generated at runtime`;

export const SignInEmailResponse = zod
  .object({
    redirect: zod.literal(false),
    token: zod.string().describe("Session token"),
    url: zod.string().nullish(),
    user: zod.object({
      id: zod.string().optional(),
      name: zod.string(),
      email: zod.string(),
      emailVerified: zod
        .boolean()
        .default(signInEmailResponseUserEmailVerifiedDefault),
      image: zod.string().optional(),
      createdAt: zod.iso.datetime({}),
      updatedAt: zod.iso.datetime({}),
    }),
  })
  .describe("Session response when idToken is provided");

/**
 * Reset the password for a user
 */
export const ResetPasswordBody = zod.object({
  newPassword: zod.string().describe("The new password to set"),
  token: zod.string().nullish().describe("The token to reset the password"),
});

export const ResetPasswordResponse = zod.object({
  status: zod.boolean().optional(),
});

/**
 * Verify the current user's password
 */
export const VerifyPasswordBody = zod.object({
  password: zod.string().describe("The password to verify"),
});

export const VerifyPasswordResponse = zod.object({
  status: zod.boolean().optional(),
});

/**
 * Verify the email of the user
 */
export const GetApiAuthVerifyEmailQueryParams = zod.object({
  token: zod.string().describe("The token to verify the email"),
  callbackURL: zod
    .string()
    .optional()
    .describe("The URL to redirect to after email verification"),
});

export const getApiAuthVerifyEmailResponseUserEmailVerifiedDefault = false;
export const getApiAuthVerifyEmailResponseUserCreatedAtDefault = `Generated at runtime`;
export const getApiAuthVerifyEmailResponseUserUpdatedAtDefault = `Generated at runtime`;

export const GetApiAuthVerifyEmailResponse = zod.object({
  user: zod.object({
    id: zod.string().optional(),
    name: zod.string(),
    email: zod.string(),
    emailVerified: zod
      .boolean()
      .default(getApiAuthVerifyEmailResponseUserEmailVerifiedDefault),
    image: zod.string().optional(),
    createdAt: zod.iso.datetime({}),
    updatedAt: zod.iso.datetime({}),
  }),
  status: zod
    .boolean()
    .describe("Indicates if the email was verified successfully"),
});

/**
 * Send a verification email to the user
 */
export const SendVerificationEmailBody = zod.object({
  email: zod.string().describe("The email to send the verification email to"),
  callbackURL: zod
    .string()
    .nullish()
    .describe("The URL to use for email verification callback"),
});

export const SendVerificationEmailResponse = zod.object({
  status: zod
    .boolean()
    .optional()
    .describe("Indicates if the email was sent successfully"),
});

export const ChangeEmailBody = zod.object({
  newEmail: zod
    .string()
    .describe("The new email address to set must be a valid email address"),
  callbackURL: zod
    .string()
    .nullish()
    .describe("The URL to redirect to after email verification"),
});

export const changeEmailResponseUserEmailVerifiedDefault = false;
export const changeEmailResponseUserCreatedAtDefault = `Generated at runtime`;
export const changeEmailResponseUserUpdatedAtDefault = `Generated at runtime`;

export const ChangeEmailResponse = zod.object({
  user: zod
    .object({
      id: zod.string().optional(),
      name: zod.string(),
      email: zod.string(),
      emailVerified: zod
        .boolean()
        .default(changeEmailResponseUserEmailVerifiedDefault),
      image: zod.string().optional(),
      createdAt: zod.iso.datetime({}),
      updatedAt: zod.iso.datetime({}),
    })
    .optional(),
  status: zod.boolean().describe("Indicates if the request was successful"),
  message: zod
    .enum(["Email updated", "Verification email sent"])
    .nullish()
    .describe("Status message of the email change process"),
});

/**
 * Change the password of the user
 */
export const ChangePasswordBody = zod.object({
  newPassword: zod.string().describe("The new password to set"),
  currentPassword: zod.string().describe("The current password is required"),
  revokeOtherSessions: zod
    .boolean()
    .nullish()
    .describe("Must be a boolean value"),
});

export const ChangePasswordResponse = zod.object({
  token: zod
    .string()
    .nullish()
    .describe("New session token if other sessions were revoked"),
  user: zod.object({
    id: zod.string().describe("The unique identifier of the user"),
    email: zod.email().describe("The email address of the user"),
    name: zod.string().describe("The name of the user"),
    image: zod.url().nullish().describe("The profile image URL of the user"),
    emailVerified: zod
      .boolean()
      .describe("Whether the email has been verified"),
    createdAt: zod.iso.datetime({}).describe("When the user was created"),
    updatedAt: zod.iso.datetime({}).describe("When the user was last updated"),
  }),
});

/**
 * Update the current user
 */
export const UpdateUserBody = zod.object({
  name: zod.string().optional().describe("The name of the user"),
  image: zod.string().nullish().describe("The image of the user"),
});

export const updateUserResponseUserEmailVerifiedDefault = false;
export const updateUserResponseUserCreatedAtDefault = `Generated at runtime`;
export const updateUserResponseUserUpdatedAtDefault = `Generated at runtime`;

export const UpdateUserResponse = zod.object({
  user: zod
    .object({
      id: zod.string().optional(),
      name: zod.string(),
      email: zod.string(),
      emailVerified: zod
        .boolean()
        .default(updateUserResponseUserEmailVerifiedDefault),
      image: zod.string().optional(),
      createdAt: zod.iso.datetime({}),
      updatedAt: zod.iso.datetime({}),
    })
    .optional(),
});

/**
 * Delete the user
 */
export const DeleteUserBody = zod.object({
  callbackURL: zod
    .string()
    .optional()
    .describe("The callback URL to redirect to after the user is deleted"),
  password: zod
    .string()
    .optional()
    .describe("The user's password. Required if session is not fresh"),
  token: zod.string().optional().describe("The deletion verification token"),
});

export const DeleteUserResponse = zod.object({
  success: zod.boolean().describe("Indicates if the operation was successful"),
  message: zod
    .enum(["User deleted", "Verification email sent"])
    .describe("Status message of the deletion process"),
});

/**
 * Send a password reset email to the user
 */
export const RequestPasswordResetBody = zod.object({
  email: zod
    .string()
    .describe(
      "The email address of the user to send a password reset email to"
    ),
  redirectTo: zod
    .string()
    .nullish()
    .describe(
      "The URL to redirect the user to reset their password. If the token isn't valid or expired, it'll be redirected with a query parameter `?error=INVALID_TOKEN`. If the token is valid, it'll be redirected with a query parameter `?token=VALID_TOKEN"
    ),
});

export const RequestPasswordResetResponse = zod.object({
  status: zod.boolean().optional(),
  message: zod.string().optional(),
});

/**
 * Redirects the user to the callback URL with the token
 */
export const ResetPasswordCallbackParams = zod.object({
  token: zod.string().describe("The token to reset the password"),
});

export const ResetPasswordCallbackQueryParams = zod.object({
  callbackURL: zod
    .string()
    .describe("The URL to redirect the user to reset their password"),
});

export const ResetPasswordCallbackResponse = zod.object({
  token: zod.string().optional(),
});

/**
 * List all active sessions for the user
 */
export const listUserSessionsResponseCreatedAtDefault = `Generated at runtime`;

export const ListUserSessionsResponseItem = zod.object({
  id: zod.string().optional(),
  expiresAt: zod.iso.datetime({}),
  token: zod.string(),
  createdAt: zod.iso.datetime({}),
  updatedAt: zod.iso.datetime({}),
  ipAddress: zod.string().optional(),
  userAgent: zod.string().optional(),
  userId: zod.string(),
});
export const ListUserSessionsResponse = zod.array(ListUserSessionsResponseItem);

/**
 * Revoke a single session
 */
export const PostApiAuthRevokeSessionBody = zod.object({
  token: zod.string().describe("The token to revoke"),
});

export const PostApiAuthRevokeSessionResponse = zod.object({
  status: zod
    .boolean()
    .describe("Indicates if the session was revoked successfully"),
});

/**
 * Revoke all sessions for the user
 */
export const PostApiAuthRevokeSessionsBody = zod.object({});

export const PostApiAuthRevokeSessionsResponse = zod.object({
  status: zod
    .boolean()
    .describe("Indicates if all sessions were revoked successfully"),
});

/**
 * Revoke all other sessions for the user except the current one
 */
export const PostApiAuthRevokeOtherSessionsBody = zod.object({});

export const PostApiAuthRevokeOtherSessionsResponse = zod.object({
  status: zod
    .boolean()
    .describe("Indicates if all other sessions were revoked successfully"),
});

/**
 * Link a social account to the user
 */
export const LinkSocialAccountBody = zod.object({
  callbackURL: zod
    .string()
    .nullish()
    .describe("The URL to redirect to after the user has signed in"),
  provider: zod.string(),
  idToken: zod
    .object({
      token: zod.string(),
      nonce: zod.string().nullish(),
      accessToken: zod.string().nullish(),
      refreshToken: zod.string().nullish(),
      scopes: zod.array(zod.unknown()).nullish(),
    })
    .nullish(),
  requestSignUp: zod.boolean().nullish(),
  scopes: zod
    .array(zod.unknown())
    .nullish()
    .describe("Additional scopes to request from the provider"),
  errorCallbackURL: zod
    .string()
    .nullish()
    .describe(
      "The URL to redirect to if there is an error during the link process"
    ),
  disableRedirect: zod
    .boolean()
    .nullish()
    .describe(
      "Disable automatic redirection to the provider. Useful for handling the redirection yourself"
    ),
  additionalData: zod.string().nullish(),
});

export const LinkSocialAccountResponse = zod.object({
  url: zod
    .string()
    .optional()
    .describe("The authorization URL to redirect the user to"),
  redirect: zod
    .boolean()
    .describe(
      "Indicates if the user should be redirected to the authorization URL"
    ),
  status: zod.boolean().optional(),
});

/**
 * List all accounts linked to the user
 */
export const ListUserAccountsResponseItem = zod.object({
  id: zod.string(),
  providerId: zod.string(),
  createdAt: zod.iso.datetime({}),
  updatedAt: zod.iso.datetime({}),
  accountId: zod.string(),
  userId: zod.string(),
  scopes: zod.array(zod.string()),
});
export const ListUserAccountsResponse = zod.array(ListUserAccountsResponseItem);

/**
 * Callback to complete user deletion with verification token
 */
export const GetApiAuthDeleteUserCallbackQueryParams = zod.object({
  token: zod.string().optional(),
  callbackURL: zod.string().nullish(),
});

export const GetApiAuthDeleteUserCallbackResponse = zod.object({
  success: zod.boolean().describe("Indicates if the deletion was successful"),
  message: zod.enum(["User deleted"]).describe("Confirmation message"),
});

/**
 * Unlink an account
 */
export const PostApiAuthUnlinkAccountBody = zod.object({
  providerId: zod.string(),
  accountId: zod.string().nullish(),
});

export const PostApiAuthUnlinkAccountResponse = zod.object({
  status: zod.boolean().optional(),
});

/**
 * Refresh the access token using a refresh token
 */
export const PostApiAuthRefreshTokenBody = zod.object({
  providerId: zod.string().describe("The provider ID for the OAuth provider"),
  accountId: zod
    .string()
    .nullish()
    .describe("The account ID associated with the refresh token"),
  userId: zod
    .string()
    .nullish()
    .describe("The user ID associated with the account"),
});

export const PostApiAuthRefreshTokenResponse = zod.object({
  tokenType: zod.string().optional(),
  idToken: zod.string().optional(),
  accessToken: zod.string().optional(),
  refreshToken: zod.string().optional(),
  accessTokenExpiresAt: zod.iso.datetime({}).optional(),
  refreshTokenExpiresAt: zod.iso.datetime({}).optional(),
});

/**
 * Get a valid access token, doing a refresh if needed
 */
export const PostApiAuthGetAccessTokenBody = zod.object({
  providerId: zod.string().describe("The provider ID for the OAuth provider"),
  accountId: zod
    .string()
    .nullish()
    .describe("The account ID associated with the refresh token"),
  userId: zod
    .string()
    .nullish()
    .describe("The user ID associated with the account"),
});

export const PostApiAuthGetAccessTokenResponse = zod.object({
  tokenType: zod.string().optional(),
  idToken: zod.string().optional(),
  accessToken: zod.string().optional(),
  accessTokenExpiresAt: zod.iso.datetime({}).optional(),
});

/**
 * Get the account info provided by the provider
 */
export const GetApiAuthAccountInfoResponse = zod.object({
  user: zod.object({
    id: zod.string(),
    name: zod.string().optional(),
    email: zod.string().optional(),
    image: zod.string().optional(),
    emailVerified: zod.boolean(),
  }),
  data: zod.object({}),
});

/**
 * Check if the API is working
 */
export const GetApiAuthOkResponse = zod.object({
  ok: zod.boolean().describe("Indicates if the API is working"),
});
