/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Super Impress API
 * LinkedIn post management tool API
 * OpenAPI spec version: 1.0.0
 */
export type PostCreateStatus = (typeof PostCreateStatus)[keyof typeof PostCreateStatus];

export const PostCreateStatus = {
	draft: 'draft',
	published: 'published',
	archived: 'archived'
} as const;

export interface PostCreate {
	/** @nullable */
	title?: string | null;
	/** @minLength 1 */
	content: string;
	tags?: string[];
	status?: PostCreateStatus;
}

export type PostUpdateStatus = (typeof PostUpdateStatus)[keyof typeof PostUpdateStatus];

export const PostUpdateStatus = {
	draft: 'draft',
	published: 'published',
	archived: 'archived'
} as const;

export interface PostUpdate {
	/** @nullable */
	title?: string | null;
	/** @minLength 1 */
	content?: string;
	tags?: string[];
	status?: PostUpdateStatus;
}

export type PostResponseStatus = (typeof PostResponseStatus)[keyof typeof PostResponseStatus];

export const PostResponseStatus = {
	draft: 'draft',
	published: 'published',
	archived: 'archived'
} as const;

export interface PostResponse {
	id: string;
	userId: string;
	/** @nullable */
	title: string | null;
	content: string;
	tags: string[];
	status: PostResponseStatus;
	createdAt: string;
	updatedAt: string;
}

export type PostListQueryStatus = (typeof PostListQueryStatus)[keyof typeof PostListQueryStatus];

export const PostListQueryStatus = {
	draft: 'draft',
	published: 'published',
	archived: 'archived'
} as const;

export interface PostListQuery {
	status?: PostListQueryStatus;
	tag?: string;
	/**
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
	/** @minimum 0 */
	offset?: number;
}

export type PostListResponsePostsItemStatus =
	(typeof PostListResponsePostsItemStatus)[keyof typeof PostListResponsePostsItemStatus];

export const PostListResponsePostsItemStatus = {
	draft: 'draft',
	published: 'published',
	archived: 'archived'
} as const;

export type PostListResponsePostsItem = {
	id: string;
	userId: string;
	/** @nullable */
	title: string | null;
	content: string;
	tags: string[];
	status: PostListResponsePostsItemStatus;
	createdAt: string;
	updatedAt: string;
};

export interface PostListResponse {
	posts: PostListResponsePostsItem[];
	total: number;
}

export interface PostError {
	error: string;
}

export interface User {
	id?: string;
	name: string;
	email: string;
	readonly emailVerified?: boolean;
	image?: string;
	createdAt: string;
	updatedAt: string;
}

export interface Session {
	id?: string;
	expiresAt: string;
	token: string;
	createdAt: string;
	updatedAt: string;
	ipAddress?: string;
	userAgent?: string;
	userId: string;
}

export interface Account {
	id?: string;
	accountId: string;
	providerId: string;
	userId: string;
	accessToken?: string;
	refreshToken?: string;
	idToken?: string;
	accessTokenExpiresAt?: string;
	refreshTokenExpiresAt?: string;
	scope?: string;
	password?: string;
	createdAt: string;
	updatedAt: string;
}

export interface Verification {
	id?: string;
	identifier: string;
	value: string;
	expiresAt: string;
	createdAt: string;
	updatedAt: string;
}

/**
 * @nullable
 */
export type SocialSignInRequestIdToken = {
	/** ID token from the provider */
	token: string;
	/**
	 * Nonce used to generate the token
	 * @nullable
	 */
	nonce?: string | null;
	/**
	 * Access token from the provider
	 * @nullable
	 */
	accessToken?: string | null;
	/**
	 * Refresh token from the provider
	 * @nullable
	 */
	refreshToken?: string | null;
	/**
	 * Expiry date of the token
	 * @nullable
	 */
	expiresAt?: number | null;
} | null | null;

export interface SocialSignInRequest {
	/**
	 * Callback URL to redirect to after the user has signed in
	 * @nullable
	 */
	callbackURL?: string | null;
	/** @nullable */
	newUserCallbackURL?: string | null;
	/**
	 * Callback URL to redirect to if an error happens
	 * @nullable
	 */
	errorCallbackURL?: string | null;
	provider: string;
	/**
	 * Disable automatic redirection to the provider. Useful for handling the redirection yourself
	 * @nullable
	 */
	disableRedirect?: boolean | null;
	/** @nullable */
	idToken?: SocialSignInRequestIdToken;
	/**
	 * Array of scopes to request from the provider. This will override the default scopes passed.
	 * @nullable
	 */
	scopes?: unknown[] | null;
	/**
	 * Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider
	 * @nullable
	 */
	requestSignUp?: boolean | null;
	/**
	 * The login hint to use for the authorization code request
	 * @nullable
	 */
	loginHint?: string | null;
	/** @nullable */
	additionalData?: string | null;
}

export interface SignOutRequest {
	[key: string]: unknown;
}

export interface SignUpWithEmailAndPasswordRequest {
	/** The name of the user */
	name: string;
	/** The email of the user */
	email: string;
	/** The password of the user */
	password: string;
	/** The profile image URL of the user */
	image?: string;
	/** The URL to use for email verification callback */
	callbackURL?: string;
	/** If this is false, the session will not be remembered. Default is `true`. */
	rememberMe?: boolean;
}

export interface SignInEmailRequest {
	/** Email of the user */
	email: string;
	/** Password of the user */
	password: string;
	/**
	 * Callback URL to use as a redirect for email verification
	 * @nullable
	 */
	callbackURL?: string | null;
	/**
	 * If this is false, the session will not be remembered. Default is `true`.
	 * @nullable
	 */
	rememberMe?: boolean | null;
}

export interface ResetPasswordRequest {
	/** The new password to set */
	newPassword: string;
	/**
	 * The token to reset the password
	 * @nullable
	 */
	token?: string | null;
}

export interface VerifyPasswordRequest {
	/** The password to verify */
	password: string;
}

export interface SendVerificationEmailRequest {
	/** The email to send the verification email to */
	email: string;
	/**
	 * The URL to use for email verification callback
	 * @nullable
	 */
	callbackURL?: string | null;
}

export interface ChangeEmailRequest {
	/** The new email address to set must be a valid email address */
	newEmail: string;
	/**
	 * The URL to redirect to after email verification
	 * @nullable
	 */
	callbackURL?: string | null;
}

export interface ChangePasswordRequest {
	/** The new password to set */
	newPassword: string;
	/** The current password is required */
	currentPassword: string;
	/**
	 * Must be a boolean value
	 * @nullable
	 */
	revokeOtherSessions?: boolean | null;
}

export interface UpdateUserRequest {
	/** The name of the user */
	name?: string;
	/**
	 * The image of the user
	 * @nullable
	 */
	image?: string | null;
}

export interface DeleteUserRequest {
	/** The callback URL to redirect to after the user is deleted */
	callbackURL?: string;
	/** The user's password. Required if session is not fresh */
	password?: string;
	/** The deletion verification token */
	token?: string;
}

export interface RequestPasswordResetRequest {
	/** The email address of the user to send a password reset email to */
	email: string;
	/**
	 * The URL to redirect the user to reset their password. If the token isn't valid or expired, it'll be redirected with a query parameter `?error=INVALID_TOKEN`. If the token is valid, it'll be redirected with a query parameter `?token=VALID_TOKEN
	 * @nullable
	 */
	redirectTo?: string | null;
}

export interface ApiAuthRevokeSessionPostRequest {
	/** The token to revoke */
	token: string;
}

export interface ApiAuthRevokeSessionsPostRequest {
	[key: string]: unknown;
}

export interface ApiAuthRevokeOtherSessionsPostRequest {
	[key: string]: unknown;
}

/**
 * @nullable
 */
export type LinkSocialAccountRequestIdToken = {
	token: string;
	/** @nullable */
	nonce?: string | null;
	/** @nullable */
	accessToken?: string | null;
	/** @nullable */
	refreshToken?: string | null;
	/** @nullable */
	scopes?: unknown[] | null;
} | null | null;

export interface LinkSocialAccountRequest {
	/**
	 * The URL to redirect to after the user has signed in
	 * @nullable
	 */
	callbackURL?: string | null;
	provider: string;
	/** @nullable */
	idToken?: LinkSocialAccountRequestIdToken;
	/** @nullable */
	requestSignUp?: boolean | null;
	/**
	 * Additional scopes to request from the provider
	 * @nullable
	 */
	scopes?: unknown[] | null;
	/**
	 * The URL to redirect to if there is an error during the link process
	 * @nullable
	 */
	errorCallbackURL?: string | null;
	/**
	 * Disable automatic redirection to the provider. Useful for handling the redirection yourself
	 * @nullable
	 */
	disableRedirect?: boolean | null;
	/** @nullable */
	additionalData?: string | null;
}

export interface ApiAuthUnlinkAccountPostRequest {
	providerId: string;
	/** @nullable */
	accountId?: string | null;
}

export interface ApiAuthRefreshTokenPostRequest {
	/** The provider ID for the OAuth provider */
	providerId: string;
	/**
	 * The account ID associated with the refresh token
	 * @nullable
	 */
	accountId?: string | null;
	/**
	 * The user ID associated with the account
	 * @nullable
	 */
	userId?: string | null;
}

export interface ApiAuthGetAccessTokenPostRequest {
	/** The provider ID for the OAuth provider */
	providerId: string;
	/**
	 * The account ID associated with the refresh token
	 * @nullable
	 */
	accountId?: string | null;
	/**
	 * The user ID associated with the account
	 * @nullable
	 */
	userId?: string | null;
}

export type GetApiPostsParams = {
	status?: GetApiPostsStatus;
	tag?: string;
	/**
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
	/**
	 * @minimum 0
	 */
	offset?: number;
};

export type GetApiPostsStatus = (typeof GetApiPostsStatus)[keyof typeof GetApiPostsStatus];

export const GetApiPostsStatus = {
	draft: 'draft',
	published: 'published',
	archived: 'archived'
} as const;

/**
 * Session response when idToken is provided
 */
export type SocialSignIn200 = {
	token: string;
	user: User;
	url?: string;
	redirect: boolean;
};

export type SocialSignIn400 = {
	message: string;
};

export type SocialSignIn401 = {
	message: string;
};

export type SocialSignIn403 = {
	message?: string;
};

export type SocialSignIn404 = {
	message?: string;
};

export type SocialSignIn429 = {
	message?: string;
};

export type SocialSignIn500 = {
	message?: string;
};

/**
 * @nullable
 */
export type GetSession200 = {
	session: Session;
	user: User;
} | null | null;

export type GetSession400 = {
	message: string;
};

export type GetSession401 = {
	message: string;
};

export type GetSession403 = {
	message?: string;
};

export type GetSession404 = {
	message?: string;
};

export type GetSession429 = {
	message?: string;
};

export type GetSession500 = {
	message?: string;
};

export type SignOut200 = {
	success?: boolean;
};

export type SignOut400 = {
	message: string;
};

export type SignOut401 = {
	message: string;
};

export type SignOut403 = {
	message?: string;
};

export type SignOut404 = {
	message?: string;
};

export type SignOut429 = {
	message?: string;
};

export type SignOut500 = {
	message?: string;
};

export type SignUpWithEmailAndPassword200User = {
	/** The unique identifier of the user */
	id: string;
	/** The email address of the user */
	email: string;
	/** The name of the user */
	name: string;
	/**
	 * The profile image URL of the user
	 * @nullable
	 */
	image?: string | null;
	/** Whether the email has been verified */
	emailVerified: boolean;
	/** When the user was created */
	createdAt: string;
	/** When the user was last updated */
	updatedAt: string;
};

export type SignUpWithEmailAndPassword200 = {
	/**
	 * Authentication token for the session
	 * @nullable
	 */
	token?: string | null;
	user: SignUpWithEmailAndPassword200User;
};

export type SignUpWithEmailAndPassword400 = {
	message: string;
};

export type SignUpWithEmailAndPassword401 = {
	message: string;
};

export type SignUpWithEmailAndPassword403 = {
	message?: string;
};

export type SignUpWithEmailAndPassword404 = {
	message?: string;
};

export type SignUpWithEmailAndPassword422 = {
	message?: string;
};

export type SignUpWithEmailAndPassword429 = {
	message?: string;
};

export type SignUpWithEmailAndPassword500 = {
	message?: string;
};

/**
 * Session response when idToken is provided
 */
export type SignInEmail200 = {
	redirect: boolean;
	/** Session token */
	token: string;
	/** @nullable */
	url?: string | null;
	user: User;
};

export type SignInEmail400 = {
	message: string;
};

export type SignInEmail401 = {
	message: string;
};

export type SignInEmail403 = {
	message?: string;
};

export type SignInEmail404 = {
	message?: string;
};

export type SignInEmail429 = {
	message?: string;
};

export type SignInEmail500 = {
	message?: string;
};

export type ResetPassword200 = {
	status?: boolean;
};

export type ResetPassword400 = {
	message: string;
};

export type ResetPassword401 = {
	message: string;
};

export type ResetPassword403 = {
	message?: string;
};

export type ResetPassword404 = {
	message?: string;
};

export type ResetPassword429 = {
	message?: string;
};

export type ResetPassword500 = {
	message?: string;
};

export type VerifyPassword200 = {
	status?: boolean;
};

export type VerifyPassword400 = {
	message: string;
};

export type VerifyPassword401 = {
	message: string;
};

export type VerifyPassword403 = {
	message?: string;
};

export type VerifyPassword404 = {
	message?: string;
};

export type VerifyPassword429 = {
	message?: string;
};

export type VerifyPassword500 = {
	message?: string;
};

export type GetApiAuthVerifyEmailParams = {
	/**
	 * The token to verify the email
	 */
	token: string;
	/**
	 * The URL to redirect to after email verification
	 */
	callbackURL?: string;
};

export type GetApiAuthVerifyEmail200 = {
	user: User;
	/** Indicates if the email was verified successfully */
	status: boolean;
};

export type GetApiAuthVerifyEmail400 = {
	message: string;
};

export type GetApiAuthVerifyEmail401 = {
	message: string;
};

export type GetApiAuthVerifyEmail403 = {
	message?: string;
};

export type GetApiAuthVerifyEmail404 = {
	message?: string;
};

export type GetApiAuthVerifyEmail429 = {
	message?: string;
};

export type GetApiAuthVerifyEmail500 = {
	message?: string;
};

export type SendVerificationEmail200 = {
	/** Indicates if the email was sent successfully */
	status?: boolean;
};

export type SendVerificationEmail400 = {
	/** Error message */
	message?: string;
};

export type SendVerificationEmail401 = {
	message: string;
};

export type SendVerificationEmail403 = {
	message?: string;
};

export type SendVerificationEmail404 = {
	message?: string;
};

export type SendVerificationEmail429 = {
	message?: string;
};

export type SendVerificationEmail500 = {
	message?: string;
};

/**
 * Status message of the email change process
 * @nullable
 */
export type ChangeEmail200Message =
	| (typeof ChangeEmail200Message)[keyof typeof ChangeEmail200Message]
	| null;

export const ChangeEmail200Message = {
	Email_updated: 'Email updated',
	Verification_email_sent: 'Verification email sent'
} as const;

export type ChangeEmail200 = {
	user?: User;
	/** Indicates if the request was successful */
	status: boolean;
	/**
	 * Status message of the email change process
	 * @nullable
	 */
	message?: ChangeEmail200Message;
};

export type ChangeEmail400 = {
	message: string;
};

export type ChangeEmail401 = {
	message: string;
};

export type ChangeEmail403 = {
	message?: string;
};

export type ChangeEmail404 = {
	message?: string;
};

export type ChangeEmail422 = {
	message?: string;
};

export type ChangeEmail429 = {
	message?: string;
};

export type ChangeEmail500 = {
	message?: string;
};

export type ChangePassword200User = {
	/** The unique identifier of the user */
	id: string;
	/** The email address of the user */
	email: string;
	/** The name of the user */
	name: string;
	/**
	 * The profile image URL of the user
	 * @nullable
	 */
	image?: string | null;
	/** Whether the email has been verified */
	emailVerified: boolean;
	/** When the user was created */
	createdAt: string;
	/** When the user was last updated */
	updatedAt: string;
};

export type ChangePassword200 = {
	/**
	 * New session token if other sessions were revoked
	 * @nullable
	 */
	token?: string | null;
	user: ChangePassword200User;
};

export type ChangePassword400 = {
	message: string;
};

export type ChangePassword401 = {
	message: string;
};

export type ChangePassword403 = {
	message?: string;
};

export type ChangePassword404 = {
	message?: string;
};

export type ChangePassword429 = {
	message?: string;
};

export type ChangePassword500 = {
	message?: string;
};

export type UpdateUser200 = {
	user?: User;
};

export type UpdateUser400 = {
	message: string;
};

export type UpdateUser401 = {
	message: string;
};

export type UpdateUser403 = {
	message?: string;
};

export type UpdateUser404 = {
	message?: string;
};

export type UpdateUser429 = {
	message?: string;
};

export type UpdateUser500 = {
	message?: string;
};

/**
 * Status message of the deletion process
 */
export type DeleteUser200Message = (typeof DeleteUser200Message)[keyof typeof DeleteUser200Message];

export const DeleteUser200Message = {
	User_deleted: 'User deleted',
	Verification_email_sent: 'Verification email sent'
} as const;

export type DeleteUser200 = {
	/** Indicates if the operation was successful */
	success: boolean;
	/** Status message of the deletion process */
	message: DeleteUser200Message;
};

export type DeleteUser400 = {
	message: string;
};

export type DeleteUser401 = {
	message: string;
};

export type DeleteUser403 = {
	message?: string;
};

export type DeleteUser404 = {
	message?: string;
};

export type DeleteUser429 = {
	message?: string;
};

export type DeleteUser500 = {
	message?: string;
};

export type RequestPasswordReset200 = {
	status?: boolean;
	message?: string;
};

export type RequestPasswordReset400 = {
	message: string;
};

export type RequestPasswordReset401 = {
	message: string;
};

export type RequestPasswordReset403 = {
	message?: string;
};

export type RequestPasswordReset404 = {
	message?: string;
};

export type RequestPasswordReset429 = {
	message?: string;
};

export type RequestPasswordReset500 = {
	message?: string;
};

export type ResetPasswordCallbackParams = {
	/**
	 * The URL to redirect the user to reset their password
	 */
	callbackURL: string;
};

export type ResetPasswordCallback200 = {
	token?: string;
};

export type ResetPasswordCallback400 = {
	message: string;
};

export type ResetPasswordCallback401 = {
	message: string;
};

export type ResetPasswordCallback403 = {
	message?: string;
};

export type ResetPasswordCallback404 = {
	message?: string;
};

export type ResetPasswordCallback429 = {
	message?: string;
};

export type ResetPasswordCallback500 = {
	message?: string;
};

export type ListUserSessions400 = {
	message: string;
};

export type ListUserSessions401 = {
	message: string;
};

export type ListUserSessions403 = {
	message?: string;
};

export type ListUserSessions404 = {
	message?: string;
};

export type ListUserSessions429 = {
	message?: string;
};

export type ListUserSessions500 = {
	message?: string;
};

export type PostApiAuthRevokeSession200 = {
	/** Indicates if the session was revoked successfully */
	status: boolean;
};

export type PostApiAuthRevokeSession400 = {
	message: string;
};

export type PostApiAuthRevokeSession401 = {
	message: string;
};

export type PostApiAuthRevokeSession403 = {
	message?: string;
};

export type PostApiAuthRevokeSession404 = {
	message?: string;
};

export type PostApiAuthRevokeSession429 = {
	message?: string;
};

export type PostApiAuthRevokeSession500 = {
	message?: string;
};

export type PostApiAuthRevokeSessions200 = {
	/** Indicates if all sessions were revoked successfully */
	status: boolean;
};

export type PostApiAuthRevokeSessions400 = {
	message: string;
};

export type PostApiAuthRevokeSessions401 = {
	message: string;
};

export type PostApiAuthRevokeSessions403 = {
	message?: string;
};

export type PostApiAuthRevokeSessions404 = {
	message?: string;
};

export type PostApiAuthRevokeSessions429 = {
	message?: string;
};

export type PostApiAuthRevokeSessions500 = {
	message?: string;
};

export type PostApiAuthRevokeOtherSessions200 = {
	/** Indicates if all other sessions were revoked successfully */
	status: boolean;
};

export type PostApiAuthRevokeOtherSessions400 = {
	message: string;
};

export type PostApiAuthRevokeOtherSessions401 = {
	message: string;
};

export type PostApiAuthRevokeOtherSessions403 = {
	message?: string;
};

export type PostApiAuthRevokeOtherSessions404 = {
	message?: string;
};

export type PostApiAuthRevokeOtherSessions429 = {
	message?: string;
};

export type PostApiAuthRevokeOtherSessions500 = {
	message?: string;
};

export type LinkSocialAccount200 = {
	/** The authorization URL to redirect the user to */
	url?: string;
	/** Indicates if the user should be redirected to the authorization URL */
	redirect: boolean;
	status?: boolean;
};

export type LinkSocialAccount400 = {
	message: string;
};

export type LinkSocialAccount401 = {
	message: string;
};

export type LinkSocialAccount403 = {
	message?: string;
};

export type LinkSocialAccount404 = {
	message?: string;
};

export type LinkSocialAccount429 = {
	message?: string;
};

export type LinkSocialAccount500 = {
	message?: string;
};

export type ListUserAccounts200Item = {
	id: string;
	providerId: string;
	createdAt: string;
	updatedAt: string;
	accountId: string;
	userId: string;
	scopes: string[];
};

export type ListUserAccounts400 = {
	message: string;
};

export type ListUserAccounts401 = {
	message: string;
};

export type ListUserAccounts403 = {
	message?: string;
};

export type ListUserAccounts404 = {
	message?: string;
};

export type ListUserAccounts429 = {
	message?: string;
};

export type ListUserAccounts500 = {
	message?: string;
};

export type GetApiAuthDeleteUserCallbackParams = {
	/**
	 * The token to verify the deletion request
	 */
	token?: string;
	/**
	 * The URL to redirect to after deletion
	 * @nullable
	 */
	callbackURL?: string | null;
};

/**
 * Confirmation message
 */
export type GetApiAuthDeleteUserCallback200Message =
	(typeof GetApiAuthDeleteUserCallback200Message)[keyof typeof GetApiAuthDeleteUserCallback200Message];

export const GetApiAuthDeleteUserCallback200Message = {
	User_deleted: 'User deleted'
} as const;

export type GetApiAuthDeleteUserCallback200 = {
	/** Indicates if the deletion was successful */
	success: boolean;
	/** Confirmation message */
	message: GetApiAuthDeleteUserCallback200Message;
};

export type GetApiAuthDeleteUserCallback400 = {
	message: string;
};

export type GetApiAuthDeleteUserCallback401 = {
	message: string;
};

export type GetApiAuthDeleteUserCallback403 = {
	message?: string;
};

export type GetApiAuthDeleteUserCallback404 = {
	message?: string;
};

export type GetApiAuthDeleteUserCallback429 = {
	message?: string;
};

export type GetApiAuthDeleteUserCallback500 = {
	message?: string;
};

export type PostApiAuthUnlinkAccount200 = {
	status?: boolean;
};

export type PostApiAuthUnlinkAccount400 = {
	message: string;
};

export type PostApiAuthUnlinkAccount401 = {
	message: string;
};

export type PostApiAuthUnlinkAccount403 = {
	message?: string;
};

export type PostApiAuthUnlinkAccount404 = {
	message?: string;
};

export type PostApiAuthUnlinkAccount429 = {
	message?: string;
};

export type PostApiAuthUnlinkAccount500 = {
	message?: string;
};

export type PostApiAuthRefreshToken200 = {
	tokenType?: string;
	idToken?: string;
	accessToken?: string;
	refreshToken?: string;
	accessTokenExpiresAt?: string;
	refreshTokenExpiresAt?: string;
};

export type PostApiAuthRefreshToken401 = {
	message: string;
};

export type PostApiAuthRefreshToken403 = {
	message?: string;
};

export type PostApiAuthRefreshToken404 = {
	message?: string;
};

export type PostApiAuthRefreshToken429 = {
	message?: string;
};

export type PostApiAuthRefreshToken500 = {
	message?: string;
};

export type PostApiAuthGetAccessToken200 = {
	tokenType?: string;
	idToken?: string;
	accessToken?: string;
	accessTokenExpiresAt?: string;
};

export type PostApiAuthGetAccessToken401 = {
	message: string;
};

export type PostApiAuthGetAccessToken403 = {
	message?: string;
};

export type PostApiAuthGetAccessToken404 = {
	message?: string;
};

export type PostApiAuthGetAccessToken429 = {
	message?: string;
};

export type PostApiAuthGetAccessToken500 = {
	message?: string;
};

export type GetApiAuthAccountInfo200User = {
	id: string;
	name?: string;
	email?: string;
	image?: string;
	emailVerified: boolean;
};

export type GetApiAuthAccountInfo200Data = { [key: string]: unknown };

export type GetApiAuthAccountInfo200 = {
	user: GetApiAuthAccountInfo200User;
	data: GetApiAuthAccountInfo200Data;
};

export type GetApiAuthAccountInfo400 = {
	message: string;
};

export type GetApiAuthAccountInfo401 = {
	message: string;
};

export type GetApiAuthAccountInfo403 = {
	message?: string;
};

export type GetApiAuthAccountInfo404 = {
	message?: string;
};

export type GetApiAuthAccountInfo429 = {
	message?: string;
};

export type GetApiAuthAccountInfo500 = {
	message?: string;
};

export type GetApiAuthOk200 = {
	/** Indicates if the API is working */
	ok: boolean;
};

export type GetApiAuthOk400 = {
	message: string;
};

export type GetApiAuthOk401 = {
	message: string;
};

export type GetApiAuthOk403 = {
	message?: string;
};

export type GetApiAuthOk404 = {
	message?: string;
};

export type GetApiAuthOk429 = {
	message?: string;
};

export type GetApiAuthOk500 = {
	message?: string;
};

export type GetApiAuthError400 = {
	message: string;
};

export type GetApiAuthError401 = {
	message: string;
};

export type GetApiAuthError403 = {
	message?: string;
};

export type GetApiAuthError404 = {
	message?: string;
};

export type GetApiAuthError429 = {
	message?: string;
};

export type GetApiAuthError500 = {
	message?: string;
};
