/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * SuperImpress API
 * LinkedIn post management tool API
 * OpenAPI spec version: 1.0.0
 */
export interface PostCreate {
  /** @nullable */
  title?: string | null;
  /** @minLength 1 */
  content: string;
  tags?: string[];
}

export interface PostUpdate {
  /** @nullable */
  title?: string | null;
  /** @minLength 1 */
  content?: string;
  tags?: string[];
}

export type PostResponseStatus =
  (typeof PostResponseStatus)[keyof typeof PostResponseStatus];

export const PostResponseStatus = {
  draft: "draft",
  published: "published",
} as const;

export type PostResponsePublicationsItemPlatform =
  (typeof PostResponsePublicationsItemPlatform)[keyof typeof PostResponsePublicationsItemPlatform];

export const PostResponsePublicationsItemPlatform = {
  linkedin: "linkedin",
  twitter: "twitter",
  threads: "threads",
  peerlist: "peerlist",
} as const;

export type PostResponsePublicationsItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  platform: PostResponsePublicationsItemPlatform;
  /** @nullable */
  platformPostId: string | null;
  /** @nullable */
  url: string | null;
  /** @nullable */
  accountId: string | null;
  publishedAt: string;
};

export interface PostResponse {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  userId: string;
  /** @nullable */
  title: string | null;
  content: string;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  status: PostResponseStatus;
  publications?: PostResponsePublicationsItem[];
}

export type PostListQueryStatus =
  (typeof PostListQueryStatus)[keyof typeof PostListQueryStatus];

export const PostListQueryStatus = {
  draft: "draft",
  published: "published",
} as const;

export interface PostListQuery {
  status?: PostListQueryStatus;
  tag?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
}

export type PostListResponsePostsItemStatus =
  (typeof PostListResponsePostsItemStatus)[keyof typeof PostListResponsePostsItemStatus];

export const PostListResponsePostsItemStatus = {
  draft: "draft",
  published: "published",
} as const;

export type PostListResponsePostsItemPublicationsItemPlatform =
  (typeof PostListResponsePostsItemPublicationsItemPlatform)[keyof typeof PostListResponsePostsItemPublicationsItemPlatform];

export const PostListResponsePostsItemPublicationsItemPlatform = {
  linkedin: "linkedin",
  twitter: "twitter",
  threads: "threads",
  peerlist: "peerlist",
} as const;

export type PostListResponsePostsItemPublicationsItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  platform: PostListResponsePostsItemPublicationsItemPlatform;
  /** @nullable */
  platformPostId: string | null;
  /** @nullable */
  url: string | null;
  /** @nullable */
  accountId: string | null;
  publishedAt: string;
};

export type PostListResponsePostsItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  userId: string;
  /** @nullable */
  title: string | null;
  content: string;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  status: PostListResponsePostsItemStatus;
  publications?: PostListResponsePostsItemPublicationsItem[];
};

export interface PostListResponse {
  posts: PostListResponsePostsItem[];
  total: number;
}

export type PostSummaryResponseStatusCounts = {
  draft: number;
  published: number;
};

export interface PostSummaryResponse {
  totalPosts: number;
  totalWordCount: number;
  statusCounts: PostSummaryResponseStatusCounts;
}

export type ManualPublicationRequestPlatform =
  (typeof ManualPublicationRequestPlatform)[keyof typeof ManualPublicationRequestPlatform];

export const ManualPublicationRequestPlatform = {
  linkedin: "linkedin",
  twitter: "twitter",
  threads: "threads",
  peerlist: "peerlist",
} as const;

export interface ManualPublicationRequest {
  platform: ManualPublicationRequestPlatform;
  url: string;
}

export type ManualPublicationResponsePlatform =
  (typeof ManualPublicationResponsePlatform)[keyof typeof ManualPublicationResponsePlatform];

export const ManualPublicationResponsePlatform = {
  linkedin: "linkedin",
  twitter: "twitter",
  threads: "threads",
  peerlist: "peerlist",
} as const;

export interface ManualPublicationResponse {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  postId: number;
  platform: ManualPublicationResponsePlatform;
  /** @nullable */
  url: string | null;
  publishedAt: string;
}

export interface PostError {
  error: string;
}

export interface LinkedInPostRequest {
  postId: string;
}

export interface LinkedInPostResponse {
  success: boolean;
  linkedInPostId?: string;
  message?: string;
}

export interface LinkedInConnectionStatus {
  connected: boolean;
  accountId?: string;
  email?: string;
}

export interface LinkedInError {
  error: string;
}

export interface User {
  id?: string;
  name: string;
  email: string;
  readonly emailVerified?: boolean;
  image?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Session {
  id?: string;
  expiresAt: string;
  token: string;
  createdAt: string;
  updatedAt: string;
  ipAddress?: string;
  userAgent?: string;
  userId: string;
}

export interface Account {
  id?: string;
  accountId: string;
  providerId: string;
  userId: string;
  accessToken?: string;
  refreshToken?: string;
  idToken?: string;
  accessTokenExpiresAt?: string;
  refreshTokenExpiresAt?: string;
  scope?: string;
  password?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Verification {
  id?: string;
  identifier: string;
  value: string;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetLinkedinStatusResponse200 {
  connected: boolean;
  accountId?: string;
  email?: string;
}

export interface PostLinkedinPostRequest {
  postId: string;
}

export interface PostLinkedinPostResponse200 {
  success: boolean;
  linkedInPostId?: string;
  message?: string;
}

export interface PostLinkedinPostResponse400 {
  success: boolean;
  linkedInPostId?: string;
  message?: string;
}

/**
 * @nullable
 */
export type SocialSignInRequestIdToken = {
  /** ID token from the provider */
  token: string;
  /**
   * Nonce used to generate the token
   * @nullable
   */
  nonce?: string | null;
  /**
   * Access token from the provider
   * @nullable
   */
  accessToken?: string | null;
  /**
   * Refresh token from the provider
   * @nullable
   */
  refreshToken?: string | null;
  /**
   * Expiry date of the token
   * @nullable
   */
  expiresAt?: number | null;
} | null;

export interface SocialSignInRequest {
  /**
   * Callback URL to redirect to after the user has signed in
   * @nullable
   */
  callbackURL?: string | null;
  /** @nullable */
  newUserCallbackURL?: string | null;
  /**
   * Callback URL to redirect to if an error happens
   * @nullable
   */
  errorCallbackURL?: string | null;
  provider: string;
  /**
   * Disable automatic redirection to the provider. Useful for handling the redirection yourself
   * @nullable
   */
  disableRedirect?: boolean | null;
  /** @nullable */
  idToken?: SocialSignInRequestIdToken;
  /**
   * Array of scopes to request from the provider. This will override the default scopes passed.
   * @nullable
   */
  scopes?: unknown[] | null;
  /**
   * Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider
   * @nullable
   */
  requestSignUp?: boolean | null;
  /**
   * The login hint to use for the authorization code request
   * @nullable
   */
  loginHint?: string | null;
  /** @nullable */
  additionalData?: string | null;
}

/**
 * Session response when idToken is provided
 */
export interface SocialSignInResponse200 {
  token: string;
  user: User;
  url?: string;
  redirect: boolean;
}

export interface SocialSignInResponse400 {
  message: string;
}

export interface SocialSignInResponse401 {
  message: string;
}

export interface SocialSignInResponse403 {
  message?: string;
}

export interface SocialSignInResponse404 {
  message?: string;
}

export interface SocialSignInResponse429 {
  message?: string;
}

export interface SocialSignInResponse500 {
  message?: string;
}

/**
 * @nullable
 */
export type GetSessionResponse200 = {
  session: Session;
  user: User;
} | null;

export interface GetSessionResponse400 {
  message: string;
}

export interface GetSessionResponse401 {
  message: string;
}

export interface GetSessionResponse403 {
  message?: string;
}

export interface GetSessionResponse404 {
  message?: string;
}

export interface GetSessionResponse429 {
  message?: string;
}

export interface GetSessionResponse500 {
  message?: string;
}

export interface SignOutRequest {
  [key: string]: unknown;
}

export interface SignOutResponse200 {
  success?: boolean;
}

export interface SignOutResponse400 {
  message: string;
}

export interface SignOutResponse401 {
  message: string;
}

export interface SignOutResponse403 {
  message?: string;
}

export interface SignOutResponse404 {
  message?: string;
}

export interface SignOutResponse429 {
  message?: string;
}

export interface SignOutResponse500 {
  message?: string;
}

export interface SignUpWithEmailAndPasswordRequest {
  /** The name of the user */
  name: string;
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
  /** The profile image URL of the user */
  image?: string;
  /** The URL to use for email verification callback */
  callbackURL?: string;
  /** If this is false, the session will not be remembered. Default is `true`. */
  rememberMe?: boolean;
}

export type SignUpWithEmailAndPasswordResponse200User = {
  /** The unique identifier of the user */
  id: string;
  /** The email address of the user */
  email: string;
  /** The name of the user */
  name: string;
  /**
   * The profile image URL of the user
   * @nullable
   */
  image?: string | null;
  /** Whether the email has been verified */
  emailVerified: boolean;
  /** When the user was created */
  createdAt: string;
  /** When the user was last updated */
  updatedAt: string;
};

export interface SignUpWithEmailAndPasswordResponse200 {
  /**
   * Authentication token for the session
   * @nullable
   */
  token?: string | null;
  user: SignUpWithEmailAndPasswordResponse200User;
}

export interface SignUpWithEmailAndPasswordResponse400 {
  message: string;
}

export interface SignUpWithEmailAndPasswordResponse401 {
  message: string;
}

export interface SignUpWithEmailAndPasswordResponse403 {
  message?: string;
}

export interface SignUpWithEmailAndPasswordResponse404 {
  message?: string;
}

export interface SignUpWithEmailAndPasswordResponse422 {
  message?: string;
}

export interface SignUpWithEmailAndPasswordResponse429 {
  message?: string;
}

export interface SignUpWithEmailAndPasswordResponse500 {
  message?: string;
}

export interface SignInEmailRequest {
  /** Email of the user */
  email: string;
  /** Password of the user */
  password: string;
  /**
   * Callback URL to use as a redirect for email verification
   * @nullable
   */
  callbackURL?: string | null;
  /**
   * If this is false, the session will not be remembered. Default is `true`.
   * @nullable
   */
  rememberMe?: boolean | null;
}

/**
 * Session response when idToken is provided
 */
export interface SignInEmailResponse200 {
  redirect: boolean;
  /** Session token */
  token: string;
  /** @nullable */
  url?: string | null;
  user: User;
}

export interface SignInEmailResponse400 {
  message: string;
}

export interface SignInEmailResponse401 {
  message: string;
}

export interface SignInEmailResponse403 {
  message?: string;
}

export interface SignInEmailResponse404 {
  message?: string;
}

export interface SignInEmailResponse429 {
  message?: string;
}

export interface SignInEmailResponse500 {
  message?: string;
}

export interface ResetPasswordRequest {
  /** The new password to set */
  newPassword: string;
  /**
   * The token to reset the password
   * @nullable
   */
  token?: string | null;
}

export interface ResetPasswordResponse200 {
  status?: boolean;
}

export interface ResetPasswordResponse400 {
  message: string;
}

export interface ResetPasswordResponse401 {
  message: string;
}

export interface ResetPasswordResponse403 {
  message?: string;
}

export interface ResetPasswordResponse404 {
  message?: string;
}

export interface ResetPasswordResponse429 {
  message?: string;
}

export interface ResetPasswordResponse500 {
  message?: string;
}

export interface VerifyPasswordRequest {
  /** The password to verify */
  password: string;
}

export interface VerifyPasswordResponse200 {
  status?: boolean;
}

export interface VerifyPasswordResponse400 {
  message: string;
}

export interface VerifyPasswordResponse401 {
  message: string;
}

export interface VerifyPasswordResponse403 {
  message?: string;
}

export interface VerifyPasswordResponse404 {
  message?: string;
}

export interface VerifyPasswordResponse429 {
  message?: string;
}

export interface VerifyPasswordResponse500 {
  message?: string;
}

export interface AuthVerifyEmailGetResponse200 {
  user: User;
  /** Indicates if the email was verified successfully */
  status: boolean;
}

export interface AuthVerifyEmailGetResponse400 {
  message: string;
}

export interface AuthVerifyEmailGetResponse401 {
  message: string;
}

export interface AuthVerifyEmailGetResponse403 {
  message?: string;
}

export interface AuthVerifyEmailGetResponse404 {
  message?: string;
}

export interface AuthVerifyEmailGetResponse429 {
  message?: string;
}

export interface AuthVerifyEmailGetResponse500 {
  message?: string;
}

export interface SendVerificationEmailRequest {
  /** The email to send the verification email to */
  email: string;
  /**
   * The URL to use for email verification callback
   * @nullable
   */
  callbackURL?: string | null;
}

export interface SendVerificationEmailResponse200 {
  /** Indicates if the email was sent successfully */
  status?: boolean;
}

export interface SendVerificationEmailResponse400 {
  /** Error message */
  message?: string;
}

export interface SendVerificationEmailResponse401 {
  message: string;
}

export interface SendVerificationEmailResponse403 {
  message?: string;
}

export interface SendVerificationEmailResponse404 {
  message?: string;
}

export interface SendVerificationEmailResponse429 {
  message?: string;
}

export interface SendVerificationEmailResponse500 {
  message?: string;
}

export interface ChangeEmailRequest {
  /** The new email address to set must be a valid email address */
  newEmail: string;
  /**
   * The URL to redirect to after email verification
   * @nullable
   */
  callbackURL?: string | null;
}

/**
 * Status message of the email change process
 * @nullable
 */
export type ChangeEmailResponse200Message =
  | (typeof ChangeEmailResponse200Message)[keyof typeof ChangeEmailResponse200Message]
  | null;

export const ChangeEmailResponse200Message = {
  Email_updated: "Email updated",
  Verification_email_sent: "Verification email sent",
} as const;

export interface ChangeEmailResponse200 {
  user?: User;
  /** Indicates if the request was successful */
  status: boolean;
  /**
   * Status message of the email change process
   * @nullable
   */
  message?: ChangeEmailResponse200Message;
}

export interface ChangeEmailResponse400 {
  message: string;
}

export interface ChangeEmailResponse401 {
  message: string;
}

export interface ChangeEmailResponse403 {
  message?: string;
}

export interface ChangeEmailResponse404 {
  message?: string;
}

export interface ChangeEmailResponse422 {
  message?: string;
}

export interface ChangeEmailResponse429 {
  message?: string;
}

export interface ChangeEmailResponse500 {
  message?: string;
}

export interface ChangePasswordRequest {
  /** The new password to set */
  newPassword: string;
  /** The current password is required */
  currentPassword: string;
  /**
   * Must be a boolean value
   * @nullable
   */
  revokeOtherSessions?: boolean | null;
}

export type ChangePasswordResponse200User = {
  /** The unique identifier of the user */
  id: string;
  /** The email address of the user */
  email: string;
  /** The name of the user */
  name: string;
  /**
   * The profile image URL of the user
   * @nullable
   */
  image?: string | null;
  /** Whether the email has been verified */
  emailVerified: boolean;
  /** When the user was created */
  createdAt: string;
  /** When the user was last updated */
  updatedAt: string;
};

export interface ChangePasswordResponse200 {
  /**
   * New session token if other sessions were revoked
   * @nullable
   */
  token?: string | null;
  user: ChangePasswordResponse200User;
}

export interface ChangePasswordResponse400 {
  message: string;
}

export interface ChangePasswordResponse401 {
  message: string;
}

export interface ChangePasswordResponse403 {
  message?: string;
}

export interface ChangePasswordResponse404 {
  message?: string;
}

export interface ChangePasswordResponse429 {
  message?: string;
}

export interface ChangePasswordResponse500 {
  message?: string;
}

export interface UpdateUserRequest {
  /** The name of the user */
  name?: string;
  /**
   * The image of the user
   * @nullable
   */
  image?: string | null;
}

export interface UpdateUserResponse200 {
  user?: User;
}

export interface UpdateUserResponse400 {
  message: string;
}

export interface UpdateUserResponse401 {
  message: string;
}

export interface UpdateUserResponse403 {
  message?: string;
}

export interface UpdateUserResponse404 {
  message?: string;
}

export interface UpdateUserResponse429 {
  message?: string;
}

export interface UpdateUserResponse500 {
  message?: string;
}

export interface DeleteUserRequest {
  /** The callback URL to redirect to after the user is deleted */
  callbackURL?: string;
  /** The user's password. Required if session is not fresh */
  password?: string;
  /** The deletion verification token */
  token?: string;
}

/**
 * Status message of the deletion process
 */
export type DeleteUserResponse200Message =
  (typeof DeleteUserResponse200Message)[keyof typeof DeleteUserResponse200Message];

export const DeleteUserResponse200Message = {
  User_deleted: "User deleted",
  Verification_email_sent: "Verification email sent",
} as const;

export interface DeleteUserResponse200 {
  /** Indicates if the operation was successful */
  success: boolean;
  /** Status message of the deletion process */
  message: DeleteUserResponse200Message;
}

export interface DeleteUserResponse400 {
  message: string;
}

export interface DeleteUserResponse401 {
  message: string;
}

export interface DeleteUserResponse403 {
  message?: string;
}

export interface DeleteUserResponse404 {
  message?: string;
}

export interface DeleteUserResponse429 {
  message?: string;
}

export interface DeleteUserResponse500 {
  message?: string;
}

export interface RequestPasswordResetRequest {
  /** The email address of the user to send a password reset email to */
  email: string;
  /**
   * The URL to redirect the user to reset their password. If the token isn't valid or expired, it'll be redirected with a query parameter `?error=INVALID_TOKEN`. If the token is valid, it'll be redirected with a query parameter `?token=VALID_TOKEN
   * @nullable
   */
  redirectTo?: string | null;
}

export interface RequestPasswordResetResponse200 {
  status?: boolean;
  message?: string;
}

export interface RequestPasswordResetResponse400 {
  message: string;
}

export interface RequestPasswordResetResponse401 {
  message: string;
}

export interface RequestPasswordResetResponse403 {
  message?: string;
}

export interface RequestPasswordResetResponse404 {
  message?: string;
}

export interface RequestPasswordResetResponse429 {
  message?: string;
}

export interface RequestPasswordResetResponse500 {
  message?: string;
}

export interface ResetPasswordCallbackResponse200 {
  token?: string;
}

export interface ResetPasswordCallbackResponse400 {
  message: string;
}

export interface ResetPasswordCallbackResponse401 {
  message: string;
}

export interface ResetPasswordCallbackResponse403 {
  message?: string;
}

export interface ResetPasswordCallbackResponse404 {
  message?: string;
}

export interface ResetPasswordCallbackResponse429 {
  message?: string;
}

export interface ResetPasswordCallbackResponse500 {
  message?: string;
}

export type ListUserSessionsResponse200 = Session[];

export interface ListUserSessionsResponse400 {
  message: string;
}

export interface ListUserSessionsResponse401 {
  message: string;
}

export interface ListUserSessionsResponse403 {
  message?: string;
}

export interface ListUserSessionsResponse404 {
  message?: string;
}

export interface ListUserSessionsResponse429 {
  message?: string;
}

export interface ListUserSessionsResponse500 {
  message?: string;
}

export interface AuthRevokeSessionPostRequest {
  /** The token to revoke */
  token: string;
}

export interface AuthRevokeSessionPostResponse200 {
  /** Indicates if the session was revoked successfully */
  status: boolean;
}

export interface AuthRevokeSessionPostResponse400 {
  message: string;
}

export interface AuthRevokeSessionPostResponse401 {
  message: string;
}

export interface AuthRevokeSessionPostResponse403 {
  message?: string;
}

export interface AuthRevokeSessionPostResponse404 {
  message?: string;
}

export interface AuthRevokeSessionPostResponse429 {
  message?: string;
}

export interface AuthRevokeSessionPostResponse500 {
  message?: string;
}

export interface AuthRevokeSessionsPostRequest {
  [key: string]: unknown;
}

export interface AuthRevokeSessionsPostResponse200 {
  /** Indicates if all sessions were revoked successfully */
  status: boolean;
}

export interface AuthRevokeSessionsPostResponse400 {
  message: string;
}

export interface AuthRevokeSessionsPostResponse401 {
  message: string;
}

export interface AuthRevokeSessionsPostResponse403 {
  message?: string;
}

export interface AuthRevokeSessionsPostResponse404 {
  message?: string;
}

export interface AuthRevokeSessionsPostResponse429 {
  message?: string;
}

export interface AuthRevokeSessionsPostResponse500 {
  message?: string;
}

export interface AuthRevokeOtherSessionsPostRequest {
  [key: string]: unknown;
}

export interface AuthRevokeOtherSessionsPostResponse200 {
  /** Indicates if all other sessions were revoked successfully */
  status: boolean;
}

export interface AuthRevokeOtherSessionsPostResponse400 {
  message: string;
}

export interface AuthRevokeOtherSessionsPostResponse401 {
  message: string;
}

export interface AuthRevokeOtherSessionsPostResponse403 {
  message?: string;
}

export interface AuthRevokeOtherSessionsPostResponse404 {
  message?: string;
}

export interface AuthRevokeOtherSessionsPostResponse429 {
  message?: string;
}

export interface AuthRevokeOtherSessionsPostResponse500 {
  message?: string;
}

/**
 * @nullable
 */
export type LinkSocialAccountRequestIdToken = {
  token: string;
  /** @nullable */
  nonce?: string | null;
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  /** @nullable */
  scopes?: unknown[] | null;
} | null;

export interface LinkSocialAccountRequest {
  /**
   * The URL to redirect to after the user has signed in
   * @nullable
   */
  callbackURL?: string | null;
  provider: string;
  /** @nullable */
  idToken?: LinkSocialAccountRequestIdToken;
  /** @nullable */
  requestSignUp?: boolean | null;
  /**
   * Additional scopes to request from the provider
   * @nullable
   */
  scopes?: unknown[] | null;
  /**
   * The URL to redirect to if there is an error during the link process
   * @nullable
   */
  errorCallbackURL?: string | null;
  /**
   * Disable automatic redirection to the provider. Useful for handling the redirection yourself
   * @nullable
   */
  disableRedirect?: boolean | null;
  /** @nullable */
  additionalData?: string | null;
}

export interface LinkSocialAccountResponse200 {
  /** The authorization URL to redirect the user to */
  url?: string;
  /** Indicates if the user should be redirected to the authorization URL */
  redirect: boolean;
  status?: boolean;
}

export interface LinkSocialAccountResponse400 {
  message: string;
}

export interface LinkSocialAccountResponse401 {
  message: string;
}

export interface LinkSocialAccountResponse403 {
  message?: string;
}

export interface LinkSocialAccountResponse404 {
  message?: string;
}

export interface LinkSocialAccountResponse429 {
  message?: string;
}

export interface LinkSocialAccountResponse500 {
  message?: string;
}

export type ListUserAccountsResponse200Item = {
  id: string;
  providerId: string;
  createdAt: string;
  updatedAt: string;
  accountId: string;
  userId: string;
  scopes: string[];
};

export type ListUserAccountsResponse200 = ListUserAccountsResponse200Item[];

export interface ListUserAccountsResponse400 {
  message: string;
}

export interface ListUserAccountsResponse401 {
  message: string;
}

export interface ListUserAccountsResponse403 {
  message?: string;
}

export interface ListUserAccountsResponse404 {
  message?: string;
}

export interface ListUserAccountsResponse429 {
  message?: string;
}

export interface ListUserAccountsResponse500 {
  message?: string;
}

/**
 * Confirmation message
 */
export type AuthDeleteUserCallbackGetResponse200Message =
  (typeof AuthDeleteUserCallbackGetResponse200Message)[keyof typeof AuthDeleteUserCallbackGetResponse200Message];

export const AuthDeleteUserCallbackGetResponse200Message = {
  User_deleted: "User deleted",
} as const;

export interface AuthDeleteUserCallbackGetResponse200 {
  /** Indicates if the deletion was successful */
  success: boolean;
  /** Confirmation message */
  message: AuthDeleteUserCallbackGetResponse200Message;
}

export interface AuthDeleteUserCallbackGetResponse400 {
  message: string;
}

export interface AuthDeleteUserCallbackGetResponse401 {
  message: string;
}

export interface AuthDeleteUserCallbackGetResponse403 {
  message?: string;
}

export interface AuthDeleteUserCallbackGetResponse404 {
  message?: string;
}

export interface AuthDeleteUserCallbackGetResponse429 {
  message?: string;
}

export interface AuthDeleteUserCallbackGetResponse500 {
  message?: string;
}

export interface AuthUnlinkAccountPostRequest {
  providerId: string;
  /** @nullable */
  accountId?: string | null;
}

export interface AuthUnlinkAccountPostResponse200 {
  status?: boolean;
}

export interface AuthUnlinkAccountPostResponse400 {
  message: string;
}

export interface AuthUnlinkAccountPostResponse401 {
  message: string;
}

export interface AuthUnlinkAccountPostResponse403 {
  message?: string;
}

export interface AuthUnlinkAccountPostResponse404 {
  message?: string;
}

export interface AuthUnlinkAccountPostResponse429 {
  message?: string;
}

export interface AuthUnlinkAccountPostResponse500 {
  message?: string;
}

export interface AuthRefreshTokenPostRequest {
  /** The provider ID for the OAuth provider */
  providerId: string;
  /**
   * The account ID associated with the refresh token
   * @nullable
   */
  accountId?: string | null;
  /**
   * The user ID associated with the account
   * @nullable
   */
  userId?: string | null;
}

export interface AuthRefreshTokenPostResponse200 {
  tokenType?: string;
  idToken?: string;
  accessToken?: string;
  refreshToken?: string;
  accessTokenExpiresAt?: string;
  refreshTokenExpiresAt?: string;
}

export interface AuthRefreshTokenPostResponse401 {
  message: string;
}

export interface AuthRefreshTokenPostResponse403 {
  message?: string;
}

export interface AuthRefreshTokenPostResponse404 {
  message?: string;
}

export interface AuthRefreshTokenPostResponse429 {
  message?: string;
}

export interface AuthRefreshTokenPostResponse500 {
  message?: string;
}

export interface AuthGetAccessTokenPostRequest {
  /** The provider ID for the OAuth provider */
  providerId: string;
  /**
   * The account ID associated with the refresh token
   * @nullable
   */
  accountId?: string | null;
  /**
   * The user ID associated with the account
   * @nullable
   */
  userId?: string | null;
}

export interface AuthGetAccessTokenPostResponse200 {
  tokenType?: string;
  idToken?: string;
  accessToken?: string;
  accessTokenExpiresAt?: string;
}

export interface AuthGetAccessTokenPostResponse401 {
  message: string;
}

export interface AuthGetAccessTokenPostResponse403 {
  message?: string;
}

export interface AuthGetAccessTokenPostResponse404 {
  message?: string;
}

export interface AuthGetAccessTokenPostResponse429 {
  message?: string;
}

export interface AuthGetAccessTokenPostResponse500 {
  message?: string;
}

export type AuthAccountInfoGetResponse200User = {
  id: string;
  name?: string;
  email?: string;
  image?: string;
  emailVerified: boolean;
};

export type AuthAccountInfoGetResponse200Data = { [key: string]: unknown };

export interface AuthAccountInfoGetResponse200 {
  user: AuthAccountInfoGetResponse200User;
  data: AuthAccountInfoGetResponse200Data;
}

export interface AuthAccountInfoGetResponse400 {
  message: string;
}

export interface AuthAccountInfoGetResponse401 {
  message: string;
}

export interface AuthAccountInfoGetResponse403 {
  message?: string;
}

export interface AuthAccountInfoGetResponse404 {
  message?: string;
}

export interface AuthAccountInfoGetResponse429 {
  message?: string;
}

export interface AuthAccountInfoGetResponse500 {
  message?: string;
}

export interface AuthOkGetResponse200 {
  /** Indicates if the API is working */
  ok: boolean;
}

export interface AuthOkGetResponse400 {
  message: string;
}

export interface AuthOkGetResponse401 {
  message: string;
}

export interface AuthOkGetResponse403 {
  message?: string;
}

export interface AuthOkGetResponse404 {
  message?: string;
}

export interface AuthOkGetResponse429 {
  message?: string;
}

export interface AuthOkGetResponse500 {
  message?: string;
}

export interface AuthErrorGetResponse400 {
  message: string;
}

export interface AuthErrorGetResponse401 {
  message: string;
}

export interface AuthErrorGetResponse403 {
  message?: string;
}

export interface AuthErrorGetResponse404 {
  message?: string;
}

export interface AuthErrorGetResponse429 {
  message?: string;
}

export interface AuthErrorGetResponse500 {
  message?: string;
}

export type GetPostsParams = {
  status?: GetPostsStatus;
  tag?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number;
};

export type GetPostsStatus =
  (typeof GetPostsStatus)[keyof typeof GetPostsStatus];

export const GetPostsStatus = {
  draft: "draft",
  published: "published",
} as const;

export type GetAuthVerifyEmailParams = {
  /**
   * The token to verify the email
   */
  token: string;
  /**
   * The URL to redirect to after email verification
   */
  callbackURL?: string;
};

export type ResetPasswordCallbackParams = {
  /**
   * The URL to redirect the user to reset their password
   */
  callbackURL: string;
};

export type GetAuthDeleteUserCallbackParams = {
  /**
   * The token to verify the deletion request
   */
  token?: string;
  /**
   * The URL to redirect to after deletion
   * @nullable
   */
  callbackURL?: string | null;
};
