/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
export interface BodyLoginUser {
	grant_type?: string | null;
	username: string;
	password: string;
	scope?: string;
	client_id?: string | null;
	client_secret?: string | null;
}

/**
 * Schema for confirming email verification.
 */
export interface EmailVerificationConfirm {
	token: string;
}

/**
 * Schema for requesting email verification resend.
 */
export interface EmailVerificationRequest {
	email: string;
}

/**
 * Schema for verification responses.
 */
export interface EmailVerificationResponse {
	message: string;
	email?: string | null;
}

export interface ValidationError {
	loc: (string | number)[];
	msg: string;
	type: string;
}

export interface HTTPValidationError {
	detail?: ValidationError[];
}

/**
 * Request body for OAuth callback.
 */
export interface LinkedInConnectCallback {
	code: string;
	state: string;
}

/**
 * Response when initiating LinkedIn OAuth flow.
 */
export interface LinkedInConnectInitiate {
	authorization_url: string;
	state: string;
}

/**
 * LinkedIn connection status for a user.
 */
export interface LinkedInConnectionStatus {
	connected: boolean;
	person_urn?: string | null;
	connected_at?: string | null;
	expires_at?: string | null;
}

/**
 * Request to post content to LinkedIn.
 */
export interface LinkedInPostRequest {
	post_id: number;
}

/**
 * Response after posting to LinkedIn.
 */
export interface LinkedInPostResponse {
	success: boolean;
	linkedin_post_id: string;
}

/**
 * Schema for changing a user's password.
 */
export interface PasswordChange {
	old_password: string;
	/**
	 * Must contain uppercase, lowercase, digit, and special character
	 * @minLength 8
	 * @maxLength 15
	 */
	new_password: string;
}

/**
 * Post status enumeration.
 */
export type PostStatus = (typeof PostStatus)[keyof typeof PostStatus];

export const PostStatus = {
	draft: 'draft',
	published: 'published',
	archived: 'archived'
} as const;

/**
 * Schema for creating a new post.
 */
export interface PostCreate {
	/** Post title */
	title?: string | null;
	/**
	 * Post content
	 * @minLength 1
	 */
	content: string;
	/** Post tags */
	tags?: string[];
	status?: PostStatus;
}

/**
 * Schema for post public data.
 */
export interface PostPublic {
	/** Post title */
	title?: string | null;
	/**
	 * Post content
	 * @minLength 1
	 */
	content: string;
	/** Post tags */
	tags?: string[];
	id: number;
	user_id: number;
	status: PostStatus;
	created_at: string;
	updated_at: string;
}

/**
 * Response schema for listing posts.
 */
export interface PostListResponse {
	posts: PostPublic[];
	total: number;
}

/**
 * Schema for updating a post (all fields optional).
 */
export interface PostUpdate {
	title?: string | null;
	content?: string | null;
	tags?: string[] | null;
	status?: PostStatus | null;
}

/**
 * JWT token response schema.
 */
export interface Token {
	access_token: string;
	token_type: string;
}

/**
 * Schema for creating a new user.
 */
export interface UserCreate {
	email: string;
	/**
	 * Must contain uppercase, lowercase, digit, and special character
	 * @minLength 8
	 * @maxLength 15
	 */
	password: string;
}

/**
 * Schema for user public data (excludes password).
 */
export interface UserPublic {
	email: string;
	id: number;
	email_verified: boolean;
}

export type ListPostsParams = {
	/**
	 * Filter by post status
	 */
	status?: PostStatus | null;
	/**
	 * Filter by tag
	 */
	tag?: string | null;
	/**
	 * Number of posts to return
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
	/**
	 * Number of posts to skip
	 * @minimum 0
	 */
	offset?: number;
};
