/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import { createMutation, createQuery } from '@tanstack/svelte-query';
import type {
	CreateMutationOptions,
	CreateMutationResult,
	CreateQueryOptions,
	CreateQueryResult,
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey
} from '@tanstack/svelte-query';

import type {
	HTTPValidationError,
	ListPostsParams,
	PostCreate,
	PostListResponse,
	PostPublic,
	PostUpdate,
	SchedulePostRequest
} from '../superimpress.schemas';

import { customInstance } from '.././axios';
import type { ErrorType } from '.././axios';

/**
 * Create a new post for the authenticated user.
 * @summary Create Post Endpoint
 */
export const createPost = (postCreate: PostCreate, signal?: AbortSignal) => {
	return customInstance<PostPublic>({
		url: `/api/posts`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: postCreate,
		signal
	});
};

export const getCreatePostMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof createPost>>,
		TError,
		{ data: PostCreate },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof createPost>>,
	TError,
	{ data: PostCreate },
	TContext
> => {
	const mutationKey = ['createPost'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createPost>>,
		{ data: PostCreate }
	> = (props) => {
		const { data } = props ?? {};

		return createPost(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreatePostMutationResult = NonNullable<Awaited<ReturnType<typeof createPost>>>;
export type CreatePostMutationBody = PostCreate;
export type CreatePostMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Create Post Endpoint
 */
export const createCreatePost = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof createPost>>,
			TError,
			{ data: PostCreate },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof createPost>>,
	TError,
	{ data: PostCreate },
	TContext
> => {
	const mutationOptions = getCreatePostMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * List posts for the authenticated user with optional filters.
 * @summary List Posts Endpoint
 */
export const listPosts = (params?: ListPostsParams, signal?: AbortSignal) => {
	return customInstance<PostListResponse>({ url: `/api/posts`, method: 'GET', params, signal });
};

export const getListPostsQueryKey = (params?: ListPostsParams) => {
	return [`/api/posts`, ...(params ? [params] : [])] as const;
};

export const getListPostsQueryOptions = <
	TData = Awaited<ReturnType<typeof listPosts>>,
	TError = ErrorType<HTTPValidationError>
>(
	params?: ListPostsParams,
	options?: {
		query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData>>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListPostsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listPosts>>> = ({ signal }) =>
		listPosts(params, signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof listPosts>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPostsQueryResult = NonNullable<Awaited<ReturnType<typeof listPosts>>>;
export type ListPostsQueryError = ErrorType<HTTPValidationError>;

/**
 * @summary List Posts Endpoint
 */

export function createListPosts<
	TData = Awaited<ReturnType<typeof listPosts>>,
	TError = ErrorType<HTTPValidationError>
>(
	params?: ListPostsParams,
	options?: {
		query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData>>;
	},
	queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getListPostsQueryOptions(params, options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Get a specific post by ID.
 * @summary Get Post Endpoint
 */
export const getPost = (postId: number, signal?: AbortSignal) => {
	return customInstance<PostPublic>({ url: `/api/posts/${postId}`, method: 'GET', signal });
};

export const getGetPostQueryKey = (postId?: number) => {
	return [`/api/posts/${postId}`] as const;
};

export const getGetPostQueryOptions = <
	TData = Awaited<ReturnType<typeof getPost>>,
	TError = ErrorType<HTTPValidationError>
>(
	postId: number,
	options?: {
		query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getPost>>, TError, TData>>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetPostQueryKey(postId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getPost>>> = ({ signal }) =>
		getPost(postId, signal);

	return { queryKey, queryFn, enabled: !!postId, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof getPost>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostQueryResult = NonNullable<Awaited<ReturnType<typeof getPost>>>;
export type GetPostQueryError = ErrorType<HTTPValidationError>;

/**
 * @summary Get Post Endpoint
 */

export function createGetPost<
	TData = Awaited<ReturnType<typeof getPost>>,
	TError = ErrorType<HTTPValidationError>
>(
	postId: number,
	options?: {
		query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getPost>>, TError, TData>>;
	},
	queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetPostQueryOptions(postId, options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Update a specific post.
 * @summary Update Post Endpoint
 */
export const updatePost = (postId: number, postUpdate: PostUpdate) => {
	return customInstance<PostPublic>({
		url: `/api/posts/${postId}`,
		method: 'PATCH',
		headers: { 'Content-Type': 'application/json' },
		data: postUpdate
	});
};

export const getUpdatePostMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof updatePost>>,
		TError,
		{ postId: number; data: PostUpdate },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof updatePost>>,
	TError,
	{ postId: number; data: PostUpdate },
	TContext
> => {
	const mutationKey = ['updatePost'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updatePost>>,
		{ postId: number; data: PostUpdate }
	> = (props) => {
		const { postId, data } = props ?? {};

		return updatePost(postId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdatePostMutationResult = NonNullable<Awaited<ReturnType<typeof updatePost>>>;
export type UpdatePostMutationBody = PostUpdate;
export type UpdatePostMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Update Post Endpoint
 */
export const createUpdatePost = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof updatePost>>,
			TError,
			{ postId: number; data: PostUpdate },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof updatePost>>,
	TError,
	{ postId: number; data: PostUpdate },
	TContext
> => {
	const mutationOptions = getUpdatePostMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * Delete a specific post.
 * @summary Delete Post Endpoint
 */
export const deletePost = (postId: number) => {
	return customInstance<void>({ url: `/api/posts/${postId}`, method: 'DELETE' });
};

export const getDeletePostMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof deletePost>>,
		TError,
		{ postId: number },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof deletePost>>,
	TError,
	{ postId: number },
	TContext
> => {
	const mutationKey = ['deletePost'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePost>>, { postId: number }> = (
		props
	) => {
		const { postId } = props ?? {};

		return deletePost(postId);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof deletePost>>>;

export type DeletePostMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Delete Post Endpoint
 */
export const createDeletePost = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof deletePost>>,
			TError,
			{ postId: number },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof deletePost>>,
	TError,
	{ postId: number },
	TContext
> => {
	const mutationOptions = getDeletePostMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * Schedule a post for future publishing.
 * @summary Schedule Post Endpoint
 */
export const schedulePost = (
	postId: number,
	schedulePostRequest: SchedulePostRequest,
	signal?: AbortSignal
) => {
	return customInstance<PostPublic>({
		url: `/api/posts/${postId}/schedule`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: schedulePostRequest,
		signal
	});
};

export const getSchedulePostMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof schedulePost>>,
		TError,
		{ postId: number; data: SchedulePostRequest },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof schedulePost>>,
	TError,
	{ postId: number; data: SchedulePostRequest },
	TContext
> => {
	const mutationKey = ['schedulePost'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof schedulePost>>,
		{ postId: number; data: SchedulePostRequest }
	> = (props) => {
		const { postId, data } = props ?? {};

		return schedulePost(postId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SchedulePostMutationResult = NonNullable<Awaited<ReturnType<typeof schedulePost>>>;
export type SchedulePostMutationBody = SchedulePostRequest;
export type SchedulePostMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Schedule Post Endpoint
 */
export const createSchedulePost = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof schedulePost>>,
			TError,
			{ postId: number; data: SchedulePostRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof schedulePost>>,
	TError,
	{ postId: number; data: SchedulePostRequest },
	TContext
> => {
	const mutationOptions = getSchedulePostMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * Cancel a scheduled post.
 * @summary Cancel Schedule Endpoint
 */
export const cancelSchedule = (postId: number, signal?: AbortSignal) => {
	return customInstance<PostPublic>({
		url: `/api/posts/${postId}/cancel-schedule`,
		method: 'POST',
		signal
	});
};

export const getCancelScheduleMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof cancelSchedule>>,
		TError,
		{ postId: number },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof cancelSchedule>>,
	TError,
	{ postId: number },
	TContext
> => {
	const mutationKey = ['cancelSchedule'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof cancelSchedule>>,
		{ postId: number }
	> = (props) => {
		const { postId } = props ?? {};

		return cancelSchedule(postId);
	};

	return { mutationFn, ...mutationOptions };
};

export type CancelScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof cancelSchedule>>>;

export type CancelScheduleMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Cancel Schedule Endpoint
 */
export const createCancelSchedule = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof cancelSchedule>>,
			TError,
			{ postId: number },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof cancelSchedule>>,
	TError,
	{ postId: number },
	TContext
> => {
	const mutationOptions = getCancelScheduleMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * Reschedule a post.
 * @summary Reschedule Post Endpoint
 */
export const reschedulePost = (
	postId: number,
	schedulePostRequest: SchedulePostRequest,
	signal?: AbortSignal
) => {
	return customInstance<PostPublic>({
		url: `/api/posts/${postId}/reschedule`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: schedulePostRequest,
		signal
	});
};

export const getReschedulePostMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof reschedulePost>>,
		TError,
		{ postId: number; data: SchedulePostRequest },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof reschedulePost>>,
	TError,
	{ postId: number; data: SchedulePostRequest },
	TContext
> => {
	const mutationKey = ['reschedulePost'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof reschedulePost>>,
		{ postId: number; data: SchedulePostRequest }
	> = (props) => {
		const { postId, data } = props ?? {};

		return reschedulePost(postId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type ReschedulePostMutationResult = NonNullable<Awaited<ReturnType<typeof reschedulePost>>>;
export type ReschedulePostMutationBody = SchedulePostRequest;
export type ReschedulePostMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Reschedule Post Endpoint
 */
export const createReschedulePost = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof reschedulePost>>,
			TError,
			{ postId: number; data: SchedulePostRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof reschedulePost>>,
	TError,
	{ postId: number; data: SchedulePostRequest },
	TContext
> => {
	const mutationOptions = getReschedulePostMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
