/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * Verify user's email with token.
 * @summary Verify Email
 */
export const VerifyEmailBody = zod
	.object({
		token: zod.string()
	})
	.describe('Schema for confirming email verification.');

export const VerifyEmailResponse = zod
	.object({
		message: zod.string(),
		email: zod.union([zod.string(), zod.null()]).optional()
	})
	.describe('Schema for verification responses.');

/**
 * Request email verification for authenticated user.
 * @summary Request Verification
 */
export const RequestVerificationResponse = zod
	.object({
		message: zod.string(),
		email: zod.union([zod.string(), zod.null()]).optional()
	})
	.describe('Schema for verification responses.');

/**
 * Resend verification email.
 * @summary Resend Verification
 */
export const ResendVerificationBody = zod
	.object({
		email: zod.string().email()
	})
	.describe('Schema for requesting email verification resend.');

export const ResendVerificationResponse = zod
	.object({
		message: zod.string(),
		email: zod.union([zod.string(), zod.null()]).optional()
	})
	.describe('Schema for verification responses.');
