/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * Initiate LinkedIn OAuth flow.
 * @summary Initiate Linkedin Connection
 */
export const InitiateLinkedinConnectionResponse = zod
	.object({
		authorization_url: zod.string(),
		state: zod.string()
	})
	.describe('Response when initiating LinkedIn OAuth flow.');

/**
 * Complete LinkedIn OAuth flow and store connection.
 * @summary Complete Linkedin Connection
 */
export const CompleteLinkedinConnectionBody = zod
	.object({
		code: zod.string(),
		state: zod.string()
	})
	.describe('Request body for OAuth callback.');

export const CompleteLinkedinConnectionResponse = zod
	.object({
		connected: zod.boolean(),
		person_urn: zod.union([zod.string(), zod.null()]).optional(),
		connected_at: zod.union([zod.string(), zod.null()]).optional(),
		expires_at: zod.union([zod.string(), zod.null()]).optional()
	})
	.describe('LinkedIn connection status for a user.');

/**
 * Disconnect LinkedIn account.
 * @summary Disconnect Linkedin Account
 */
export const DisconnectLinkedinResponse = zod
	.object({
		connected: zod.boolean(),
		person_urn: zod.union([zod.string(), zod.null()]).optional(),
		connected_at: zod.union([zod.string(), zod.null()]).optional(),
		expires_at: zod.union([zod.string(), zod.null()]).optional()
	})
	.describe('LinkedIn connection status for a user.');

/**
 * Get current LinkedIn connection status.
 * @summary Get Linkedin Connection Status
 */
export const GetLinkedinStatusResponse = zod
	.object({
		connected: zod.boolean(),
		person_urn: zod.union([zod.string(), zod.null()]).optional(),
		connected_at: zod.union([zod.string(), zod.null()]).optional(),
		expires_at: zod.union([zod.string(), zod.null()]).optional()
	})
	.describe('LinkedIn connection status for a user.');

/**
 * Post content to LinkedIn.
 * @summary Post To Linkedin Endpoint
 */
export const PostToLinkedinBody = zod
	.object({
		post_id: zod.number()
	})
	.describe('Request to post content to LinkedIn.');

export const PostToLinkedinResponse = zod
	.object({
		success: zod.boolean(),
		linkedin_post_id: zod.string()
	})
	.describe('Response after posting to LinkedIn.');
