/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult
} from '@tanstack/react-query';

import type {
	HTTPValidationError,
	LinkedInConnectCallback,
	LinkedInConnectInitiate,
	LinkedInConnectionStatus,
	LinkedInPostRequest,
	LinkedInPostResponse
} from '../superimpress.schemas';

import { customInstance } from '.././axios';
import type { ErrorType } from '.././axios';

/**
 * Initiate LinkedIn OAuth flow.
 * @summary Initiate Linkedin Connection
 */
export const initiateLinkedinConnection = (signal?: AbortSignal) => {
	return customInstance<LinkedInConnectInitiate>({
		url: `/api/linkedin/connect/initiate`,
		method: 'POST',
		signal
	});
};

export const getInitiateLinkedinConnectionMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof initiateLinkedinConnection>>,
		TError,
		void,
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof initiateLinkedinConnection>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ['initiateLinkedinConnection'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof initiateLinkedinConnection>>,
		void
	> = () => {
		return initiateLinkedinConnection();
	};

	return { mutationFn, ...mutationOptions };
};

export type InitiateLinkedinConnectionMutationResult = NonNullable<
	Awaited<ReturnType<typeof initiateLinkedinConnection>>
>;

export type InitiateLinkedinConnectionMutationError = ErrorType<unknown>;

/**
 * @summary Initiate Linkedin Connection
 */
export const useInitiateLinkedinConnection = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof initiateLinkedinConnection>>,
			TError,
			void,
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof initiateLinkedinConnection>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getInitiateLinkedinConnectionMutationOptions(options), queryClient);
};
/**
 * Complete LinkedIn OAuth flow and store connection.
 * @summary Complete Linkedin Connection
 */
export const completeLinkedinConnection = (
	linkedInConnectCallback: LinkedInConnectCallback,
	signal?: AbortSignal
) => {
	return customInstance<LinkedInConnectionStatus>({
		url: `/api/linkedin/connect/callback`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: linkedInConnectCallback,
		signal
	});
};

export const getCompleteLinkedinConnectionMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof completeLinkedinConnection>>,
		TError,
		{ data: LinkedInConnectCallback },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof completeLinkedinConnection>>,
	TError,
	{ data: LinkedInConnectCallback },
	TContext
> => {
	const mutationKey = ['completeLinkedinConnection'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof completeLinkedinConnection>>,
		{ data: LinkedInConnectCallback }
	> = (props) => {
		const { data } = props ?? {};

		return completeLinkedinConnection(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CompleteLinkedinConnectionMutationResult = NonNullable<
	Awaited<ReturnType<typeof completeLinkedinConnection>>
>;
export type CompleteLinkedinConnectionMutationBody = LinkedInConnectCallback;
export type CompleteLinkedinConnectionMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Complete Linkedin Connection
 */
export const useCompleteLinkedinConnection = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof completeLinkedinConnection>>,
			TError,
			{ data: LinkedInConnectCallback },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof completeLinkedinConnection>>,
	TError,
	{ data: LinkedInConnectCallback },
	TContext
> => {
	return useMutation(getCompleteLinkedinConnectionMutationOptions(options), queryClient);
};
/**
 * Disconnect LinkedIn account.
 * @summary Disconnect Linkedin Account
 */
export const disconnectLinkedin = (signal?: AbortSignal) => {
	return customInstance<LinkedInConnectionStatus>({
		url: `/api/linkedin/disconnect`,
		method: 'POST',
		signal
	});
};

export const getDisconnectLinkedinMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof disconnectLinkedin>>,
		TError,
		void,
		TContext
	>;
}): UseMutationOptions<Awaited<ReturnType<typeof disconnectLinkedin>>, TError, void, TContext> => {
	const mutationKey = ['disconnectLinkedin'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof disconnectLinkedin>>, void> = () => {
		return disconnectLinkedin();
	};

	return { mutationFn, ...mutationOptions };
};

export type DisconnectLinkedinMutationResult = NonNullable<
	Awaited<ReturnType<typeof disconnectLinkedin>>
>;

export type DisconnectLinkedinMutationError = ErrorType<unknown>;

/**
 * @summary Disconnect Linkedin Account
 */
export const useDisconnectLinkedin = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof disconnectLinkedin>>,
			TError,
			void,
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof disconnectLinkedin>>, TError, void, TContext> => {
	return useMutation(getDisconnectLinkedinMutationOptions(options), queryClient);
};
/**
 * Get current LinkedIn connection status.
 * @summary Get Linkedin Connection Status
 */
export const getLinkedinStatus = (signal?: AbortSignal) => {
	return customInstance<LinkedInConnectionStatus>({
		url: `/api/linkedin/status`,
		method: 'GET',
		signal
	});
};

export const getGetLinkedinStatusQueryKey = () => {
	return [`/api/linkedin/status`] as const;
};

export const getGetLinkedinStatusQueryOptions = <
	TData = Awaited<ReturnType<typeof getLinkedinStatus>>,
	TError = ErrorType<unknown>
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLinkedinStatus>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetLinkedinStatusQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getLinkedinStatus>>> = ({ signal }) =>
		getLinkedinStatus(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getLinkedinStatus>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLinkedinStatusQueryResult = NonNullable<
	Awaited<ReturnType<typeof getLinkedinStatus>>
>;
export type GetLinkedinStatusQueryError = ErrorType<unknown>;

export function useGetLinkedinStatus<
	TData = Awaited<ReturnType<typeof getLinkedinStatus>>,
	TError = ErrorType<unknown>
>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLinkedinStatus>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getLinkedinStatus>>,
					TError,
					Awaited<ReturnType<typeof getLinkedinStatus>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLinkedinStatus<
	TData = Awaited<ReturnType<typeof getLinkedinStatus>>,
	TError = ErrorType<unknown>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLinkedinStatus>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getLinkedinStatus>>,
					TError,
					Awaited<ReturnType<typeof getLinkedinStatus>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLinkedinStatus<
	TData = Awaited<ReturnType<typeof getLinkedinStatus>>,
	TError = ErrorType<unknown>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLinkedinStatus>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Linkedin Connection Status
 */

export function useGetLinkedinStatus<
	TData = Awaited<ReturnType<typeof getLinkedinStatus>>,
	TError = ErrorType<unknown>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLinkedinStatus>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetLinkedinStatusQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Post content to LinkedIn.
 * @summary Post To Linkedin Endpoint
 */
export const postToLinkedin = (linkedInPostRequest: LinkedInPostRequest, signal?: AbortSignal) => {
	return customInstance<LinkedInPostResponse>({
		url: `/api/linkedin/post`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: linkedInPostRequest,
		signal
	});
};

export const getPostToLinkedinMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postToLinkedin>>,
		TError,
		{ data: LinkedInPostRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postToLinkedin>>,
	TError,
	{ data: LinkedInPostRequest },
	TContext
> => {
	const mutationKey = ['postToLinkedin'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postToLinkedin>>,
		{ data: LinkedInPostRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postToLinkedin(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostToLinkedinMutationResult = NonNullable<Awaited<ReturnType<typeof postToLinkedin>>>;
export type PostToLinkedinMutationBody = LinkedInPostRequest;
export type PostToLinkedinMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Post To Linkedin Endpoint
 */
export const usePostToLinkedin = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postToLinkedin>>,
			TError,
			{ data: LinkedInPostRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof postToLinkedin>>,
	TError,
	{ data: LinkedInPostRequest },
	TContext
> => {
	return useMutation(getPostToLinkedinMutationOptions(options), queryClient);
};
