/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * SuperImpress API
 * LinkedIn post management tool API
 * OpenAPI spec version: 1.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { ErrorType } from ".././axios";

import { customInstance } from ".././axios";
import type {
  GetApiLinkedinStatusResponse200,
  PostApiLinkedinPostRequest,
  PostApiLinkedinPostResponse200,
  PostApiLinkedinPostResponse400,
  PostApiLinkedinPostWithFormDataBodyThree,
  PostApiLinkedinPostWithUrlEncodedBodyTwo,
} from "../superimpress.schemas";

/**
 * Check if the authenticated user has a LinkedIn account connected
 * @summary Check LinkedIn connection status
 */
export const getApiLinkedinStatus = (signal?: AbortSignal) => {
  return customInstance<GetApiLinkedinStatusResponse200>({
    url: `/api/linkedin/status`,
    method: "GET",
    signal,
  });
};

export const getGetApiLinkedinStatusQueryKey = () => {
  return [`/api/linkedin/status`] as const;
};

export const getGetApiLinkedinStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiLinkedinStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiLinkedinStatus>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiLinkedinStatusQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiLinkedinStatus>>
  > = ({ signal }) => getApiLinkedinStatus(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiLinkedinStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiLinkedinStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiLinkedinStatus>>
>;
export type GetApiLinkedinStatusQueryError = ErrorType<unknown>;

export function useGetApiLinkedinStatus<
  TData = Awaited<ReturnType<typeof getApiLinkedinStatus>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLinkedinStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLinkedinStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiLinkedinStatus>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLinkedinStatus<
  TData = Awaited<ReturnType<typeof getApiLinkedinStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLinkedinStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLinkedinStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiLinkedinStatus>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLinkedinStatus<
  TData = Awaited<ReturnType<typeof getApiLinkedinStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLinkedinStatus>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Check LinkedIn connection status
 */

export function useGetApiLinkedinStatus<
  TData = Awaited<ReturnType<typeof getApiLinkedinStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLinkedinStatus>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiLinkedinStatusQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Publish a post to the authenticated user's LinkedIn account
 * @summary Publish post to LinkedIn
 */
export const postApiLinkedinPostWithJson = (
  postApiLinkedinPostRequest: PostApiLinkedinPostRequest,
  signal?: AbortSignal
) => {
  return customInstance<PostApiLinkedinPostResponse200>({
    url: `/api/linkedin/post`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postApiLinkedinPostRequest,
    signal,
  });
};

export const getPostApiLinkedinPostWithJsonMutationOptions = <
  TError = ErrorType<PostApiLinkedinPostResponse400>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiLinkedinPostWithJson>>,
    TError,
    { data: PostApiLinkedinPostRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiLinkedinPostWithJson>>,
  TError,
  { data: PostApiLinkedinPostRequest },
  TContext
> => {
  const mutationKey = ["postApiLinkedinPostWithJson"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiLinkedinPostWithJson>>,
    { data: PostApiLinkedinPostRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiLinkedinPostWithJson(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiLinkedinPostWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiLinkedinPostWithJson>>
>;
export type PostApiLinkedinPostWithJsonMutationBody =
  PostApiLinkedinPostRequest;
export type PostApiLinkedinPostWithJsonMutationError =
  ErrorType<PostApiLinkedinPostResponse400>;

/**
 * @summary Publish post to LinkedIn
 */
export const usePostApiLinkedinPostWithJson = <
  TError = ErrorType<PostApiLinkedinPostResponse400>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiLinkedinPostWithJson>>,
      TError,
      { data: PostApiLinkedinPostRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiLinkedinPostWithJson>>,
  TError,
  { data: PostApiLinkedinPostRequest },
  TContext
> => {
  return useMutation(
    getPostApiLinkedinPostWithJsonMutationOptions(options),
    queryClient
  );
};
/**
 * Publish a post to the authenticated user's LinkedIn account
 * @summary Publish post to LinkedIn
 */
export const postApiLinkedinPostWithUrlEncoded = (
  postApiLinkedinPostWithUrlEncodedBodyTwo: PostApiLinkedinPostWithUrlEncodedBodyTwo,
  signal?: AbortSignal
) => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(
    `postId`,
    postApiLinkedinPostWithUrlEncodedBodyTwo.postId
  );

  return customInstance<PostApiLinkedinPostResponse200>({
    url: `/api/linkedin/post`,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    data: formUrlEncoded,
    signal,
  });
};

export const getPostApiLinkedinPostWithUrlEncodedMutationOptions = <
  TError = ErrorType<PostApiLinkedinPostResponse400>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiLinkedinPostWithUrlEncoded>>,
    TError,
    { data: PostApiLinkedinPostWithUrlEncodedBodyTwo },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiLinkedinPostWithUrlEncoded>>,
  TError,
  { data: PostApiLinkedinPostWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ["postApiLinkedinPostWithUrlEncoded"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiLinkedinPostWithUrlEncoded>>,
    { data: PostApiLinkedinPostWithUrlEncodedBodyTwo }
  > = (props) => {
    const { data } = props ?? {};

    return postApiLinkedinPostWithUrlEncoded(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiLinkedinPostWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiLinkedinPostWithUrlEncoded>>
>;
export type PostApiLinkedinPostWithUrlEncodedMutationBody =
  PostApiLinkedinPostWithUrlEncodedBodyTwo;
export type PostApiLinkedinPostWithUrlEncodedMutationError =
  ErrorType<PostApiLinkedinPostResponse400>;

/**
 * @summary Publish post to LinkedIn
 */
export const usePostApiLinkedinPostWithUrlEncoded = <
  TError = ErrorType<PostApiLinkedinPostResponse400>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiLinkedinPostWithUrlEncoded>>,
      TError,
      { data: PostApiLinkedinPostWithUrlEncodedBodyTwo },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiLinkedinPostWithUrlEncoded>>,
  TError,
  { data: PostApiLinkedinPostWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPostApiLinkedinPostWithUrlEncodedMutationOptions(options),
    queryClient
  );
};
/**
 * Publish a post to the authenticated user's LinkedIn account
 * @summary Publish post to LinkedIn
 */
export const postApiLinkedinPostWithFormData = (
  postApiLinkedinPostWithFormDataBodyThree: PostApiLinkedinPostWithFormDataBodyThree,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  formData.append(`postId`, postApiLinkedinPostWithFormDataBodyThree.postId);

  return customInstance<PostApiLinkedinPostResponse200>({
    url: `/api/linkedin/post`,
    method: "POST",
    data: formData,
    signal,
  });
};

export const getPostApiLinkedinPostWithFormDataMutationOptions = <
  TError = ErrorType<PostApiLinkedinPostResponse400>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiLinkedinPostWithFormData>>,
    TError,
    { data: PostApiLinkedinPostWithFormDataBodyThree },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiLinkedinPostWithFormData>>,
  TError,
  { data: PostApiLinkedinPostWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ["postApiLinkedinPostWithFormData"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiLinkedinPostWithFormData>>,
    { data: PostApiLinkedinPostWithFormDataBodyThree }
  > = (props) => {
    const { data } = props ?? {};

    return postApiLinkedinPostWithFormData(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiLinkedinPostWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiLinkedinPostWithFormData>>
>;
export type PostApiLinkedinPostWithFormDataMutationBody =
  PostApiLinkedinPostWithFormDataBodyThree;
export type PostApiLinkedinPostWithFormDataMutationError =
  ErrorType<PostApiLinkedinPostResponse400>;

/**
 * @summary Publish post to LinkedIn
 */
export const usePostApiLinkedinPostWithFormData = <
  TError = ErrorType<PostApiLinkedinPostResponse400>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiLinkedinPostWithFormData>>,
      TError,
      { data: PostApiLinkedinPostWithFormDataBodyThree },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiLinkedinPostWithFormData>>,
  TError,
  { data: PostApiLinkedinPostWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPostApiLinkedinPostWithFormDataMutationOptions(options),
    queryClient
  );
};
