/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * SuperImpress API
 * LinkedIn post management tool API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * Check if the authenticated user has a LinkedIn account connected
 * @summary Check LinkedIn connection status
 */
export const GetApiLinkedinStatusResponse = zod.object({
  connected: zod.boolean(),
  accountId: zod.string().optional(),
  email: zod.string().optional(),
});

/**
 * Publish a post to the authenticated user's LinkedIn account
 * @summary Publish post to LinkedIn
 */
export const PostApiLinkedinPostWithJsonBody = zod.object({
  postId: zod.string(),
});

export const PostApiLinkedinPostWithJsonResponse = zod.object({
  success: zod.boolean(),
  linkedInPostId: zod.string().optional(),
  message: zod.string().optional(),
});

/**
 * Publish a post to the authenticated user's LinkedIn account
 * @summary Publish post to LinkedIn
 */
export const PostApiLinkedinPostWithUrlEncodedBody = zod.object({
  postId: zod.string(),
});

export const PostApiLinkedinPostWithUrlEncodedResponse = zod.object({
  success: zod.boolean(),
  linkedInPostId: zod.string().optional(),
  message: zod.string().optional(),
});

/**
 * Publish a post to the authenticated user's LinkedIn account
 * @summary Publish post to LinkedIn
 */
export const PostApiLinkedinPostWithFormDataBody = zod.object({
  postId: zod.string(),
});

export const PostApiLinkedinPostWithFormDataResponse = zod.object({
  success: zod.boolean(),
  linkedInPostId: zod.string().optional(),
  message: zod.string().optional(),
});
