/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import { createMutation, createQuery } from '@tanstack/svelte-query';
import type {
	CreateMutationOptions,
	CreateMutationResult,
	CreateQueryOptions,
	CreateQueryResult,
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey
} from '@tanstack/svelte-query';

import type {
	HTTPValidationError,
	LinkedInConnectCallback,
	LinkedInConnectInitiate,
	LinkedInConnectionStatus,
	LinkedInPostRequest,
	LinkedInPostResponse
} from '../superimpress.schemas';

import { customInstance } from '.././axios';
import type { ErrorType } from '.././axios';

/**
 * Initiate LinkedIn OAuth flow.
 * @summary Initiate Linkedin Connection
 */
export const initiateLinkedinConnection = (signal?: AbortSignal) => {
	return customInstance<LinkedInConnectInitiate>({
		url: `/api/linkedin/connect/initiate`,
		method: 'POST',
		signal
	});
};

export const getInitiateLinkedinConnectionMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof initiateLinkedinConnection>>,
		TError,
		void,
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof initiateLinkedinConnection>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ['initiateLinkedinConnection'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof initiateLinkedinConnection>>,
		void
	> = () => {
		return initiateLinkedinConnection();
	};

	return { mutationFn, ...mutationOptions };
};

export type InitiateLinkedinConnectionMutationResult = NonNullable<
	Awaited<ReturnType<typeof initiateLinkedinConnection>>
>;

export type InitiateLinkedinConnectionMutationError = ErrorType<unknown>;

/**
 * @summary Initiate Linkedin Connection
 */
export const createInitiateLinkedinConnection = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof initiateLinkedinConnection>>,
			TError,
			void,
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof initiateLinkedinConnection>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getInitiateLinkedinConnectionMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * Complete LinkedIn OAuth flow and store connection.
 * @summary Complete Linkedin Connection
 */
export const completeLinkedinConnection = (
	linkedInConnectCallback: LinkedInConnectCallback,
	signal?: AbortSignal
) => {
	return customInstance<LinkedInConnectionStatus>({
		url: `/api/linkedin/connect/callback`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: linkedInConnectCallback,
		signal
	});
};

export const getCompleteLinkedinConnectionMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof completeLinkedinConnection>>,
		TError,
		{ data: LinkedInConnectCallback },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof completeLinkedinConnection>>,
	TError,
	{ data: LinkedInConnectCallback },
	TContext
> => {
	const mutationKey = ['completeLinkedinConnection'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof completeLinkedinConnection>>,
		{ data: LinkedInConnectCallback }
	> = (props) => {
		const { data } = props ?? {};

		return completeLinkedinConnection(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CompleteLinkedinConnectionMutationResult = NonNullable<
	Awaited<ReturnType<typeof completeLinkedinConnection>>
>;
export type CompleteLinkedinConnectionMutationBody = LinkedInConnectCallback;
export type CompleteLinkedinConnectionMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Complete Linkedin Connection
 */
export const createCompleteLinkedinConnection = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof completeLinkedinConnection>>,
			TError,
			{ data: LinkedInConnectCallback },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof completeLinkedinConnection>>,
	TError,
	{ data: LinkedInConnectCallback },
	TContext
> => {
	const mutationOptions = getCompleteLinkedinConnectionMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * Disconnect LinkedIn account.
 * @summary Disconnect Linkedin Account
 */
export const disconnectLinkedin = (signal?: AbortSignal) => {
	return customInstance<LinkedInConnectionStatus>({
		url: `/api/linkedin/disconnect`,
		method: 'POST',
		signal
	});
};

export const getDisconnectLinkedinMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof disconnectLinkedin>>,
		TError,
		void,
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof disconnectLinkedin>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ['disconnectLinkedin'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof disconnectLinkedin>>, void> = () => {
		return disconnectLinkedin();
	};

	return { mutationFn, ...mutationOptions };
};

export type DisconnectLinkedinMutationResult = NonNullable<
	Awaited<ReturnType<typeof disconnectLinkedin>>
>;

export type DisconnectLinkedinMutationError = ErrorType<unknown>;

/**
 * @summary Disconnect Linkedin Account
 */
export const createDisconnectLinkedin = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof disconnectLinkedin>>,
			TError,
			void,
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof disconnectLinkedin>>, TError, void, TContext> => {
	const mutationOptions = getDisconnectLinkedinMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * Get current LinkedIn connection status.
 * @summary Get Linkedin Connection Status
 */
export const getLinkedinStatus = (signal?: AbortSignal) => {
	return customInstance<LinkedInConnectionStatus>({
		url: `/api/linkedin/status`,
		method: 'GET',
		signal
	});
};

export const getGetLinkedinStatusQueryKey = () => {
	return [`/api/linkedin/status`] as const;
};

export const getGetLinkedinStatusQueryOptions = <
	TData = Awaited<ReturnType<typeof getLinkedinStatus>>,
	TError = ErrorType<unknown>
>(options?: {
	query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getLinkedinStatus>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetLinkedinStatusQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getLinkedinStatus>>> = ({ signal }) =>
		getLinkedinStatus(signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof getLinkedinStatus>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLinkedinStatusQueryResult = NonNullable<
	Awaited<ReturnType<typeof getLinkedinStatus>>
>;
export type GetLinkedinStatusQueryError = ErrorType<unknown>;

/**
 * @summary Get Linkedin Connection Status
 */

export function createGetLinkedinStatus<
	TData = Awaited<ReturnType<typeof getLinkedinStatus>>,
	TError = ErrorType<unknown>
>(
	options?: {
		query?: Partial<
			CreateQueryOptions<Awaited<ReturnType<typeof getLinkedinStatus>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetLinkedinStatusQueryOptions(options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Post content to LinkedIn.
 * @summary Post To Linkedin Endpoint
 */
export const postToLinkedin = (linkedInPostRequest: LinkedInPostRequest, signal?: AbortSignal) => {
	return customInstance<LinkedInPostResponse>({
		url: `/api/linkedin/post`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: linkedInPostRequest,
		signal
	});
};

export const getPostToLinkedinMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof postToLinkedin>>,
		TError,
		{ data: LinkedInPostRequest },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof postToLinkedin>>,
	TError,
	{ data: LinkedInPostRequest },
	TContext
> => {
	const mutationKey = ['postToLinkedin'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postToLinkedin>>,
		{ data: LinkedInPostRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postToLinkedin(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostToLinkedinMutationResult = NonNullable<Awaited<ReturnType<typeof postToLinkedin>>>;
export type PostToLinkedinMutationBody = LinkedInPostRequest;
export type PostToLinkedinMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Post To Linkedin Endpoint
 */
export const createPostToLinkedin = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof postToLinkedin>>,
			TError,
			{ data: LinkedInPostRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof postToLinkedin>>,
	TError,
	{ data: LinkedInPostRequest },
	TContext
> => {
	const mutationOptions = getPostToLinkedinMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
