/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedAppRouteImport } from './routes/_protected/_app'
import { Route as ProtectedAppIndexRouteImport } from './routes/_protected/_app/index'
import { Route as ProtectedAppPostsNewRouteImport } from './routes/_protected/_app/posts/new'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppRoute = ProtectedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppIndexRoute = ProtectedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAppRoute,
} as any)
const ProtectedAppPostsNewRoute = ProtectedAppPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => ProtectedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedAppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/posts/new': typeof ProtectedAppPostsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedAppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/posts/new': typeof ProtectedAppPostsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/_app': typeof ProtectedAppRouteWithChildren
  '/_protected/_app/': typeof ProtectedAppIndexRoute
  '/_protected/_app/posts/new': typeof ProtectedAppPostsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/posts/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/posts/new'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/register'
    | '/_protected/_app'
    | '/_protected/_app/'
    | '/_protected/_app/posts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_app': {
      id: '/_protected/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAppRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_app/': {
      id: '/_protected/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAppIndexRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
    '/_protected/_app/posts/new': {
      id: '/_protected/_app/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof ProtectedAppPostsNewRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
  }
}

interface ProtectedAppRouteChildren {
  ProtectedAppIndexRoute: typeof ProtectedAppIndexRoute
  ProtectedAppPostsNewRoute: typeof ProtectedAppPostsNewRoute
}

const ProtectedAppRouteChildren: ProtectedAppRouteChildren = {
  ProtectedAppIndexRoute: ProtectedAppIndexRoute,
  ProtectedAppPostsNewRoute: ProtectedAppPostsNewRoute,
}

const ProtectedAppRouteWithChildren = ProtectedAppRoute._addFileChildren(
  ProtectedAppRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAppRoute: typeof ProtectedAppRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppRoute: ProtectedAppRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
