/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Root
 */
export const RootApiTestGetResponse = zod.unknown();
