/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import { createQuery } from '@tanstack/svelte-query';
import type {
	CreateQueryOptions,
	CreateQueryResult,
	QueryFunction,
	QueryKey
} from '@tanstack/svelte-query';

import { customInstance } from '.././axios';
import type { ErrorType } from '.././axios';

/**
 * @summary Root
 */
export const rootApiTestGet = (signal?: AbortSignal) => {
	return customInstance<unknown>({ url: `/api/test`, method: 'GET', signal });
};

export const getRootApiTestGetQueryKey = () => {
	return [`/api/test`] as const;
};

export const getRootApiTestGetQueryOptions = <
	TData = Awaited<ReturnType<typeof rootApiTestGet>>,
	TError = ErrorType<unknown>
>(options?: {
	query?: CreateQueryOptions<Awaited<ReturnType<typeof rootApiTestGet>>, TError, TData>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRootApiTestGetQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof rootApiTestGet>>> = ({ signal }) =>
		rootApiTestGet(signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof rootApiTestGet>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type RootApiTestGetQueryResult = NonNullable<Awaited<ReturnType<typeof rootApiTestGet>>>;
export type RootApiTestGetQueryError = ErrorType<unknown>;

/**
 * @summary Root
 */

export function createRootApiTestGet<
	TData = Awaited<ReturnType<typeof rootApiTestGet>>,
	TError = ErrorType<unknown>
>(options?: {
	query?: CreateQueryOptions<Awaited<ReturnType<typeof rootApiTestGet>>, TError, TData>;
}): CreateQueryResult<TData, TError> & { queryKey: QueryKey } {
	const queryOptions = getRootApiTestGetQueryOptions(options);

	const query = createQuery(queryOptions) as CreateQueryResult<TData, TError> & {
		queryKey: QueryKey;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}
