/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '.././axios';
import type { ErrorType } from '.././axios';

/**
 * @summary Root
 */
export const rootApiTestGet = (signal?: AbortSignal) => {
	return customInstance<unknown>({ url: `/api/test`, method: 'GET', signal });
};

export const getRootApiTestGetQueryKey = () => {
	return [`/api/test`] as const;
};

export const getRootApiTestGetQueryOptions = <
	TData = Awaited<ReturnType<typeof rootApiTestGet>>,
	TError = ErrorType<unknown>
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof rootApiTestGet>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRootApiTestGetQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof rootApiTestGet>>> = ({ signal }) =>
		rootApiTestGet(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof rootApiTestGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RootApiTestGetQueryResult = NonNullable<Awaited<ReturnType<typeof rootApiTestGet>>>;
export type RootApiTestGetQueryError = ErrorType<unknown>;

export function useRootApiTestGet<
	TData = Awaited<ReturnType<typeof rootApiTestGet>>,
	TError = ErrorType<unknown>
>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof rootApiTestGet>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof rootApiTestGet>>,
					TError,
					Awaited<ReturnType<typeof rootApiTestGet>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRootApiTestGet<
	TData = Awaited<ReturnType<typeof rootApiTestGet>>,
	TError = ErrorType<unknown>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof rootApiTestGet>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof rootApiTestGet>>,
					TError,
					Awaited<ReturnType<typeof rootApiTestGet>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRootApiTestGet<
	TData = Awaited<ReturnType<typeof rootApiTestGet>>,
	TError = ErrorType<unknown>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof rootApiTestGet>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Root
 */

export function useRootApiTestGet<
	TData = Awaited<ReturnType<typeof rootApiTestGet>>,
	TError = ErrorType<unknown>
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof rootApiTestGet>>, TError, TData>>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getRootApiTestGetQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}
