/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import { createMutation, createQuery } from '@tanstack/svelte-query';
import type {
	CreateMutationOptions,
	CreateMutationResult,
	CreateQueryOptions,
	CreateQueryResult,
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey
} from '@tanstack/svelte-query';

import type {
	BodyLoginUser,
	HTTPValidationError,
	PasswordChange,
	Token,
	UserCreate,
	UserPublic
} from '../superimpress.schemas';

import { customInstance } from '.././axios';
import type { ErrorType } from '.././axios';

/**
 * @summary Register User
 */
export const registerUser = (userCreate: UserCreate, signal?: AbortSignal) => {
	return customInstance<UserPublic>({
		url: `/api/register`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: userCreate,
		signal
	});
};

export const getRegisterUserMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof registerUser>>,
		TError,
		{ data: UserCreate },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof registerUser>>,
	TError,
	{ data: UserCreate },
	TContext
> => {
	const mutationKey = ['registerUser'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof registerUser>>,
		{ data: UserCreate }
	> = (props) => {
		const { data } = props ?? {};

		return registerUser(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>;
export type RegisterUserMutationBody = UserCreate;
export type RegisterUserMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Register User
 */
export const createRegisterUser = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof registerUser>>,
			TError,
			{ data: UserCreate },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof registerUser>>,
	TError,
	{ data: UserCreate },
	TContext
> => {
	const mutationOptions = getRegisterUserMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * @summary Login User
 */
export const loginUser = (bodyLoginUser: BodyLoginUser, signal?: AbortSignal) => {
	const formUrlEncoded = new URLSearchParams();
	if (bodyLoginUser.grant_type !== undefined && bodyLoginUser.grant_type !== null) {
		formUrlEncoded.append(`grant_type`, bodyLoginUser.grant_type);
	}
	formUrlEncoded.append(`username`, bodyLoginUser.username);
	formUrlEncoded.append(`password`, bodyLoginUser.password);
	if (bodyLoginUser.scope !== undefined) {
		formUrlEncoded.append(`scope`, bodyLoginUser.scope);
	}
	if (bodyLoginUser.client_id !== undefined && bodyLoginUser.client_id !== null) {
		formUrlEncoded.append(`client_id`, bodyLoginUser.client_id);
	}
	if (bodyLoginUser.client_secret !== undefined && bodyLoginUser.client_secret !== null) {
		formUrlEncoded.append(`client_secret`, bodyLoginUser.client_secret);
	}

	return customInstance<Token>({
		url: `/api/login`,
		method: 'POST',
		headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
		data: formUrlEncoded,
		signal
	});
};

export const getLoginUserMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof loginUser>>,
		TError,
		{ data: BodyLoginUser },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof loginUser>>,
	TError,
	{ data: BodyLoginUser },
	TContext
> => {
	const mutationKey = ['loginUser'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof loginUser>>,
		{ data: BodyLoginUser }
	> = (props) => {
		const { data } = props ?? {};

		return loginUser(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>;
export type LoginUserMutationBody = BodyLoginUser;
export type LoginUserMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Login User
 */
export const createLoginUser = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof loginUser>>,
			TError,
			{ data: BodyLoginUser },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof loginUser>>,
	TError,
	{ data: BodyLoginUser },
	TContext
> => {
	const mutationOptions = getLoginUserMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * @summary Read Current User
 */
export const readCurrentUser = (signal?: AbortSignal) => {
	return customInstance<UserPublic>({ url: `/api/users/me/`, method: 'GET', signal });
};

export const getReadCurrentUserQueryKey = () => {
	return [`/api/users/me/`] as const;
};

export const getReadCurrentUserQueryOptions = <
	TData = Awaited<ReturnType<typeof readCurrentUser>>,
	TError = ErrorType<unknown>
>(options?: {
	query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof readCurrentUser>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getReadCurrentUserQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof readCurrentUser>>> = ({ signal }) =>
		readCurrentUser(signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof readCurrentUser>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ReadCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof readCurrentUser>>>;
export type ReadCurrentUserQueryError = ErrorType<unknown>;

/**
 * @summary Read Current User
 */

export function createReadCurrentUser<
	TData = Awaited<ReturnType<typeof readCurrentUser>>,
	TError = ErrorType<unknown>
>(
	options?: {
		query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof readCurrentUser>>, TError, TData>>;
	},
	queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getReadCurrentUserQueryOptions(options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Change Password
 */
export const changePassword = (passwordChange: PasswordChange, signal?: AbortSignal) => {
	return customInstance<unknown>({
		url: `/api/change-password`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: passwordChange,
		signal
	});
};

export const getChangePasswordMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof changePassword>>,
		TError,
		{ data: PasswordChange },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof changePassword>>,
	TError,
	{ data: PasswordChange },
	TContext
> => {
	const mutationKey = ['changePassword'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof changePassword>>,
		{ data: PasswordChange }
	> = (props) => {
		const { data } = props ?? {};

		return changePassword(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>;
export type ChangePasswordMutationBody = PasswordChange;
export type ChangePasswordMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Change Password
 */
export const createChangePassword = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof changePassword>>,
			TError,
			{ data: PasswordChange },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof changePassword>>,
	TError,
	{ data: PasswordChange },
	TContext
> => {
	const mutationOptions = getChangePasswordMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * Delete the current user's account and all associated data.
 * @summary Delete Current User
 */
export const deleteCurrentUser = () => {
	return customInstance<unknown>({ url: `/api/users/me`, method: 'DELETE' });
};

export const getDeleteCurrentUserMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof deleteCurrentUser>>,
		TError,
		void,
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof deleteCurrentUser>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ['deleteCurrentUser'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCurrentUser>>, void> = () => {
		return deleteCurrentUser();
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteCurrentUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteCurrentUser>>
>;

export type DeleteCurrentUserMutationError = ErrorType<unknown>;

/**
 * @summary Delete Current User
 */
export const createDeleteCurrentUser = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof deleteCurrentUser>>,
			TError,
			void,
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof deleteCurrentUser>>, TError, void, TContext> => {
	const mutationOptions = getDeleteCurrentUserMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
