"""Add cascade delete to posts

Revision ID: 0756c72f69ea
Revises: a42ee80015d1
Create Date: 2026-01-05 23:20:44.276926

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0756c72f69ea"
down_revision: Union[str, Sequence[str], None] = "a42ee80015d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("post_user_id_fkey"), "post", type_="foreignkey")
    op.create_foreign_key(None, "post", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "post", type_="foreignkey")
    op.create_foreign_key(
        op.f("post_user_id_fkey"), "post", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
