"""replace linkedin refresh token with access token

Revision ID: 9420f5168691
Revises: 3524ea2b729e
Create Date: 2025-12-30 11:58:13.199965

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9420f5168691"
down_revision: Union[str, Sequence[str], None] = "3524ea2b729e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("linkedin_access_token", sa.String(), nullable=True)
    )
    op.add_column(
        "user",
        sa.Column("linkedin_access_token_expires_at", sa.DateTime(), nullable=True),
    )
    op.drop_column("user", "linkedin_refresh_token_expires_at")
    op.drop_column("user", "linkedin_refresh_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "linkedin_refresh_token", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "linkedin_refresh_token_expires_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user", "linkedin_access_token_expires_at")
    op.drop_column("user", "linkedin_access_token")
    # ### end Alembic commands ###
