"""Add email verification fields

Revision ID: 94740395d249
Revises: ee3dec5a0673
Create Date: 2025-12-14 12:06:52.699968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94740395d249"
down_revision: Union[str, Sequence[str], None] = "ee3dec5a0673"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email_verified", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("verification_token", sa.String(), nullable=True))
    op.add_column(
        "user", sa.Column("verification_token_expires_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("verification_sent_at", sa.DateTime(), nullable=True)
    )
    op.add_column("user", sa.Column("verified_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_user_verification_token"), "user", ["verification_token"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_verification_token"), table_name="user")
    op.drop_column("user", "verified_at")
    op.drop_column("user", "verification_sent_at")
    op.drop_column("user", "verification_token_expires_at")
    op.drop_column("user", "verification_token")
    op.drop_column("user", "email_verified")
    # ### end Alembic commands ###
