"""create social connections and remove linkedin fields

Revision ID: 9e37f1f5cdbd
Revises: 9420f5168691
Create Date: 2025-12-30 21:01:00.567687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9e37f1f5cdbd"
down_revision: Union[str, Sequence[str], None] = "9420f5168691"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_connection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("platform_user_id", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.Column("access_token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("connected_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("platform_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "platform", "platform_user_id", name="uq_user_platform_account"
        ),
    )
    op.create_index(
        op.f("ix_social_connection_platform"),
        "social_connection",
        ["platform"],
        unique=False,
    )
    op.create_index(
        op.f("ix_social_connection_user_id"),
        "social_connection",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_platform", "social_connection", ["user_id", "platform"], unique=False
    )
    op.drop_constraint(op.f("user_linkedin_person_urn_key"), "user", type_="unique")
    op.drop_column("user", "linkedin_connected_at")
    op.drop_column("user", "linkedin_access_token")
    op.drop_column("user", "linkedin_access_token_expires_at")
    op.drop_column("user", "linkedin_person_urn")
    op.drop_column("user", "linkedin_connected")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "linkedin_connected", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "linkedin_person_urn", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "linkedin_access_token_expires_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "linkedin_access_token", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "linkedin_connected_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_unique_constraint(
        op.f("user_linkedin_person_urn_key"),
        "user",
        ["linkedin_person_urn"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index("ix_user_platform", table_name="social_connection")
    op.drop_index(op.f("ix_social_connection_user_id"), table_name="social_connection")
    op.drop_index(op.f("ix_social_connection_platform"), table_name="social_connection")
    op.drop_table("social_connection")
    # ### end Alembic commands ###
