"""add post scheduling support

Revision ID: d09a6d64a682
Revises: 4a3aea050616
Create Date: 2026-01-07 19:26:33.274778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d09a6d64a682"
down_revision: Union[str, Sequence[str], None] = "4a3aea050616"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post", sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("post", sa.Column("reason_failed", sa.Text(), nullable=True))
    op.add_column(
        "post", sa.Column("linkedin_post_id", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_post_scheduled_for"), "post", ["scheduled_for"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_scheduled_for"), table_name="post")
    op.drop_column("post", "linkedin_post_id")
    op.drop_column("post", "reason_failed")
    op.drop_column("post", "scheduled_for")
    # ### end Alembic commands ###
