/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SuperImpress API
 * LinkedIn post management tool API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * Create a new post for the authenticated user
 * @summary Create a new post
 */

export const PostApiPostsBody = zod.object({
  title: zod.string().nullish(),
  content: zod.string().min(1),
  tags: zod.array(zod.string()).optional(),
});

/**
 * List posts for the authenticated user with optional filtering by status and tag
 * @summary List posts
 */
export const getApiPostsQueryLimitDefault = 100;
export const getApiPostsQueryLimitMax = 100;

export const getApiPostsQueryOffsetDefault = 0;
export const getApiPostsQueryOffsetMin = 0;

export const GetApiPostsQueryParams = zod.object({
  status: zod.enum(["draft", "published"]).optional(),
  tag: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(getApiPostsQueryLimitMax)
    .default(getApiPostsQueryLimitDefault),
  offset: zod
    .number()
    .min(getApiPostsQueryOffsetMin)
    .default(getApiPostsQueryOffsetDefault),
});

export const getApiPostsResponsePostsItemIdMin = -9007199254740991;
export const getApiPostsResponsePostsItemIdMax = 9007199254740991;

export const GetApiPostsResponse = zod.object({
  posts: zod.array(
    zod.object({
      id: zod
        .number()
        .min(getApiPostsResponsePostsItemIdMin)
        .max(getApiPostsResponsePostsItemIdMax),
      userId: zod.string(),
      title: zod.string().nullable(),
      content: zod.string(),
      tags: zod.array(zod.string()),
      status: zod.enum(["draft", "published"]),
      createdAt: zod.iso.datetime({}),
      updatedAt: zod.iso.datetime({}),
      publications: zod
        .array(
          zod.object({
            id: zod.number().min(1),
            platform: zod.enum(["linkedin", "twitter", "threads", "peerlist"]),
            platformPostId: zod.string().nullish(),
            url: zod.string().nullish(),
            accountId: zod.string().nullish(),
            publishedAt: zod.iso.datetime({}),
          })
        )
        .optional(),
    })
  ),
  total: zod.number(),
});

/**
 * Get summary stats and total word count for user posts
 * @summary Posts summary
 */
export const GetApiPostsSummaryResponse = zod.object({
  totalPosts: zod.number(),
  totalWordCount: zod.number(),
  statusCounts: zod.object({
    draft: zod.number(),
    published: zod.number(),
  }),
});

/**
 * Get a specific post by ID
 * @summary Get a post
 */
export const getApiPostsByIdPathIdRegExp = /^[0-9]+$/;

export const GetApiPostsByIdParams = zod.object({
  id: zod.string().regex(getApiPostsByIdPathIdRegExp),
});

export const getApiPostsByIdResponseIdMin = -9007199254740991;
export const getApiPostsByIdResponseIdMax = 9007199254740991;

export const GetApiPostsByIdResponse = zod.object({
  id: zod
    .number()
    .min(getApiPostsByIdResponseIdMin)
    .max(getApiPostsByIdResponseIdMax),
  userId: zod.string(),
  title: zod.string().nullable(),
  content: zod.string(),
  tags: zod.array(zod.string()),
  status: zod.enum(["draft", "published"]),
  createdAt: zod.iso.datetime({}),
  updatedAt: zod.iso.datetime({}),
  publications: zod
    .array(
      zod.object({
        id: zod.number().min(1),
        platform: zod.enum(["linkedin", "twitter", "threads", "peerlist"]),
        platformPostId: zod.string().nullish(),
        url: zod.string().nullish(),
        accountId: zod.string().nullish(),
        publishedAt: zod.iso.datetime({}),
      })
    )
    .optional(),
});

/**
 * Update a specific post by ID
 * @summary Update a post
 */
export const patchApiPostsByIdPathIdRegExp = /^[0-9]+$/;

export const PatchApiPostsByIdParams = zod.object({
  id: zod.string().regex(patchApiPostsByIdPathIdRegExp),
});

export const PatchApiPostsByIdBody = zod.object({
  title: zod.string().nullish(),
  content: zod.string().min(1).optional(),
  tags: zod.array(zod.string()).optional(),
});

export const patchApiPostsByIdResponseIdMin = -9007199254740991;
export const patchApiPostsByIdResponseIdMax = 9007199254740991;

export const PatchApiPostsByIdResponse = zod.object({
  id: zod
    .number()
    .min(patchApiPostsByIdResponseIdMin)
    .max(patchApiPostsByIdResponseIdMax),
  userId: zod.string(),
  title: zod.string().nullable(),
  content: zod.string(),
  tags: zod.array(zod.string()),
  status: zod.enum(["draft", "published"]),
  createdAt: zod.iso.datetime({}),
  updatedAt: zod.iso.datetime({}),
  publications: zod
    .array(
      zod.object({
        id: zod.number().min(1),
        platform: zod.enum(["linkedin", "twitter", "threads", "peerlist"]),
        platformPostId: zod.string().nullish(),
        url: zod.string().nullish(),
        accountId: zod.string().nullish(),
        publishedAt: zod.iso.datetime({}),
      })
    )
    .optional(),
});

/**
 * Delete a specific post by ID
 * @summary Delete a post
 */
export const deleteApiPostsByIdPathIdRegExp = /^[0-9]+$/;

export const DeleteApiPostsByIdParams = zod.object({
  id: zod.string().regex(deleteApiPostsByIdPathIdRegExp),
});

/**
 * Manually record that a post was published on a platform
 * @summary Mark post as published
 */
export const postApiPostsByIdPublicationsPathIdRegExp = /^[0-9]+$/;

export const PostApiPostsByIdPublicationsParams = zod.object({
  id: zod.string().regex(postApiPostsByIdPublicationsPathIdRegExp),
});

export const PostApiPostsByIdPublicationsBody = zod.object({
  platform: zod.enum(["linkedin", "twitter", "threads", "peerlist"]),
  url: zod.url(),
});

/**
 * Delete a publication history entry from a post for the authenticated user
 * @summary Delete publication record
 */
export const deleteApiPostsByIdPublicationsByPublicationIdPathIdRegExp =
  /^[0-9]+$/;
export const deleteApiPostsByIdPublicationsByPublicationIdPathPublicationIdRegExp =
  /^[0-9]+$/;

export const DeleteApiPostsByIdPublicationsByPublicationIdParams = zod.object({
  id: zod
    .string()
    .regex(deleteApiPostsByIdPublicationsByPublicationIdPathIdRegExp),
  publicationId: zod
    .string()
    .regex(
      deleteApiPostsByIdPublicationsByPublicationIdPathPublicationIdRegExp
    ),
});
