/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * SuperImpress API
 * LinkedIn post management tool API
 * OpenAPI spec version: 1.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { ErrorType } from ".././axios";

import { customInstance } from ".././axios";
import type {
  GetPostsParams,
  ManualPublicationRequest,
  ManualPublicationResponse,
  PostCreate,
  PostError,
  PostListResponse,
  PostResponse,
  PostSummaryResponse,
  PostUpdate,
} from "../superimpress.schemas";

/**
 * Create a new post for the authenticated user
 * @summary Create a new post
 */
export const postPosts = (postCreate: PostCreate, signal?: AbortSignal) => {
  return customInstance<PostResponse>({
    url: `/posts`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postCreate,
    signal,
  });
};

export const getPostPostsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPosts>>,
    TError,
    { data: PostCreate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPosts>>,
  TError,
  { data: PostCreate },
  TContext
> => {
  const mutationKey = ["postPosts"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPosts>>,
    { data: PostCreate }
  > = (props) => {
    const { data } = props ?? {};

    return postPosts(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPosts>>
>;
export type PostPostsMutationBody = PostCreate;
export type PostPostsMutationError = ErrorType<unknown>;

/**
 * @summary Create a new post
 */
export const usePostPosts = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPosts>>,
      TError,
      { data: PostCreate },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postPosts>>,
  TError,
  { data: PostCreate },
  TContext
> => {
  return useMutation(getPostPostsMutationOptions(options), queryClient);
};
/**
 * List posts for the authenticated user with optional filtering by status and tag
 * @summary List posts
 */
export const getPosts = (params?: GetPostsParams, signal?: AbortSignal) => {
  return customInstance<PostListResponse>({
    url: `/posts`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetPostsQueryKey = (params?: GetPostsParams) => {
  return [`/posts`, ...(params ? [params] : [])] as const;
};

export const getGetPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({
    signal,
  }) => getPosts(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPosts>>
>;
export type GetPostsQueryError = ErrorType<unknown>;

export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List posts
 */

export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get summary stats and total word count for user posts
 * @summary Posts summary
 */
export const getPostsSummary = (signal?: AbortSignal) => {
  return customInstance<PostSummaryResponse>({
    url: `/posts/summary`,
    method: "GET",
    signal,
  });
};

export const getGetPostsSummaryQueryKey = () => {
  return [`/posts/summary`] as const;
};

export const getGetPostsSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostsSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPostsSummary>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsSummaryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostsSummary>>> = ({
    signal,
  }) => getPostsSummary(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPostsSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostsSummary>>
>;
export type GetPostsSummaryQueryError = ErrorType<unknown>;

export function useGetPostsSummary<
  TData = Awaited<ReturnType<typeof getPostsSummary>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostsSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsSummary>>,
          TError,
          Awaited<ReturnType<typeof getPostsSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostsSummary<
  TData = Awaited<ReturnType<typeof getPostsSummary>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostsSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsSummary>>,
          TError,
          Awaited<ReturnType<typeof getPostsSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostsSummary<
  TData = Awaited<ReturnType<typeof getPostsSummary>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostsSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Posts summary
 */

export function useGetPostsSummary<
  TData = Awaited<ReturnType<typeof getPostsSummary>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostsSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostsSummaryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get a specific post by ID
 * @summary Get a post
 */
export const getPostsById = (id: string, signal?: AbortSignal) => {
  return customInstance<PostResponse>({
    url: `/posts/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetPostsByIdQueryKey = (id: string) => {
  return [`/posts/${id}`] as const;
};

export const getGetPostsByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostsById>>,
  TError = ErrorType<PostError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostsById>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostsById>>> = ({
    signal,
  }) => getPostsById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPostsById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostsById>>
>;
export type GetPostsByIdQueryError = ErrorType<PostError>;

export function useGetPostsById<
  TData = Awaited<ReturnType<typeof getPostsById>>,
  TError = ErrorType<PostError>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostsById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsById>>,
          TError,
          Awaited<ReturnType<typeof getPostsById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostsById<
  TData = Awaited<ReturnType<typeof getPostsById>>,
  TError = ErrorType<PostError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostsById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsById>>,
          TError,
          Awaited<ReturnType<typeof getPostsById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostsById<
  TData = Awaited<ReturnType<typeof getPostsById>>,
  TError = ErrorType<PostError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostsById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a post
 */

export function useGetPostsById<
  TData = Awaited<ReturnType<typeof getPostsById>>,
  TError = ErrorType<PostError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostsById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostsByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Update a specific post by ID
 * @summary Update a post
 */
export const patchPostsById = (
  id: string,
  postUpdate: PostUpdate,
  signal?: AbortSignal
) => {
  return customInstance<PostResponse>({
    url: `/posts/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: postUpdate,
    signal,
  });
};

export const getPatchPostsByIdMutationOptions = <
  TError = ErrorType<PostError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchPostsById>>,
    TError,
    { id: string; data: PostUpdate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchPostsById>>,
  TError,
  { id: string; data: PostUpdate },
  TContext
> => {
  const mutationKey = ["patchPostsById"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchPostsById>>,
    { id: string; data: PostUpdate }
  > = (props) => {
    const { id, data } = props ?? {};

    return patchPostsById(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchPostsByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchPostsById>>
>;
export type PatchPostsByIdMutationBody = PostUpdate;
export type PatchPostsByIdMutationError = ErrorType<PostError>;

/**
 * @summary Update a post
 */
export const usePatchPostsById = <
  TError = ErrorType<PostError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchPostsById>>,
      TError,
      { id: string; data: PostUpdate },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof patchPostsById>>,
  TError,
  { id: string; data: PostUpdate },
  TContext
> => {
  return useMutation(getPatchPostsByIdMutationOptions(options), queryClient);
};
/**
 * Delete a specific post by ID
 * @summary Delete a post
 */
export const deletePostsById = (id: string, signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/posts/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeletePostsByIdMutationOptions = <
  TError = ErrorType<PostError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePostsById>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePostsById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deletePostsById"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePostsById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deletePostsById(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePostsByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePostsById>>
>;

export type DeletePostsByIdMutationError = ErrorType<PostError>;

/**
 * @summary Delete a post
 */
export const useDeletePostsById = <
  TError = ErrorType<PostError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePostsById>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deletePostsById>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeletePostsByIdMutationOptions(options), queryClient);
};
/**
 * Manually record that a post was published on a platform
 * @summary Mark post as published
 */
export const postPostsByIdPublications = (
  id: string,
  manualPublicationRequest: ManualPublicationRequest,
  signal?: AbortSignal
) => {
  return customInstance<ManualPublicationResponse>({
    url: `/posts/${id}/publications`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: manualPublicationRequest,
    signal,
  });
};

export const getPostPostsByIdPublicationsMutationOptions = <
  TError = ErrorType<PostError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPostsByIdPublications>>,
    TError,
    { id: string; data: ManualPublicationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPostsByIdPublications>>,
  TError,
  { id: string; data: ManualPublicationRequest },
  TContext
> => {
  const mutationKey = ["postPostsByIdPublications"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPostsByIdPublications>>,
    { id: string; data: ManualPublicationRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postPostsByIdPublications(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostsByIdPublicationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPostsByIdPublications>>
>;
export type PostPostsByIdPublicationsMutationBody = ManualPublicationRequest;
export type PostPostsByIdPublicationsMutationError = ErrorType<PostError>;

/**
 * @summary Mark post as published
 */
export const usePostPostsByIdPublications = <
  TError = ErrorType<PostError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPostsByIdPublications>>,
      TError,
      { id: string; data: ManualPublicationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postPostsByIdPublications>>,
  TError,
  { id: string; data: ManualPublicationRequest },
  TContext
> => {
  return useMutation(
    getPostPostsByIdPublicationsMutationOptions(options),
    queryClient
  );
};
/**
 * Delete a publication history entry from a post for the authenticated user
 * @summary Delete publication record
 */
export const deletePostsByIdPublicationsByPublicationId = (
  id: string,
  publicationId: string,
  signal?: AbortSignal
) => {
  return customInstance<void>({
    url: `/posts/${id}/publications/${publicationId}`,
    method: "DELETE",
    signal,
  });
};

export const getDeletePostsByIdPublicationsByPublicationIdMutationOptions = <
  TError = ErrorType<PostError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePostsByIdPublicationsByPublicationId>>,
    TError,
    { id: string; publicationId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePostsByIdPublicationsByPublicationId>>,
  TError,
  { id: string; publicationId: string },
  TContext
> => {
  const mutationKey = ["deletePostsByIdPublicationsByPublicationId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePostsByIdPublicationsByPublicationId>>,
    { id: string; publicationId: string }
  > = (props) => {
    const { id, publicationId } = props ?? {};

    return deletePostsByIdPublicationsByPublicationId(id, publicationId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePostsByIdPublicationsByPublicationIdMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof deletePostsByIdPublicationsByPublicationId>>
  >;

export type DeletePostsByIdPublicationsByPublicationIdMutationError =
  ErrorType<PostError>;

/**
 * @summary Delete publication record
 */
export const useDeletePostsByIdPublicationsByPublicationId = <
  TError = ErrorType<PostError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePostsByIdPublicationsByPublicationId>>,
      TError,
      { id: string; publicationId: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deletePostsByIdPublicationsByPublicationId>>,
  TError,
  { id: string; publicationId: string },
  TContext
> => {
  return useMutation(
    getDeletePostsByIdPublicationsByPublicationIdMutationOptions(options),
    queryClient
  );
};
