/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * Create a new post for the authenticated user.
 * @summary Create Post Endpoint
 */
export const createPostBodyTitleOneMax = 255;

export const CreatePostBody = zod
	.object({
		title: zod
			.union([zod.string().min(1).max(createPostBodyTitleOneMax), zod.null()])
			.optional()
			.describe('Post title'),
		content: zod.string().min(1).describe('Post content'),
		tags: zod.array(zod.string()).optional().describe('Post tags'),
		status: zod
			.enum(['draft', 'published', 'archived'])
			.optional()
			.describe('Post status enumeration.')
	})
	.describe('Schema for creating a new post.');

/**
 * List posts for the authenticated user with optional filters.
 * @summary List Posts Endpoint
 */
export const listPostsQueryLimitDefault = 100;
export const listPostsQueryLimitMax = 100;

export const listPostsQueryOffsetDefault = 0;
export const listPostsQueryOffsetMin = 0;

export const ListPostsQueryParams = zod.object({
	status: zod
		.union([
			zod.enum(['draft', 'published', 'archived']).describe('Post status enumeration.'),
			zod.null()
		])
		.optional()
		.describe('Filter by post status'),
	tag: zod.union([zod.string(), zod.null()]).optional().describe('Filter by tag'),
	limit: zod
		.number()
		.min(1)
		.max(listPostsQueryLimitMax)
		.default(listPostsQueryLimitDefault)
		.describe('Number of posts to return'),
	offset: zod
		.number()
		.min(listPostsQueryOffsetMin)
		.default(listPostsQueryOffsetDefault)
		.describe('Number of posts to skip')
});

export const listPostsResponsePostsItemTitleOneMax = 255;

export const ListPostsResponse = zod
	.object({
		posts: zod.array(
			zod
				.object({
					title: zod
						.union([zod.string().min(1).max(listPostsResponsePostsItemTitleOneMax), zod.null()])
						.optional()
						.describe('Post title'),
					content: zod.string().min(1).describe('Post content'),
					tags: zod.array(zod.string()).optional().describe('Post tags'),
					id: zod.number(),
					user_id: zod.number(),
					status: zod.enum(['draft', 'published', 'archived']).describe('Post status enumeration.'),
					created_at: zod.string().datetime({}),
					updated_at: zod.string().datetime({})
				})
				.describe('Schema for post public data.')
		),
		total: zod.number()
	})
	.describe('Response schema for listing posts.');

/**
 * Get a specific post by ID.
 * @summary Get Post Endpoint
 */
export const GetPostParams = zod.object({
	post_id: zod.number()
});

export const getPostResponseTitleOneMax = 255;

export const GetPostResponse = zod
	.object({
		title: zod
			.union([zod.string().min(1).max(getPostResponseTitleOneMax), zod.null()])
			.optional()
			.describe('Post title'),
		content: zod.string().min(1).describe('Post content'),
		tags: zod.array(zod.string()).optional().describe('Post tags'),
		id: zod.number(),
		user_id: zod.number(),
		status: zod.enum(['draft', 'published', 'archived']).describe('Post status enumeration.'),
		created_at: zod.string().datetime({}),
		updated_at: zod.string().datetime({})
	})
	.describe('Schema for post public data.');

/**
 * Update a specific post.
 * @summary Update Post Endpoint
 */
export const UpdatePostParams = zod.object({
	post_id: zod.number()
});

export const updatePostBodyTitleOneMax = 255;

export const UpdatePostBody = zod
	.object({
		title: zod.union([zod.string().min(1).max(updatePostBodyTitleOneMax), zod.null()]).optional(),
		content: zod.union([zod.string().min(1), zod.null()]).optional(),
		tags: zod.union([zod.array(zod.string()), zod.null()]).optional(),
		status: zod
			.union([
				zod.enum(['draft', 'published', 'archived']).describe('Post status enumeration.'),
				zod.null()
			])
			.optional()
	})
	.describe('Schema for updating a post (all fields optional).');

export const updatePostResponseTitleOneMax = 255;

export const UpdatePostResponse = zod
	.object({
		title: zod
			.union([zod.string().min(1).max(updatePostResponseTitleOneMax), zod.null()])
			.optional()
			.describe('Post title'),
		content: zod.string().min(1).describe('Post content'),
		tags: zod.array(zod.string()).optional().describe('Post tags'),
		id: zod.number(),
		user_id: zod.number(),
		status: zod.enum(['draft', 'published', 'archived']).describe('Post status enumeration.'),
		created_at: zod.string().datetime({}),
		updated_at: zod.string().datetime({})
	})
	.describe('Schema for post public data.');

/**
 * Delete a specific post.
 * @summary Delete Post Endpoint
 */
export const DeletePostParams = zod.object({
	post_id: zod.number()
});
