/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import { createMutation } from '@tanstack/svelte-query';
import type {
	CreateMutationOptions,
	CreateMutationResult,
	MutationFunction,
	QueryClient
} from '@tanstack/svelte-query';

import type {
	EmailVerificationConfirm,
	EmailVerificationRequest,
	EmailVerificationResponse,
	HTTPValidationError
} from '../superimpress.schemas';

import { customInstance } from '.././axios';
import type { ErrorType } from '.././axios';

/**
 * Verify user's email with token.
 * @summary Verify Email
 */
export const verifyEmail = (
	emailVerificationConfirm: EmailVerificationConfirm,
	signal?: AbortSignal
) => {
	return customInstance<EmailVerificationResponse>({
		url: `/api/verify`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: emailVerificationConfirm,
		signal
	});
};

export const getVerifyEmailMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof verifyEmail>>,
		TError,
		{ data: EmailVerificationConfirm },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof verifyEmail>>,
	TError,
	{ data: EmailVerificationConfirm },
	TContext
> => {
	const mutationKey = ['verifyEmail'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof verifyEmail>>,
		{ data: EmailVerificationConfirm }
	> = (props) => {
		const { data } = props ?? {};

		return verifyEmail(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type VerifyEmailMutationResult = NonNullable<Awaited<ReturnType<typeof verifyEmail>>>;
export type VerifyEmailMutationBody = EmailVerificationConfirm;
export type VerifyEmailMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Verify Email
 */
export const createVerifyEmail = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof verifyEmail>>,
			TError,
			{ data: EmailVerificationConfirm },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof verifyEmail>>,
	TError,
	{ data: EmailVerificationConfirm },
	TContext
> => {
	const mutationOptions = getVerifyEmailMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * Request email verification for authenticated user.
 * @summary Request Verification
 */
export const requestVerification = (signal?: AbortSignal) => {
	return customInstance<EmailVerificationResponse>({
		url: `/api/verify/request`,
		method: 'POST',
		signal
	});
};

export const getRequestVerificationMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof requestVerification>>,
		TError,
		void,
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof requestVerification>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ['requestVerification'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof requestVerification>>,
		void
	> = () => {
		return requestVerification();
	};

	return { mutationFn, ...mutationOptions };
};

export type RequestVerificationMutationResult = NonNullable<
	Awaited<ReturnType<typeof requestVerification>>
>;

export type RequestVerificationMutationError = ErrorType<unknown>;

/**
 * @summary Request Verification
 */
export const createRequestVerification = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof requestVerification>>,
			TError,
			void,
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof requestVerification>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getRequestVerificationMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * Resend verification email.
 * @summary Resend Verification
 */
export const resendVerification = (
	emailVerificationRequest: EmailVerificationRequest,
	signal?: AbortSignal
) => {
	return customInstance<EmailVerificationResponse>({
		url: `/api/verify/resend`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: emailVerificationRequest,
		signal
	});
};

export const getResendVerificationMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof resendVerification>>,
		TError,
		{ data: EmailVerificationRequest },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof resendVerification>>,
	TError,
	{ data: EmailVerificationRequest },
	TContext
> => {
	const mutationKey = ['resendVerification'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof resendVerification>>,
		{ data: EmailVerificationRequest }
	> = (props) => {
		const { data } = props ?? {};

		return resendVerification(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type ResendVerificationMutationResult = NonNullable<
	Awaited<ReturnType<typeof resendVerification>>
>;
export type ResendVerificationMutationBody = EmailVerificationRequest;
export type ResendVerificationMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Resend Verification
 */
export const createResendVerification = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown
>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof resendVerification>>,
			TError,
			{ data: EmailVerificationRequest },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof resendVerification>>,
	TError,
	{ data: EmailVerificationRequest },
	TContext
> => {
	const mutationOptions = getResendVerificationMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
