name: Docs Checks

on:
  pull_request:
    branches: [main]
    paths:
      - "docs/**"

jobs:
  docs-checks:
    name: Docs Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: docs

      - name: Check Formatting & Linting
        run: bun run check
        working-directory: docs

      - name: Check Types
        run: bun run types:check
        working-directory: docs
